### ISSUE TITLE
Consider separating service protos into different files

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#1]
Currently all files are in a single proto.
https://github.com/GoogleCloudPlatform/microservices-demo/blob/4572974c882b7c159a59e5344a3aa42c7f4af040/pb/demo.proto

Ideally we should have per-service protos like `pb/hipstershop/currencyservice.proto` etc.

**Comment by DanSanche** [comment]
Closing this and other `kind/improvement` issues as we attempt to move the project into a stable maintenance state

**Comment by askmeegs** [comment]
Reopening to resume the discussion and triage.

**Comment by mathieu-benoit** [comment]
Could candidate to be tackle in https://github.com/GoogleCloudPlatform/microservices-demo/issues/814 too.

**Comment by NimJay** [comment]
Commenting to cool this issue down (from our team's out-of-SLO list):
We should still address this issue. I'll leave it open.

**Comment by bourgeoisor** [comment]
Closing this issue in favour of the bigger-scope https://github.com/GoogleCloudPlatform/microservices-demo/issues/814
