### ISSUE TITLE
cartservice: move tests/ dir out of root

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#10]
`/tests/cartservice` should go be moved to `/src/cartservice/tests/cartservice`.

**Comment by djmailhot** [comment]
> Does vs or vscode’s .NET/C# support understand this approach and still able to run the tests from the IDE?
- @ahmetb

**Comment by DanSanche** [comment]
@djmailhot Do you have any objections to this? I'd say IDE tests aren't too important

**Comment by djmailhot** [comment]
@DanSanche Apologies, I'm confused.  What is your question again?

**Comment by DanSanche** [comment]
I think ahmet was suggesting moving the test from `/tests/cartservice` to `/src/cartservice/tests/cartservice` to be consistent with the other services. Any objections? Were you saying that would break IDE tests or something?

**Comment by djmailhot** [comment]
> `/tests/cartservice` should go be moved to `/src/cartservice/tests/cartservice`.

Turns out that you [can't nest one CS project within another](https://github.com/xunit/xunit/issues/1467#issuecomment-333404867).

**Comment by djmailhot** [comment]
My PR is useless, so I'll delete it and release this issue
