### ISSUE TITLE
service pending

### ISSUE THREAD

**Issue by HichamOuguerzi** [GoogleCloudPlatform/microservices-demo#100]
Hi,
Thank you for this great demo.
I'm running the demo locally with docker Desktop. I can't access the home page and the following pods are pending : paymentservice, productcatalogservice, recommendationservice and shippingservice.

Please help!

rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 10.100.182.255:3550: i/o timeout"
could not retrieve products
main.(*frontendServer).homeHandler
	/go/src/github.com/GoogleCloudPlatform/microservices-demo/src/frontend/handlers.go:53
main.(*frontendServer).(main.homeHandler)-fm
	/go/src/github.com/GoogleCloudPlatform/microservices-demo/src/frontend/main.go:122
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:1947
github.com/GoogleCloudPlatform/microservices-demo/src/frontend/vendor/github.com/gorilla/mux.(*Router).ServeHTTP
	/go/src/github.com/GoogleCloudPlatform/microservices-demo/src/frontend/vendor/github.com/gorilla/mux/mux.go:162
main.(*logHandler).ServeHTTP
	/go/src/github.com/GoogleCloudPlatform/microservices-demo/src/frontend/middleware.go:81
main.ensureSessionID.func1
	/go/src/github.com/GoogleCloudPlatform/microservices-demo/src/frontend/middleware.go:103
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:1947
github.com/GoogleCloudPlatform/microservices-demo/src/frontend/vendor/go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP
	/go/src/github.com/GoogleCloudPlatform/microservices-demo/src/frontend/vendor/go.opencensus.io/plugin/ochttp/server.go:82
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2697
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1830
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2361

**Comment by ahmetb** [comment]
The demo is meant to be deployed on Kubernetes. Are you using Kubernetes on docker for desktop?

Error message clearly indicates can’t reach the pod’s IP:port. Try deploying to a real Kubernetes cluster perhaps, but I am confident it works on Kubernetes for Docker for Desktop.

**Comment by HichamOuguerzi** [comment]
I'm using k8s on docker for desktop.
$kubectl get nodes
NAME                 STATUS    ROLES     AGE       VERSION
docker-for-desktop   Ready     master    1d        v1.10.3
I followed Option 1 installation as indicated on the readme.
payment, recommendations and shipping services are pending.
<img width="548" alt="screen shot 2018-11-26 at 20 29 34" src="https://user-images.githubusercontent.com/23150695/49037281-1dbdf700-f1ba-11e8-8862-32a0ccfca04f.png">

**Comment by ahmetb** [comment]
Please do `kubectl describe pods`. 
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-application/ your cluster may not have enough space (RAM, CPU etc) to schedule all these pods.

**Comment by HichamOuguerzi** [comment]
here, thank you for your help.
<img width="825" alt="screen shot 2018-11-26 at 21 47 40" src="https://user-images.githubusercontent.com/23150695/49041335-3f70ab80-f1c5-11e8-88c8-68f97ad02d7d.png">

**Comment by ahmetb** [comment]
Yep, looks like your CPU isn't enough.
Use Settings for Docker for Mac to increase CPU for the VM.
