### ISSUE TITLE
AdService trace logging is reported as Error instead of Info.

### ISSUE THREAD

**Issue by rghetia** [GoogleCloudPlatform/microservices-demo#101]
Here is the sample log.

 insertId: "8m85fufgieo83"  
 labels: {
  compute.googleapis.com/resource_name: "fluentd-gcp-v2.0.17-pmqdr"   
  container.googleapis.com/namespace_name: "default"   
  container.googleapis.com/pod_name: "adservice-74bd8cb69-sw8wj"   
  container.googleapis.com/stream: "stderr"   
 }
 logName: "projects/microservices-demo-223307/logs/server"  
 receiveTimestamp: "2018-11-30T11:52:04.363633212Z"  
 resource: {
  labels: {
   cluster_name: "demo"    
   container_name: "server"    
   instance_id: "8772787556939461677"    
   namespace_id: "default"    
   pod_id: "adservice-74bd8cb69-sw8wj"    
   project_id: "microservices-demo-223307"    
   zone: "europe-west4-b"    
  }
  type: "container"   
 }
 severity: "ERROR"  
 textPayload: "INFO: SpanData{context=SpanContext{traceId=TraceId{traceId=0000000000000000aa4969b250fd2c88}, spanId=SpanId{spanId=edb2a981d3d2dfa0}, traceOptions=TraceOptions{sampled=true}}, parentSpanId=SpanId{spanId=3527fd550f2d50ee}, hasRemoteParent=true, name=Recv.hipstershop.AdService.GetAds, kind=null, startTimestamp=Timestamp{seconds=1543578721, nanos=420000047}, attributes=Attributes{attributeMap={}, droppedAttributesCount=0}, annotations=TimedEvents{events=[], droppedEventsCount=0}, messageEvents=TimedEvents{events=[TimedEvent{timestamp=Timestamp{seconds=1543578721, nanos=420086897}, event=MessageEvent{type=RECEIVED, messageId=0, uncompressedMessageSize=0, compressedMessageSize=0}}, TimedEvent{timestamp=Timestamp{seconds=1543578721, nanos=420566443}, event=MessageEvent{type=SENT, messageId=0, uncompressedMessageSize=116, compressedMessageSize=116}}], droppedEventsCount=0}, links=Links{links=[], droppedLinksCount=0}, childSpanCount=null, status=Status{canonicalCode=OK, description=null}, endTimestamp=Timestamp{seconds=1543578721, nanos=420769048}}
"  
 timestamp: "2018-11-30T11:52:02Z"

**Comment by ahmetb** [comment]
Looks like a Stackdriver Logging issue about detecting the severity from message?

**Comment by kbhattac** [comment]
> Here is the sample log.
> 
> insertId: "8m85fufgieo83"
> labels: {
> compute.googleapis.com/resource_name: "fluentd-gcp-v2.0.17-pmqdr"
> container.googleapis.com/namespace_name: "default"
> container.googleapis.com/pod_name: "adservice-74bd8cb69-sw8wj"
> container.googleapis.com/stream: "stderr"
> }
> logName: "projects/microservices-demo-223307/logs/server"
> receiveTimestamp: "2018-11-30T11:52:04.363633212Z"
> resource: {
> labels: {
> cluster_name: "demo"
> container_name: "server"
> instance_id: "8772787556939461677"
> namespace_id: "default"
> pod_id: "adservice-74bd8cb69-sw8wj"
> project_id: "microservices-demo-223307"
> zone: "europe-west4-b"
> }
> type: "container"
> }
> severity: "ERROR"
> textPayload: "INFO: SpanData{context=SpanContext{traceId=TraceId{traceId=0000000000000000aa4969b250fd2c88}, spanId=SpanId{spanId=edb2a981d3d2dfa0}, traceOptions=TraceOptions{sampled=true}}, parentSpanId=SpanId{spanId=3527fd550f2d50ee}, hasRemoteParent=true, name=Recv.hipstershop.AdService.GetAds, kind=null, startTimestamp=Timestamp{seconds=1543578721, nanos=420000047}, attributes=Attributes{attributeMap={}, droppedAttributesCount=0}, annotations=TimedEvents{events=[], droppedEventsCount=0}, messageEvents=TimedEvents{events=[TimedEvent{timestamp=Timestamp{seconds=1543578721, nanos=420086897}, event=MessageEvent{type=RECEIVED, messageId=0, uncompressedMessageSize=0, compressedMessageSize=0}}, TimedEvent{timestamp=Timestamp{seconds=1543578721, nanos=420566443}, event=MessageEvent{type=SENT, messageId=0, uncompressedMessageSize=116, compressedMessageSize=116}}], droppedEventsCount=0}, links=Links{links=[], droppedLinksCount=0}, childSpanCount=null, status=Status{canonicalCode=OK, description=null}, endTimestamp=Timestamp{seconds=1543578721, nanos=420769048}}
> "
> timestamp: "2018-11-30T11:52:02Z"

Thanks for registering the issue on my behalf :-)

**Comment by DanSanche** [comment]
I'm not seeing this error for the `adservice`, but I do see it for some others. I opened a PR for this here: https://github.com/GoogleCloudPlatform/microservices-demo/pull/245
