### ISSUE TITLE
Readiness and liveness probes failing on local cluster

### ISSUE THREAD

**Issue by bpastiu** [GoogleCloudPlatform/microservices-demo#1047]
Hi there and thanks a lot for this project. I am trying to deploy this project using Tilt (https://tilt.dev/) for local development. The pods go up but they start failing almost immediately due to liveness and readiness probes failure.
I am using docker-desktop on mac arm 64. I built the images using the --platform flag for `linux/amd64`

Not sure if this is something related to my setup or otherwise.

Didn't see anyone trying out tilt so maybe I am overreaching. Here is a screenshot.
![tilt](https://user-images.githubusercontent.com/9333829/190127112-6c5b77e5-cf8a-47c4-888e-53b1197c8177.png)

Again, thanks for all the hard work.

**Comment by v-bpastiu** [comment]
Disregard that. I got it to work after messing around with the grpc_health_probe connect timeouts. Made them bigger than 1s and apparently it worked.

**Comment by NimJay** [comment]
Glad you were able to find a workaround. I will close this issue.
