### ISSUE TITLE
Terraform's `kubectl wait --for=condition=ready pods ...` hangs

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/microservices-demo#1079]
### Describe the bug 
* According to this [Google-internal Doc](https://docs.google.com/document/d/1r-1osqq1PYUq6O9IMj1Y_J2Z3ivrn6d1wXE4HbHsops/edit#), Online Boutique's default Terraform (in [/main/terraform](https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/terraform)) sometimes hangs.
* More specifically, it's the ["kubectl wait" condition inside main.tf](https://github.com/GoogleCloudPlatform/microservices-demo/blob/4ad3226fe803049b587277678664536f003f74b3/terraform/main.tf#L86) that hangs.

### To Reproduce 
* I have not reproduced the issue myself yet.
* But we can _try_ to reproduce this issue by running the `terraform apply` (as seen in [/terraform/README.md](https://github.com/GoogleCloudPlatform/microservices-demo/tree/4ad3226fe803049b587277678664536f003f74b3/terraform#deploy-the-sample-application)) multiple times.

### Logs  
* N/A

### Screenshots 
* N/A

### Environment 
* TBD

### Additional context 
* tpryan@ might be able to provide additional context.

### Exposure 
* This would affect anyone using Terraform to deploy Online Boutique.

**Comment by NimJay** [comment]
tpryan@
Is my assumption correct: you witnessed this issue when Cloud Build tried running [this line](https://github.com/tpryan/microservices-demo/blob/88d6e80a8d571eeef68a6a9528c4dbfa64e9d59d/test#L75)?

**Comment by tpryan** [comment]
Yes. But it also occurred during manual tests - ie calling terraform directly, and not in the test script.

**Comment by tpryan** [comment]
It's intermittent. And I can't tell what variables are changing. I have a build job that runs it every night. So in theory I will get logs for you to sift through eventually. :)

**Comment by minherz** [comment]
@NimJay i suggest to close this item. there is no clear reproduction path. as an option, we can add a timeout argument to the relevant Terraform configurations to avoid tests to hang out forever.

**Comment by NimJay** [comment]
## Issue Disappeared

* I took a quick look at the [last 100 "build histories" of the DeployStack tests](https://screenshot.googleplex.com/6mSzPFPqReQMgTM.png).
* Each test attempts to run Online Boutique's Terraform. The Cloud Build Triggers are configured by [/.deploystack/test.yaml](https://github.com/GoogleCloudPlatform/microservices-demo/blob/release/v0.5.2/.deploystack/test.yaml) and [/.deploystack/test](https://github.com/GoogleCloudPlatform/microservices-demo/blob/release/v0.5.2/.deploystack/test).
* 3 of the 100 builds failed, but those 3 failures are not related to the `kubectl wait` issues reports in _this_ issue.
* It should be safe to close this issue now (as per @minherz's suggestion).
