### ISSUE TITLE
Deploy it on a local Kubernetes cluster with istio Jaeger tracing enabled

### ISSUE THREAD

**Issue by aghag10** [GoogleCloudPlatform/microservices-demo#108]
Hi,

I wanted to deploy the application on a local Kubernetes cluster, where I have installed istio. Istio Jaeger tracing is enabled. I was wondering if the microservices have any instrumentation done for Jaeger? 
Also, what are the steps to deploy the application on a local Kubernetes cluster?

 kubectl apply -f ../kubernetes-manifests/

Looks like the images are not pushed to public Docker repo - 
default        adservice-7d87b789dc-gcxxf                                   0/1       ImagePullBackOff   0          45s
default        adservice-fbcc45f96-vpsqd                                    0/2       Terminating        0          9m
default        cartservice-7dd67f5c98-68jvt                                 0/1       ImagePullBackOff   0          45s
default        checkoutservice-78b864646c-g6cmx                             0/1       ImagePullBackOff   0          45s
default        currencyservice-7b4b9b8995-4r6dp                             0/1       ImagePullBackOff   0          45s
default        emailservice-7f98964f6-nvvmv                                 0/1       ImagePullBackOff   0          45s
default        frontend-6997f7b6d8-vsmmg                                    0/1       ImagePullBackOff   0          45s
default        loadgenerator-6bd89f959b-b74x9                               0/1       Init:0/1           0          45s
default        paymentservice-6b5564854c-48482                              0/1       ErrImagePull       0          44s
default        productcatalogservice-b4c4966d9-gkst4                        0/1       ImagePullBackOff   0          44s
default        recommendationservice-7c77f6bff5-5448r                       0/1       ImagePullBackOff   0          44s
default        redis-cart-77d754f696-v76fh                                  1/1       Running            0          44s
default        shippingservice-6bd888b795-l4pxw                             0/1       ImagePullBackOff   0          44s

kubectl describe pod cartservice-7dd67f5c98-68jvt
Failed to pull image "cartservice": rpc error: code = Unknown desc = Error response from daemon: repository cartservice not found: does not exist or no pull access

Thanks!

**Comment by ahmetb** [comment]
> I was wondering if the microservices have any instrumentation done for Jaeger?

We use OpenCensus, so if you configure stuff correctly, I think it _can_ export to Jaeger. There's work happening to show this working, but won't land soon. (cc: @rghetia)



> Also, what are the steps to deploy the application on a local Kubernetes cluster?

Just create a minikube cluster and run `skaffold run` (see instructions in README). You can't directly apply the manifests, you'll definitely get ImagePull without building the images onto the local cluster.

**Comment by aghag10** [comment]
Thanks for your replies.

> > I was wondering if the microservices have any instrumentation done for Jaeger?
> 
> We use OpenCensus, so if you configure stuff correctly, I think it _can_ export to Jaeger. There's work happening to show this working, but won't land soon. (cc: @rghetia)
> 

Can you elaborate on "configure stuff correctly"? If I deploy the application with istio sidecars (using istioctl kube-inject command), would istio sidecars be able to inject and forward http headers?

> > Also, what are the steps to deploy the application on a local Kubernetes cluster?
> 
> Just create a minikube cluster and run `skaffold run` (see instructions in README). You can't directly apply the manifests, you'll definitely get ImagePull without building the images onto the local cluster.

I'm not using minikube. I already have a locally deployed Kubernetes cluster using kubeadm. Would skaffold run still work?

**Comment by ahmetb** [comment]
I'd recommend reading up on how OpenCensus works with Jaeger. (I'm not familiar with this myself but) you most likely need to configure the OpenCensus exporters in the application code to export spans/traces to Jaeger.

> If I deploy the application with istio sidecars

See README.md, we recommend enabling auto-sidecar injection in the namespace. (You won't be able to use istioctl with skaffold.) Tracing, in this case, has nothing to do with Istio (you can use it without Istio). Istio will give you a correlation ID header, but it's not capable of associating which incoming requests are correlated to which outgoing requests (that's something we do in the app code with OpenCensus).

**Comment by aghag10** [comment]
> > Also, what are the steps to deploy the application on a local Kubernetes cluster?
> 
> Just create a minikube cluster and run `skaffold run` (see instructions in README). You can't directly apply the manifests, you'll definitely get ImagePull without building the images onto the local cluster.

I'm not using minikube. I already have a locally deployed Kubernetes cluster using kubeadm. Would skaffold run still work?

It's failing with this error - 

skaffold run
WARN[0000] config version (skaffold/v1alpha5) out of date: upgrading to latest (skaffold/v1beta2)
Starting build...
Building [emailservice]...
2018/12/27 15:01:40 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
Sending build context to Docker daemon  98.82kB
Step 1/14 : FROM python:3-alpine as base
FATA[0001] build failed: building [emailservice]: build artifact: running build: Error parsing reference: "python:3-alpine as base" is not a valid repository/tag: invalid reference format

**Comment by ahmetb** [comment]
I opened #109 to track.

It's in our goals to support local (non-GCP) installation as well as GCP. So far we only focused on getting traces exported to Stackdriver Tracing. (Today, it would spit the traces out to stdout on minikube etc).

I believe OpenCensus is designing an in-cluster agent model which would be a single component all traces are sent to (and from there, exported to Stackdriver, Jaeger etc). I don't think the agent is ready for use yet, but it would solve the problem (without changing the app code much).

**Comment by ahmetb** [comment]
Oh yeah you linked to opencensus-service, which I was referring to as the _agent_ above.

**Comment by ahmetb** [comment]
btw I missed one of your comments:

> I'm not using minikube. I already have a locally deployed Kubernetes cluster using kubeadm. Would skaffold run still work?

It should, but since cluster isn't a recognized local tool (docker-for-mac or minikube etc) it will have to push the images to a public registry first, and have the k8s node pull the images from there. (read this post to understand how skaffold works: https://ahmet.im/blog/skaffold/).

I recommend starting with docker-for-desktop or minikube instead of kubeadm first.

> FATA[0001] build failed: building [emailservice]: build artifact: running build: Error parsing reference: "python:3-alpine as base" is not a valid repository/tag: invalid reference format

I think this is because the docker engine you have on the machine is pretty old and doesn't support Multi-Stage Docker Builds feature yet (it thinks that whole string is the image name but it's not).

**Comment by aghag10** [comment]
> > FATA[0001] build failed: building [emailservice]: build artifact: running build: Error parsing reference: "python:3-alpine as base" is not a valid repository/tag: invalid reference format
> 
> I think this is because the docker engine you have on the machine is pretty old and doesn't support Multi-Stage Docker Builds feature yet (it thinks that whole string is the image name but it's not).

Thanks a lot. That fixed the issue. It was able to pull most of the images, but now it's failing with this error. 
  File "/tmp/pip-install-2x648y68/PyGObject/setup.py", line 777, in find_new_api
      import cairo
  **ModuleNotFoundError: No module named 'cairo'

  ----------------------------------------
  Failed building wheel for PyGObject**
  Running setup.py clean for PyGObject
: 
: 
FATA[0001] build failed: building [emailservice]: tagging: pushing: denied: requested access to the resource is denied

I've already manually installed cairo package. 
apt install libcairo2-dev
pip install cairocffi
pip install https://files.pythonhosted.org/packages/68/76/340ff847897296b2c8174dfa5a5ec3406e3ed783a2abac918cf326abad86/pycairo-1.17.1.tar.gz
  Stored in directory: /root/.cache/pip/wheels/99/b7/64/8eb1df08bd90f2699736ed6658e2250bf58202b8ff2e5f3a72
Successfully built pycairo
Installing collected packages: pycairo
Successfully installed pycairo-1.17.1

The package is listed as a requirement for emailservice so it should automatically be downloaded when I run skaffold run. Can you please take a look? Thanks!

**Comment by ahmetb** [comment]
@aghag10 please open a separate issue for these stuff. This issue discusses Jaeger. Try doing a "git pull" if you haven't done recently.
