### ISSUE TITLE
Export traces to Jaeger if installed

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#109]
(This came up in #108 and I believe some work is already happening.)

I'd love to have the demo app export traces to a local Jaeger installation ideally with minimal to no config changes.

I'm not sure how we can detect a jaeger installation uniformly and register it as an exporter (that works alongside with Stackdriver exporter) in multiple languages.

cc: @rghetia

**Comment by rghetia** [comment]
@ahmethb Jaeger itself doesn't support any discovery mechanism. Is environment variable approach not sufficient? Alternatively, a simple GET query on port 16686 of jaeger service (assuming the service is named jaeger) can be used to determine if the service is available or not.

btw, I haven't got a chance to look at adding jaeger/grafana/promethues  to microservice demo. If some can help add those service then I can add the instrumentation part.

**Comment by ahmetb** [comment]
> Jaeger itself doesn't support any discovery mechanism. Is environment variable approach not sufficient?

how would this look like? 

Right now we have a simple check like `if isOnGCE(){registerStackdriverExporter()}` in all languages. (Some languages have this explicitly, and some languages have it in the Stackdriver SDK register method, which fails silently if it's not on GCE).

Also would it be possible to have multiple exporters (i.e. both jaeger and gce) simultaneously?

**Comment by rghetia** [comment]
yes, it is possible to have multiple exporter.
In each service specific .yaml file set env (e.g JAEGER_ENABLE=true). This does require user to change the yaml file though. Not sure if there is a way to set the env for all micro-services while deploying it (or using some global config).

**Comment by ahmetb** [comment]
We can take a shortcut like `helm init && helm install stable/jaeger-operator` to install [this Helm chart](https://github.com/helm/charts/tree/master/stable/jaeger-operator) in the README if folks want to try Jaeger integration.

Ideally we shouldn't maintain Jaeger kubernetes deployment manifests.

**Comment by ahmetb** [comment]
That looks like a cleaner solution. Is the oc-agent ready for use here? If so, I'd be happy to scrub SD/Jaeger specific code from each microservice.

**Comment by rghetia** [comment]
OcAgent is ready. 
Here is how it is used in our [interoptest](https://github.com/census-ecosystem/opencensus-experiments/tree/master/interoptest). It is based on hipstershop-demo model.
 
OcAgent export for
[Go](https://github.com/census-ecosystem/opencensus-experiments/blob/6ae8418a76405df8140c4bbb0b65ef54baa3a0ec/interoptest/src/goservice/main.go#L65)
[Java](https://github.com/census-ecosystem/opencensus-experiments/blob/6ae8418a76405df8140c4bbb0b65ef54baa3a0ec/interoptest/src/javaservice/src/main/java/io/opencensus/interop/JavaService.java#L34)

**Comment by ahmetb** [comment]
@rghetia if OC Agent is ready I suppose we should move to it directly. We can have prod/local versions of it that export to Stackdriver/Jaeger, respectively.

I don't see anything about it at https://opencensus.io/, just want to confirm it's ready for prime time. :)

**Comment by ahmetb** [comment]
@rghetia I also found out about https://github.com/Omnition/opencensus-service-demo.

Looks like there's interest in integrating more OC pieces around Hipster Shop. Can we bring some of these back instead of integrating Jaeger everywhere?

**Comment by rghetia** [comment]
@ahmetb you mean add the OcAgent to all the hipster shop services instead of Jaeger?

**Comment by bogdandrutu** [comment]
+100 to use the OcAgent exporter.

**Comment by ahmetb** [comment]
> @ahmetb you mean add the OcAgent to all the hipster shop services instead of Jaeger?

Yes, but I'm not sure if agent is something we add to each service (is it?). Isn't it something like a DaemonSet (on each node) or a centralized daemon (one per cluster)?

**Comment by rghetia** [comment]
one per node OR one per cluster is sufficient. however each service need to enable oc-agent exporter.

**Comment by ahmetb** [comment]
> one per node OR one per cluster is sufficient

Have we productized the OcAgent? Where can I find some versioned yaml files or helm packages for it?

> however each service need to enable oc-agent exporter.

I see. I think this would be more beneficial than adding Jaeger exporter everywhere, plus showcases how to use oc-agent exporter.

**Comment by bogdandrutu** [comment]
@ahmetb also it will allow this example to be run with any backend that we support with minimal changes in the oc-agent config. We are working to create a yaml/helm.

**Comment by ahmetb** [comment]
@bogdandrutu SGTM. We'd likely end up vendoring the resulting .yaml (given image will work for O(N) years). 

Is it possible to fan-out to multiple exporters (like jaeger and SD at the same time) from the oc-agent config? If so, and it does that without crashing, I'd love to get it working with no config both local and on GCP.

**Comment by bogdandrutu** [comment]
@ahmetb yes it is possible to do multiple exporters at the same time via config.

**Comment by ahmetb** [comment]
We can close this since we probably won't support Jaeger exporter, but I hope we can get someone to port OpenCensus to OpenTelemetry at some point.

**Comment by djmailhot** [comment]
As noted above, a configurable Open Census Agent is preferred over using a Jaeger exporter.  Closing this issue as Obsolete.
