### ISSUE TITLE
[WIP] add Jaeger OpenCensus exporters

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#112]
This issue tracks which microservices recognize JAEGER_ENABLED environment variable to register jaeger exporter for OpenCensus.

- [x] adservice (#111 is reference implementation)
- [ ] cartservice
- [x] checkoutservice
- [x] currencyservice
- [ ] emailservice
- [x] frontend
- [ ] paymentservice
- [x] productcatalogservice
- [ ] recommendationservice
- [x] shippingservice

**Comment by askmeegs** [comment]
discussion: https://github.com/GoogleCloudPlatform/microservices-demo/issues/109

**Comment by djmailhot** [comment]
As noted in #109, a configurable Open Census Agent is preferred over using a Jaeger exporter.  Closing this issue as Obsolete.
