### ISSUE TITLE
emailservice fails if stackdriver trace API is not enabled

### ISSUE THREAD

**Issue by bleything** [GoogleCloudPlatform/microservices-demo#119]
I recently tried to get this running on GKE and ran into an issue where emailservice wouldn't start. The logs indicated that the stackdriver trace API needed to be enabled:

```
$ kubectl logs emailservice-...
{"timestamp": 1546455589.3441265, "severity": "INFO", "name": "emailservice-server", "message": "starting the email service in dummy mode."}
{"timestamp": 1546455589.3529084, "severity": "INFO", "name": "emailservice-server", "message": "listening on port: 8080"}
Exception calling application: 403 Stackdriver Trace API has not been used in project [REDACTED] before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudtrace.googleapis.com/overview?project=[REDACTED] then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

I've since created other projects and found that API to be automatically enabled, so I'm not sure if I hit a transient issue or if this is actually an action that needs to be taken (and should therefore be documented).

**Comment by ahmetb** [comment]
Did this happen to overlap with the servicemanagement API outage you observed? 

The fact that new projects have this enabled as you saw (and nobody else hit this) makes me think it was a transient issue.

**Comment by bleything** [comment]
> Did this happen to overlap with the servicemanagement API outage you observed?

It's possible. The timeline is pretty fuzzy in my memory at this point but I'm reasonably sure that I created the project several days before that outage. 

> The fact that new projects have this enabled as you saw (and nobody else hit this) makes me think it was a transient issue.

It's starting to feel that way to me, too.

**Comment by ahmetb** [comment]
I'll close as not reproducible, will reopen if it happens again.
