### ISSUE TITLE
Broken Link in Workload Identity

### ISSUE THREAD

**Issue by LukeSchlangen** [GoogleCloudPlatform/microservices-demo#1195]
### Describe the bug 

Workload Identity link leads to `404`

### To Reproduce 

1. https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/docs/development-guide.md#option-1-google-kubernetes-engine-gke

2. Click link that says [see these instructions](https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/docs/workload-identity.md)

3. You will be redirected to a `404` page. It seems this file has been removed from the [docs folder](https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/docs)

### Exposure 

Persistent

**Comment by mathieu-benoit** [comment]
Good catch @LukeSchlangen, thanks for reporting the issue. We indeed simplify that part in this repo by just targeting the official WI setup page.

Note: To anyone who would like to fix that, the link should land there: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#enable,
