### ISSUE TITLE
Support product retrieval/definition via database, in `productcatalogservice`

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/microservices-demo#1260]
### Describe request or inquiry 
* This was requested by @LukeSchlangen and @moficodes. (Mofi, Luke, please provide any more details that I might have missed.)
* Currently, the Online Boutique's products are defined inside a [`products.json`](https://github.com/GoogleCloudPlatform/microservices-demo/blob/7741562421ad61ad1d30cebf39e21587a8377952/src/productcatalogservice/products.json) file inside the `productcatalogservice`. 
* But we want to also support the ability to load this list of products from a database (e.g., in-cluster SQL database, or a database on a cloud service).
* That database would be populated by another app — not Online Boutique — which Luke and Mofi would maintain in a different repository.
* Work necessary from Online Boutique
   * add code inside `productcatalogservice` to read from a database (specified via environment variables) instead of the `products.json` file.
   * add a Kustomize Component and documentation for enabling/configuring this new feature

### What purpose/environment will this feature serve? 
* Luke and Mofi want to demo multiple scenarios, but this specific features requests (detailed in this GitHub issue) will help us demo:
  * two microservice-based apps sharing data.

**Comment by NimJay** [comment]
@LukeSchlangen and @moficodes,
First off, thank you so much for the heads-up on this project!
I think it would be really cool to showcase data being shared between multiple microservice-based apps.

Since this is a fairly complex project, I ask that you create a **short** Google Doc detailing the context, changes to be made to Online Boutique, and any support that you would need from our team. My team and I can leave our thoughts and help you flesh out the design decisions in that Google Doc. It doesn't have to be super thorough. I just want to make sure I communicate this to my team and get their input. 😊

**Comment by LukeSchlangen** [comment]
Definitely! Do you have the original diagram for this image available in an editable format somewhere?
https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/docs/img/architecture-diagram.png

I think we can communicate our idea most clearly by adding three boxes to this diagram.

**Comment by LukeSchlangen** [comment]
The Back Office Application would be a standalone application that would be an optional integration (like the redis database). Here is the general idea for integrating:

![Back Office Application to Microservices Demo](https://user-images.githubusercontent.com/5384581/201157373-f9a1e7ee-5e73-4afd-ad82-49a8d22c6922.png)

**Comment by NimJay** [comment]
> Do you have the original diagram for this image available ... ?

Yes! :)
See [Google Slides here](https://docs.google.com/presentation/d/12803GBApC8unpd8cmp4BOkk9dTPV4OOtihhIJHa8m28/edit#slide=id.p).

**Comment by bourgeoisor** [comment]
@NimJay this is still active? (fell out of SLO, just commenting)

**Comment by LukeSchlangen** [comment]
I think it's something we still _aspire_ to do, but I think it's safe to close it for now since it would probably be late 2023/early 2024 before we had the time to invest in implementation.

**Comment by minherz** [comment]
@NimJay I am assigning it to you for another round of review. If there is no demand for this, consider to close it. We can always reopen this issue later or create a new one that address specific demands.

**Comment by bourgeoisor** [comment]
As of https://github.com/GoogleCloudPlatform/microservices-demo/pull/2466, the products catalog supports AlloyDB, enabled through the AlloyDB Kustomize component.
