### ISSUE TITLE
Support easy use of non-default VPC in Terraform

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/microservices-demo#1265]
### Describe request or inquiry 
* Our Terraform needs to be easy to use for anyone who doesn't want to use the `default` GCP [VPC (Virtual Private Cloud)](https://cloud.google.com/vpc/docs/vpc).

### Option 1
* We could use the Terraform [`google_container_clusters`'s `network` argument](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster) to configure the VPC being used by the GKE cluster.
* We would have to do something similar for every GCP resource created by Terraform (e.g., Memorystore instance).
* We could introduce a variable inside `variables.tf` that lets users easily set the VPC being used.

### Option 2
* We could even create a completely new VPC via Terraform — instead of assuming the user already has a ready-to-use VPC.

### What purpose/environment will this feature serve? 
* This feature request was initially requested in https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/issues/989.
* This is useful for users from organizations with highly restrictive GCP policies.

**Comment by minherz** [comment]
It looks like the original "trigger" for this came from [CloudOps Sandbox][1]. @NimJay is it required by any other project? If not, we might consider rejecting it for now given that Sandbox plans include sundown of the provisioning demo applications, leaving this task at user's discretion.

[1]: https://github.com/GoogleCloudPlatform/cloud-ops-sandbox

**Comment by bourgeoisor** [comment]
@NimJay should we close this?

**Comment by bourgeoisor** [comment]
Closing due to lack of interest. Feel free to reopen!
