### ISSUE TITLE
skaffold version skew causing issues

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/microservices-demo#127]
Installed skaffold with chocolateley:
```
choco install skaffold --force
```

When running:
```
skaffold run --default-repo=gcr.io/opencensus-demos
```
I get:
```
FATA[0002] creating runner: parsing skaffold config: unknown api version: 'skaffold/v1beta2'
```

**Comment by ahmetb** [comment]
sounds like you probably have an old version of skaffold. what version are you on?

**Comment by simonz130** [comment]
v0.19.0

**Comment by simonz130** [comment]
In my fork, when I do
```
skaffold run
```
with the same version, it starts to build, but then I get:
```
FATA[1812] build failed: building [emailservice]: tagging: pushing: denied: requested access to the resource is denied
```

**Comment by ahmetb** [comment]
Try v0.20. I think that's when this apiVersion got out.

Since we're not telling people to install old versions of skaffold, people keep opening issues saying there's errors/warnings due to old versions of skaffold.

**Comment by simonz130** [comment]
Yeah, this helped. Thanks!
We need to update the instructions to require v0.2 or higher and also mention how to update to that version.

**Comment by ahmetb** [comment]
I'm a little bit hesitant about documenting it. There are already 3 places that refer to the skaffold version (cloudbuild.yaml, .travis.yml, skaffold.yaml) and documenting it would add a 4th place.

Given skaffold recently became backwards-compatible, and probably most of demo users don't have a previous old skaffold setup mostly (except us, devs), I suspect this will work just fine for the majority of users.

**Comment by simonz130** [comment]
This needs to be documented. "Working for majority" is not a good measure.
Adding a small note of "ensure latest version of skaffold" will make it
better for cases when you work with demo, then don't do anything for a
while, then get back to it.
