### ISSUE TITLE
Investigate Sigstore support

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/microservices-demo#1299]
* [Sigstore](https://www.sigstore.dev/how-it-works) is a standard that defines a set of technologies/tools that developers can use to "sign" the artifacts they build.
* Online Boutique could use Sigstore to sign the container images published to the public (e.g., `gcr.io/google-samples/emailservice:v0.5.0`).
* Users of Online Boutique can then verify that the container images that they `pull` have not been tampered with.
* Thank you, @mathieu-benoit, for this suggestion.
* This GitHub issue tracks the following:
  * [ ] Understand how Sigstore works. Research alternatives.
  * [ ] Answer: Should Online Boutique use Sigstore?
  * [ ] Answer: If yes, create a GitHub issue to describe and track the implementation.

**Comment by NimJay** [comment]
An example of Sigstore's `cosign` tool being used by Google: https://github.com/GoogleContainerTools/distroless#how-do-i-verify-distroless-images.

**Comment by minherz** [comment]
Work is postponed due to limited capacity.

**Comment by bourgeoisor** [comment]
Unlikely to get to this, but we should still do https://github.com/GoogleCloudPlatform/microservices-demo/issues/1339 which may brings its own host of security improvements. Closing, feel free to reopen if you disagree.
