### ISSUE TITLE
Migrate to Artifact Registry from Container Registry

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/microservices-demo#1339]
* Today, Online Boutique uses Google Cloud's [Container Registry](https://cloud.google.com/container-registry/docs) for the container images that it published.
* For instance, `gcr.io/google-samples/emailservice:v0.5.0` is hosted on Container Registry.
* However, Artifact Registry is the recommended way to host container images on Google Cloud — not Container Registry.
* Relevant documentation: [Transition from Container Registry](https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr).
* We should migrate to Artifact Registry.

**Comment by NimJay** [comment]
Update (to cool down our teams' OoSLO list): This work [was planned for Q4](https://docs.google.com/document/d/1fxEldm4oqRcOIyVUhImsjWAn36jY2lalTKeN-dIOEz4/edit), but it could be delayed since our team's priorities have changed significantly.

**Comment by minherz** [comment]
Priority is decreased because the required migration is not urgent.

**Comment by muncus** [comment]
This continues to be low-priority work.

**Comment by NimJay** [comment]
Addressed via [b/355704951#comment3](http://b/355704951#comment3). All gcr.io images are using AR (Artifact Registry) under the hood.
