### ISSUE TITLE
./gradlew: not found local cluster deployment

### ISSUE THREAD

**Issue by anasj25** [GoogleCloudPlatform/microservices-demo#1347]
Step 4/18 : COPY gradle gradle
 ---> ca2a614ce472
Step 5/18 : RUN chmod +x gradlew
 ---> Running in 4cfbc82c2da9
Removing intermediate container 4cfbc82c2da9
 ---> 4ab32a37dc28
Step 6/18 : RUN ./gradlew downloadRepos
 ---> Running in 374228cb6f66
/bin/sh: 1: ./gradlew: not found
The command '/bin/sh -c ./gradlew downloadRepos' returned a non-zero code: 127

**Comment by mathieu-benoit** [comment]
Thanks @anasj25 for reporting this issue!

Just to confirm, could you clarify which command you are running please?

I just tested `cd src/adservice && docker build -t adservice .` and it's working successfully without the error/issue you are facing:
```
Step 4/18 : COPY gradle gradle
 ---> 6a53b84138b6
Step 5/18 : RUN chmod +x gradlew
 ---> Running in 7c0aa69d8b5c
Removing intermediate container 7c0aa69d8b5c
 ---> 5514d4121c79
Step 6/18 : RUN ./gradlew downloadRepos
 ---> Running in 78bbabedbb48
Downloading https://services.gradle.org/distributions/gradle-7.6-bin.zip
...........10%............20%...........30%............40%............50%...........60%............70%............80%...........90%............100%

Welcome to Gradle 7.6!
```

Also, could you confirm that you have the latest version of Online Boutique?

Thanks for providing more context and information to help us diagnosing this issue.

**Comment by anasj25** [comment]
Hi Mathieu,
I am on windows and I ran the skaffold run command. And yes I cloned the latest Online Boutique repo on my PC.

**Comment by NimJay** [comment]
Hey @anasj25,
* Sorry for the extremely late response!
* Thanks for providing additional info. :)
* The error message is similar to error message seen in [issue 1434](https://github.com/GoogleCloudPlatform/microservices-demo/issues/1434#issuecomment-1377451183).
```
/bin/sh: 1: ./gradlew: not found
```
* Could you retry (re-`git clone`) with the [following workaround](https://github.com/GoogleCloudPlatform/microservices-demo/issues/1434#issuecomment-1377451183)?
```
git clone https://github.com/GoogleCloudPlatform/microservices-demo.git --config core.autocrlf=true
```
* This issue seems related to the following discrepancy: 
    * Windows uses `CR + LF` as a new line character
    * Linux uses `LF` as a new line character

**Comment by minherz** [comment]
@anasj25 can you please confirm that the issue is still reproducible following @NimJay's [comment](https://github.com/GoogleCloudPlatform/microservices-demo/issues/1347#issuecomment-1513566064)?

**Comment by marcghanime** [comment]
Hello @minherz & @NimJay, 

i have the same problem on Windows 11 with Minkube

- Cloned the latest version with [the following workaround](https://github.com/GoogleCloudPlatform/microservices-demo/issues/1434#issuecomment-1377451183) 
- Error comes up with both `skaffold run` and `docker build`

Error with skaffold run:
```
Building [adservice]...
Target platforms: [linux/amd64]
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            BuildKit is currently disabled; enable it by removing the DOCKER_BUILDKIT=0
            environment-variable.

Sending build context to Docker daemon  117.2kB
Step 1/19 : FROM eclipse-temurin:19@sha256:f3fbf1ad599d4b5dbdd7ceb55708d10cb9fafb08e094ef91e92aa63b520a232e as builder
 ---> f546b418bb3a
Step 2/19 : WORKDIR /app
 ---> Using cache
 ---> de3fef9c1bce
Step 3/19 : COPY ["build.gradle", "gradlew", "./"]
 ---> Using cache
 ---> 29e208f43c2a
Step 4/19 : COPY gradle gradle
 ---> Using cache
 ---> d8420a3827c0
Step 5/19 : RUN chmod +x gradlew
 ---> Using cache
 ---> 5cc3fdf9796c
Step 6/19 : RUN ./gradlew downloadRepos
 ---> Running in 05a20dc9e5d6
/bin/sh: 1: ./gradlew: not found
The command '/bin/sh -c ./gradlew downloadRepos' returned a non-zero code: 127
build [adservice] failed: exit status 127. Docker build ran into internal error. Please retry.
If this keeps happening, please open an issue..
```

Error with docker build:

```=> [without-grpc-health-probe-bin 2/5] RUN apk add --no-cache ca-certificates                                                                                                              2.3s
 => [without-grpc-health-probe-bin 3/5] RUN mkdir -p /opt/cprof &&     wget -q -O- https://storage.googleapis.com/cloud-profiler/java/latest/profiler_java_agent_alpine.tar.gz     | tar x  2.1s
 => [without-grpc-health-probe-bin 4/5] WORKDIR /app                                                                                                                                        0.0s 
 => [builder 2/9] WORKDIR /app                                                                                                                                                              0.3s 
 => [builder 3/9] COPY [build.gradle, gradlew, ./]                                                                                                                                          0.0s 
 => [builder 4/9] COPY gradle gradle                                                                                                                                                        0.0s 
 => [builder 5/9] RUN chmod +x gradlew                                                                                                                                                      0.3s 
 => ERROR [builder 6/9] RUN ./gradlew downloadRepos                                                                                                                                         0.6s 
------
 > [builder 6/9] RUN ./gradlew downloadRepos:
#0 0.543 /bin/sh: 1: ./gradlew: not found
------
Dockerfile:22
--------------------
  20 |     COPY gradle gradle
  21 |     RUN chmod +x gradlew
  22 | >>> RUN ./gradlew downloadRepos
  23 |
  24 |     COPY . .
--------------------
ERROR: failed to solve: process "/bin/sh -c ./gradlew downloadRepos" did not complete successfully: exit code: 127
```

**Comment by marcghanime** [comment]
Hello again, 

I was able to fix it by going into VS Code and manually setting the end of line sequence as LF instead of CRLF for the following files: 

`src\adservice\Dockerfile` 
`src\adservice\gradlew`
`src\adservice\gradlew.bat`

I'm not sure if all 3 are required to fix the bug but I tried these 3 together at first and it worked.
Cloning the latest version with [this workaround](https://github.com/GoogleCloudPlatform/microservices-demo/issues/1434#issuecomment-1377451183) did not work for me for some reason.

You can change the end of line sequence in VS Code by opening the Command Palette (Ctrl+Shift+P) and selecting _Change End of Line Sequence_ and setting it to LF.

**Comment by minherz** [comment]
@NimJay , can you please have a look.

**Comment by NimJay** [comment]
@marcghanime thank you for not only reporting your issue, but also finding and sharing a fix! 👏 

I have created [pull-request 1806](https://github.com/GoogleCloudPlatform/microservices-demo/pull/1806) to fix the issue (i.e., convert existing `CRLF` files in this repo to `LF`).

If possible, could you please:
```
git checkout nimjay-lf
cd src/adservice
docker build --no-cache . -t my-adservice-test
```
and let me know if you are able to successfully build the `adservice` using the `nimjay-lf` branch, **on Windows**.
Command to delete `my-adservice-test`:
```
docker image rm my-adservice-test
```

**Comment by marcghanime** [comment]
Hey @NimJay, 

I have tried to build the service with your changes but it still fails. I also found out that only the `src\adservice\gradlew` file needs to be changed to LF, keeping the `src\adservice\Dockerfile` and `src\adservice\gradlew.bat` files as they come **also leads to successful builds**. I also noticed that in the pull request the files changed do not include the `src\adservice\gradlew` file which (at least on my machine) is the only file that needs to be changed to LF.

It also might be that git on windows **automatically** changes all the files to CRLF [as explained here](https://docs.github.com/articles/dealing-with-line-endings#:~:text=text%20eol%3Dcrlf%20Git%20will,LF%20endings%2C%20even%20on%20Windows.).

**Comment by NimJay** [comment]
Thanks once again, @marcghanime! That info helps.

* I've updated the [the fix in pull-request 1806](https://github.com/GoogleCloudPlatform/microservices-demo/pull/1806/files).
    * I changed the `.gitattributes` line from `* text=auto` to `* text=auto eol=lf`.
    * This will force Windows to use `LF` locally when you `git clone` (according to [this article](https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/#:~:text=if%20you%20only%20use%20*%20text%3Dauto%2C%20you%20may%20still%20see%20some%20CRLF%20line%20endings%20locally%20in%20your%20working%20tree%3B%20this%20is%20okay%20and%20is%20working%20as%20expected.%20If%20you%20don%E2%80%99t%20want%20this%2C%20you%20can%20enforce%20*%20text%3Dauto%20eol%3Dlf%20instead.) and my personal testing on Windows).
* I have tested [pull-request 1806](https://github.com/GoogleCloudPlatform/microservices-demo/pull/1806/files) on a Windows machine using:
```
git clone --single-branch --branch nimjay-lf https://github.com/GoogleCloudPlatform/microservices-demo.git
cd .\microservices-demo\
git ls-files --eol | findstr gradle
```
* In the output, I saw that my local files were using `LF`:
```
i/lf    w/lf    attr/text=auto eol=lf   src/adservice/build.gradle
i/-text w/-text attr/text=auto eol=lf   src/adservice/gradle/wrapper/gradle-wrapper.jar
i/lf    w/lf    attr/text=auto eol=lf   src/adservice/gradle/wrapper/gradle-wrapper.properties
i/lf    w/lf    attr/text=auto eol=lf   src/adservice/gradlew
i/lf    w/lf    attr/text=auto eol=lf   src/adservice/gradlew.bat
i/lf    w/lf    attr/text=auto eol=lf   src/adservice/settings.gradle
```
* I have also tested `skaffold run --module=app` on [a local kind cluster](https://github.com/GoogleCloudPlatform/microservices-demo/issues/1804#issuecomment-1563404858) (on a Window machine). Online Boutique worked.
* Unfortunately, the fix from [pull-request 1806](https://github.com/GoogleCloudPlatform/microservices-demo/pull/1806/files) does not work for existing/old clones of this repo. To apply the fix, you may need to additionally run (according to [this article](https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/#:~:text=To%20update%20existing%20line%20endings%20in%20your%20working%20tree)):
```
git rm --cached -r .
git reset --hard
```
