### ISSUE TITLE
Deploy opencensus kubernets-operator for resource identification

### ISSUE THREAD

**Issue by bogdandrutu** [GoogleCloudPlatform/microservices-demo#136]
Part of the deployment as the first service deployed we should add the opencensus kubernets-operator (see https://github.com/census-ecosystem/kubernetes-operator) (look for some of the PRs for more instructions on how to build/deploy).

This is important to ensure the right resources are associated with the exported metrics/traces (one of the critical label is the container_name which is not available in the opencensus library).

**Comment by DanSanche** [comment]
Closing this and other `kind/improvement` issues as we attempt to move the project into a stable maintenance state
