### ISSUE TITLE
Proposal: Use backend database to catalog / order services

### ISSUE THREAD

**Issue by Haybu** [GoogleCloudPlatform/microservices-demo#140]
To illustrate having additional persistence in the stack, would be great to add a persistence database layer for some services. Will help to use this demo for other educational and research purposes.

**Comment by ahmetb** [comment]
Right now illustrating persistence is not within the scope of the project.

Avoiding stateful components saves us a lot of pain during deployment, runtime and configuration.

If you have a demo you'd like to show with statefulness, you can start by making Redis persistent/replicated.

**Comment by pie6k** [comment]
> Avoiding stateful components saves us a lot of pain during deployment, runtime and configuration.

... but is the case for almost any product, which means a lot of pain during deployment, runtime and configuration. Which seems like good reason to include it inside such a great example project

**Comment by ahmetb** [comment]
There are countless Kubernetes features, and we can only highlight so many without overcomplicating the source code, as well as Kubernetes manifests and deployment procedure.
