### ISSUE TITLE
Auto-merge Renovate pull-requests for patch/minor/digest

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/microservices-demo#1428]
#### Terminology
* From [semver.org](https://semver.org/) (`major.minor.patch`):
    * `major` = incompatible API changes
    * `minor` = new functionality & **backwards compatible**
    * `patch` = bug fixes & **backwards compatible**
* `digest` = similar to [pull-request #1426](https://github.com/GoogleCloudPlatform/microservices-demo/pull/1426/files) 

#### Background
* [Most](https://github.com/GoogleCloudPlatform/microservices-demo/graphs/contributors) of the pull-requests merged into `main` come from Renovate Bot (dependency updates).
* Most of these updates are **not** `major` updates.
* The review process for a non-`major` updates is: if the CI checks are passing, merge the pull-request.

#### Feature Request
* Renovate Bot updates should be auto-merged if the following conditions are met:
    1. the update is one of: `patch`; `minor`; `digest`
    1. the relevant CI tests are passing
* For now, `major` updates should go through a manual review.
    * We have experienced breakages of Online Boutique functionality because of `major` Renovate Bot updates (e.g., when [`pino` was updated](https://github.com/GoogleCloudPlatform/microservices-demo/issues/1274#issuecomment-1334531055)).
    * We could auto-merge `major` updates too once we have thorough end-to-end tests of most of Online Boutique (e.g., U.I. tests).

#### Additional Notes
* This will free up a lot of the time that our team spends on reviewing Online Boutique pull-requests.

**Comment by gitsan13** [comment]
Hi @NimJay 
I would like to give this issue a try. Can you please assign me to it?

**Comment by NimJay** [comment]
Hi @gitsan13,

First, thank you for your interest in contributing.
This issue (about auto-merging Renovate pull-requests) is more appropriate for someone with admin access to this GitHub repository.

If you'd like to work on something, I recommend: https://github.com/GoogleCloudPlatform/microservices-demo/issues/693
But https://github.com/GoogleCloudPlatform/microservices-demo/issues/693 is a big task because it involves [multiple microservices](https://github.com/search?q=filename%3ADockerfile+repo%3AGoogleCloudPlatform%2Fmicroservices-demo&type=code). 
So you could try https://github.com/GoogleCloudPlatform/microservices-demo/issues/693 _for a specific microservice_ (e.g., for the [`loadgenerator`](https://github.com/GoogleCloudPlatform/microservices-demo/blob/a59d8b5e86f509d254fa245c60dfd07ee28b2fb8/src/loadgenerator/Dockerfile) — is `python:3.11.1-slim` the smallest base image we can use, or it there something smaller)?

**Comment by minherz** [comment]
@bourgeoisor for your tracking

**Comment by bourgeoisor** [comment]
Done here: https://github.com/GoogleCloudPlatform/microservices-demo/pull/1835
