### ISSUE TITLE
Can't build with GCB in CloudShell - "no such file or directory"

### ISSUE THREAD

**Issue by christianhxc** [GoogleCloudPlatform/microservices-demo#143]
I'm trying to run this app in GCP CloudShell and after facing the "no space" error, I cleaned the disk and start over. Now, when I run the command to build on GCB `skaffold run -p gcb --default-repo=gcr.io/[PROJECT_ID]` I'm getting the following error:

```
Starting build...
Building [gcr.io/[PROJECT_ID]/emailservice]...
Pushing code to gs://[PROJECT_ID]_cloudbuild/source/[PROJECT_ID]-b85aab371fd9bd087c76d32acd797268.tar.gz
FATA[0002] build failed: building [gcr.io/[PROJECT_ID]/emailservice]: uploading source tarball: uploading targz to google storage: creating tar gz: lstat /home/christianhx
c/microservices-demo/src/emailservice/src/emailservice/Dockerfile: no such file or directory
```

I'm using the Skaffold v0.22.0, and I've also tried updating the skaffold.yaml version to `beta4` but same error.

Note: When running the command I'm including the proper project id.

**Comment by ahmetb** [comment]
Looks like gcb build machine is running out of disk. I will see if we can pass that parameter to GCB via skaffold.

**Comment by ahmetb** [comment]
In the meanwhile you can build it without “-p gcb” on Cloud Shell.

**Comment by christianhxc** [comment]
@ahmetb yep, that's why I cleaned the home directory and restarted CloudShell. Now that I have space, instead of running the build locally I'm using GCB but then I get that error. I don't understand why I'm getting this error `/home/christianhx
c/microservices-demo/src/emailservice/src/emailservice/Dockerfile: no such file or directory` ... It works locally, but not when using GCB.

**Comment by ahmetb** [comment]
hmm `src/emailservice/src/emailservice/Dockerfile` looks odd. the second `/src/emailservice` should not be there.

**Comment by christianhxc** [comment]
@ahmetb exactly, I don't know why it's not working when building it on GCB =/

**Comment by jpatokal** [comment]
I ran into this as well today.  The weird thing is that precisely the same command (with `-p gcb`) works just fine when running in a VM instead of Cloud Shell.

**Comment by ahmetb** [comment]
Thanks for the report, will take a look.

**Comment by dgageot** [comment]
Hi, this should be fixed in Skaffold v0.23.0

**Comment by mike-holberger** [comment]
Will not build in Google Shell in GKE either - no space left on device. Following directions for: "(Optional) Deploying on a Istio-installed GKE cluster"

**Comment by ahmetb** [comment]
Closing as this was a skaffold issue.

If you run into "no space left on device" error, please open a separate issue (so I can follow up with the Cloud Shell product team).
