### ISSUE TITLE
OTel Collector lacks permissions on GKE

### ISSUE THREAD

**Issue by arbrown** [GoogleCloudPlatform/microservices-demo#1444]
### Describe the bug 
The OpenTelemetry Colector fails to export spans to cloud trace on GKE Autopilot clusters.  It fails with the error:

```
failed to export to Google Cloud Trace: rpc error: code = PermissionDenied desc = The caller does not have permission"
```

This worked previously, and seems to be related to a change in Workload Identity permissions on GKE autopilot.  Note that trace exports work as intended on GKE standard.

### To Reproduce 
Deploy Online Boutique with the googlecloudoperations kustomize module on a GKE autopilot cluster.  Note the lack of spans in Cloud Trace, and observe the error messages in the logs for the collector.

**Comment by NimJay** [comment]
(We talked about this offline, but I'll mention it here for visibility.)

You mentioned:
> "Note that trace exports work as intended on GKE standard."

I was able to reproduce this permission issue with a **standard** GKE cluster — not autopilot.

### Reproduction Details

GKE version: 1.24.7-gke.900	
Num of nodes: 2
Branch/commit used: `main`
Error message in `opentelemetrycollector`:
```
2023/01/09 21:09:51 failed to export to Google Cloud Trace: rpc error: code = PermissionDenied desc = The caller does not have permission
```

**Comment by NimJay** [comment]
I should clarify: the standard GKE cluster I mentioned in my previous comment has Workload Identity enabled.

<img width="390" alt="Screenshot 2023-01-11 at 9 48 20 AM" src="https://user-images.githubusercontent.com/10292865/211836592-f52642a1-8559-4c6e-b8d2-5378d99fbae9.png">

**Comment by christopherhendrich** [comment]
I am seeing the same error with standard clusters that have WI enabled. 
otel-collector uses the default KSA of the namespace, correct?
I tried to run the below without any success. The GSA has the permissions to cloud trace as described as in the readme. 
```
gcloud iam service-accounts add-iam-policy-binding ${GSA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com \
    --member "serviceAccount:${PROJECT_ID}.svc.id.goog[${ONLINEBOUTIQUE_NAMESPACE}/default]" \
    --role roles/iam.workloadIdentityUser
    ```

**Comment by arbrown** [comment]
Hi Christopher,

I think you're on the right track.  As long as all the variables in your command are properly set, the only other thing to do is update the Kubernetes service account with a similar command:
```
kubectl annotate serviceaccount default iam.gke.io/gcp-service-account=${GSA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com
```
And then restart the collector deployment.  Check out the [pending documentation update](https://github.com/GoogleCloudPlatform/microservices-demo/tree/wi-docs/kustomize/components/google-cloud-operations#workload-identity) for more info.

**Comment by bourgeoisor** [comment]
@arbrown as this is set as P1, do you have an update on this issue? Is the priority still set correctly?
