### ISSUE TITLE
Instructions about using static image does not work

### ISSUE THREAD

**Issue by incfly** [GoogleCloudPlatform/microservices-demo#150]
On the `README.md` it mentions about using static image.

> Option 3: Using Static Images
> 💡 Recommended for test-driving the application on an existing cluster.
> 
> Prerequisite: a running Kubernetes cluster.
> 
> Clone this repository.
> 
> Deploy the application: kubectl apply -f ./release/kubernetes-manifests
> 
> Run kubectl get pods to see pods are in a healthy and ready state.
> 
> Find the IP address of your application, then visit the application on your browser to confirm installation.
> 
> kubectl get service frontend-external

However, this will not work.

1. `./realease/kubernetes-manifests` should be `kubernetes-manifests`
1. The image in the yaml files are as "cartservice" without referencing the full docker registry url. Digging commit history a bit, it seems to adapt to skaffold. However the instructions does not work for static image then.

As a first-comer, I do think being able to use a public image to deploy in my cluster is very helpful.

**Comment by ahmetb** [comment]
We havent provided a release yet. Once we do, the directory will exist. Sorry!

**Comment by bureado** [comment]
For the record, if you want to deploy HipsterShop in your existing Kubernetes cluster, here's what worked for me:

1. Access to a container registry
2. Ability to push to said registry (e.g., `docker login`)
3. Ability for your Kubernetes cluster to [use the credentials](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/) (i.e., `kubectl create secret docker-registry ...` and then `imagePullSecrets` on the `kubernetes-manifests/` YAML files)
4. `skaffold run` with `--default-repo=<registry>`
5. Change the `containers.image` property to `<registry>/<image>:<tag>` with `<tag>` as pushed to your registry (defaults to git's `HEAD`, you can [change it](https://skaffold.dev/docs/how-tos/taggers/) in the `skaffold.yaml` though)
6. If you change the YAML after `skaffold run`, don't forget to `kubectl apply` again

I was able to deploy to Azure Kubernetes Service using Azure Container Registry from a Debian box this way. I'm sure there's a way to automate some of this with `skaffold` or in the YAML themselves, but documenting it here in case someone else is trying to get HipsterShop running elsewhere.

**Comment by ahmetb** [comment]
Thanks! I'll close this until we provide releases (manifests referencing public prebuilt images). I removed those instructions from the README, sorry for the confusion.

**Comment by incfly** [comment]
Yup, let's hide the `./releases` until it's ready. Thanks for the fix!

**Comment by ahmetb** [comment]
FYI the instructions are added back as part of v0.1.0 release.

**Comment by incfly** [comment]
Awesome, thanks for the quick fix!
