### ISSUE TITLE
cartservice: use structured json logging and add times

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#154]
cartservice is currently not using JSON structured logging with fields recognized by stackdriver. It would be good to use that + add timestamps so that when a problem arises (like health probes failing), it would be good to see the logs around that time.

**Comment by askmeegs** [comment]
see https://github.com/GoogleCloudPlatform/microservices-demo/issues/47

**Comment by djmailhot** [comment]
I'm prioritizing other work, so I'm de-assigning myself from this issue.

**Comment by DanSanche** [comment]
Closing this and other `kind/improvement` issues as we attempt to move the project into a stable maintenance state
