### ISSUE TITLE
Replace `patchesStrategicMerge`/`patchesJson6902` with `patches`

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/microservices-demo#1564]
### Describe request or inquiry 
* [Kustomize 5.0.0](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.0.0) was released Feb 2023. The release notes mention:
> We are deprecating the following kustomization fields. These fields will never be removed from the kustomize.config.k8s.io/v1beta1 Kustomization API, but they will not be included in the kustomize.config.k8s.io/v1 Kustomization API. When Kustomization v1 is available, we will announce the deprecation of the v1beta1 version. There will be at least two releases between deprecation and removal of Kustomization v1beta1 support from the kustomize CLI, and removal itself will happen in a future major version bump.
> * patchesStrategicMerge. Please use [patches](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/) instead
> * patchesJson6902. Please use [patches](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/) instead
> * vars. Please use [replacements](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/) instead.
> * imageTags. This is an alias for [images](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/images/), please switch to images.
* Today, Online Boutique uses `patchesStrategicMerge` and `patchesJson6902`. We should replace the use of these fields with [`patches`](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/).

### What purpose/environment will this feature serve? 
* This impacts a few of [our Kustomize components](https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/kustomize).

**Comment by NimJay** [comment]
I've assigned a priority of p3 (lowest) for now because:
> "There will be at least two releases [of Kustomize] between deprecation and removal of Kustomization v1beta1 support from the kustomize CLI, and removal itself will happen in a future major version bump."

Kustomize 4.0.0 was released in [Feb 2021](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.0.0).
Kustomize 5.0.0 was released in [Feb 2023](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.0.0).
I'm guessing Kustomize 6.0.0 and 7.0.0 will take 1 and 2 years, respectively. 🤷

**Comment by NimJay** [comment]
Update to cool down our out-of-SLO list: this issue is still a p3.

**Comment by bourgeoisor** [comment]
There are no more `patchesStrategicMerge` in the repo. Closing as obsolete.
