### ISSUE TITLE
Decouple product list management from `frontend`

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/microservices-demo#1590]
### Describe request or inquiry 
* Today, modifying Online Boutique's list of products requires an update to the `frontend`.
* See [previous change to list of products here](https://github.com/GoogleCloudPlatform/microservices-demo/pull/600/files#diff-95341b0273b00662e5a4829c80fe6e991265426d5c2f2bc6e7377d84e38ef7d3).
* This is because the `frontend` hosts the images for all products (see [`/src/frontend/static/img/products` folder](https://github.com/GoogleCloudPlatform/microservices-demo/tree/release/v0.5.2/src/frontend/static/img/products)).
* Ideally, we would not have to update the `frontend`.
* That is, product list management should be decoupled from `frontend` — in true microservice spirit.
* Potential solutions:
    1. have the `productcatalogservice` publicly host product images,
    2. introduce a new microservices for publicly hosting product images,
    3. have the `productcatalogservice` upload images to a public-hosting service like [Google Cloud Storage](https://cloud.google.com/storage) (GCS). This approach would be similar to [Avocano](https://github.com/GoogleCloudPlatform/avocano) (another GCP demo application). Avocano uploads product images to GCS buckets and makes the backend share the URLs of those images with the frontend as needed.

### What purpose/environment will this feature serve? 
* This is part of a recent effort to make Online Boutique relate more to the ecommerce and retail industry.
* An important takeaway (for users from the ecommerce/retail industry) inside should be: how to decouple product and inventory management from the rest of the app.
* See [Google-internal doc here](https://docs.google.com/document/d/1z3vBmlQfUEAaCBO2LpFgMGEggNqboSp83eLiKufD7g4/edit#heading=h.t0dnfs6z18a8) for more info.

**Comment by minherz** [comment]
Any updates?

**Comment by Irene-123** [comment]
Hi @NimJay 
I went through the issue and looking to contribute here, though need some time for more clarification and understanding
Wanted to know if I can take up this as my first issue here or if you have any suggestions lmk :)
Thanks!

**Comment by NimJay** [comment]
Hi @Irene-123 (Kirti), thank you for your interest in contributing! :)

I'm realizing that all 3 of the solutions that I proposed in the description would break one of the [product requirements (of the default Online Boutique deployment) listed here](https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/docs/product-requirements.md):
- either by introducing a dependency on a Google Cloud product (breaking the requirement that this app should run on local clusters like kind)
- or by introducing a new external IP address (breaking the requirement that all changes should preserve the simplicity of demos)

Hence, I will close this issue.

CC: @bourgeoisor (tech lead of this repo, who can override my decision here) :)
