### ISSUE TITLE
istio-manifests.yaml fails validation on Istio 1.1

### ISSUE THREAD

**Issue by davidebbo** [GoogleCloudPlatform/microservices-demo#161]
Here is what I get:

```
$ kubectl apply -f ./release/istio-manifests.yaml 
gateway.networking.istio.io/frontend-gateway created
virtualservice.networking.istio.io/frontend-ingress created
serviceentry.networking.istio.io/currency-provider-external created
virtualservice.networking.istio.io/frontend created
Error from server: error when creating "./release/istio-manifests.yaml": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: domain name "254.169.254" invalid (top level domain "254" cannot be all-numeric)
```

This was working when I was using 1.0.4. This is using Istio 1.1.0-rc.0 from dockerhub.

**Comment by davidebbo** [comment]
@ayj / @ozevren: could this be some Galley issue?

**Comment by davidebbo** [comment]
Seems it's complaining about having an IP address under the ServiceEntry's hosts: https://github.com/GoogleCloudPlatform/microservices-demo/blob/5f41e12b2f0631a6a0c462b326acf440156109ee/release/istio-manifests.yaml#L123

**Comment by ayj** [comment]
The configuration is invalid. `hosts` cannot be an IP address (see https://github.com/istio/istio/blob/f385a88421d6854f4eacada9f6f090c4563a224c/pilot/pkg/model/validation.go#L272).

You probably want to use the address field to specify the metadata server IP (see https://github.com/istio/api/blob/53b11a3dc9ff646d30dfd23785d0b99b11b221ef/networking/v1alpha3/service_entry.proto#L338-L352.

**Comment by ahmetb** [comment]
This sounds like a breaking change in the API.

What's the justification for rejecting an address that was previously accepted in the API in a minor release?

Now my suspicion is that we move out the IP into the `addresses` field, but then the installations with Istio 1.0.x won’t work with it correctly (if even accepts the `addresses` field)? Was this field there & used in Istio 1.0.x? If not, we’ll have to make Istio 1.1.x a requirement.

**Comment by ayj** [comment]
Looks like other networking APIs (VirtualService) have a special case in their validation logic to allow IP addresses. cc @costinm @andraxylia for clarification on the expected behavior here.

**Comment by davidebbo** [comment]
So @ayj, something like this?

```
spec:
  hosts:
  - "metadata.google" # GCE metadata server
  - "metadata.google.internal" # GCE metadata server
  - "accounts.google.com" # Used to get token
  - "*.googleapis.com"
  addresses:
  - "169.254.169.254" # GCE metadata server
```

I agree it feels like a breaking change, and should at the very least be documented in some 1.1. breaking change doc.

**Comment by ayj** [comment]
Let's wait for someone from the networking team to chime in. This might be a simple validation bug in Pilot and not a true breaking change.

**Comment by duderino** [comment]
Sorry guys, we're bombarded by lots of github mentions every day and since this isn't an Istio issue no bug scrub could every find it.   Next time, could you file a bit here?  https://github.com/istio/istio/issues/new?template=bug_report.md

**Comment by howardjohn** [comment]
Something is actually wrong on Istio 1.0.6 as far as I can tell:

```
default/productcatalogservice-6f6df99f7f-blskm[server]: {"message":"failed to start profiler: failed to get the project ID from Compute Engine: Get http://169.254.169.254/computeMetadata/v1/project/project-id: dial tcp 169.254.169.254:80: connect: connection refused","severity":"warning","timestamp":"2019-03-08T15:53:56.646352265Z"}
```

With Istio off, it works fine.

This is with a clean cluster, installing 1.0.6, then `kubectl apply -f release/` on master.

At the same time, I am able to create a pod and curl `metadata.google.internal` and `169.254.169.254` just fine

**Comment by ahmetb** [comment]
@howardjohn just FYI that profiler/tracing exporters are initially expected to fail because Istio nondeterministically doesn't make networking available during first couple of milliseconds of the pod (because of the lack of container start order regarding istio-proxy). It might be initially succeeding.

Instead of looking at productcatalog logs, I recommend creating a temporary pod and curl'ing from there.
