### ISSUE TITLE
cartservice crashes on start when Istio 1.1 proxy injection is enabled

### ISSUE THREAD

**Issue by davidebbo** [GoogleCloudPlatform/microservices-demo#162]
Using Istio 1.1.0-rc.0 from dockerhub. When proxy injection is enabled, cartservice fails to start.

Here is what I see in the cartservice logs, though I'm not sure if that's the real problem or some red herring:

```
 textPayload:  "StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. ProtocolFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 890
   at cartservice.cartstore.RedisCartStore.EnsureRedisConnected() in /app/cartstore/RedisCartStore.cs:line 79
   at cartservice.cartstore.RedisCartStore.InitializeAsync() in /app/cartstore/RedisCartStore.cs:line 60
   at cartservice.Program.<>c__DisplayClass4_0.<<StartServer>b__0>d.MoveNext() in /app/Program.cs:line 54
```

**Comment by ahmetb** [comment]
Do you deploy first then enable injection?

Looks like it’s failing to talk to redis service (tcp redis wire protocol). Do both have sidecars?

Are you on mTLS strict or permissive mode?
cc: @mokeefe

**Comment by davidebbo** [comment]
I tried back and forth enabling/disabling injection, each time killing all the pods to give them fresh start. App runs great without injection.

Within injection, the redis service looks healthy and has sidecar. cartservice is the only one that seems to have issues:

```
NAME                                     READY   STATUS             RESTARTS   AGE
adservice-6cd6965787-5wh2b               2/2     Running            0          16m
cartservice-78969bb54d-lcb2r             1/2     CrashLoopBackOff   7          16m
checkoutservice-6848667dd7-ltzln         2/2     Running            0          16m
currencyservice-668f49f985-qbdzq         2/2     Running            0          16m
emailservice-796bb9588b-dvfzl            2/2     Running            0          16m
frontend-6dcd4969b4-l47m7                2/2     Running            0          16m
loadgenerator-b67b89d8f-cnqht            0/2     Init:0/2           0          16m
paymentservice-548657568f-9wx4v          2/2     Running            0          16m
productcatalogservice-7b94dfb45c-lv4z8   2/2     Running            0          16m
recommendationservice-5fb85f46df-wxnh6   2/2     Running            0          16m
redis-cart-9b864d47f-5b4ng               2/2     Running            0          16m
shippingservice-5f5d75bf65-2jmsr         2/2     Running            0          16m
```

**Comment by ahmetb** [comment]
I'm fairly certain multiple people have tested this on GKE Istio add-on (mTLS permissive mode) with Istio 1.0.x and it was working fine. Although this issue sounds similar: #141.

I wonder if this could be a change regarding how port names (on the pod spec) are treated to infer the protocol type?

**Comment by davidebbo** [comment]
And I forgot to mention: I'm using permissive.

@ayj how are the best Istio people to help look into this?

**Comment by ayj** [comment]
cc @andraxylia @costinm

**Comment by meganokeefe** [comment]
@davidebbo I followed your workflow (GKE `v1.11.7-gke.4`, istio `1.1-rc0`, Permissive, enable injection, deploy hipstershop) and I'm seeing the same thing: 

```
NAME                                     READY   STATUS             RESTARTS   AGE
adservice-6cd6965787-xchgd               2/2     Running            0          6m
cartservice-78969bb54d-tsvff             1/2     CrashLoopBackOff   6          7m
checkoutservice-6848667dd7-mr6gr         2/2     Running            0          7m
currencyservice-668f49f985-vhv6h         2/2     Running            0          6m
emailservice-796bb9588b-9pcm8            2/2     Running            0          7m
frontend-6dcd4969b4-vh2hq                2/2     Running            0          7m
loadgenerator-b67b89d8f-r7q7h            0/2     Init:0/2           0          6m
paymentservice-548657568f-8tmr8          2/2     Running            0          7m
productcatalogservice-7b94dfb45c-9gxxd   2/2     Running            0          7m
recommendationservice-5fb85f46df-vtqst   2/2     Running            0          7m
redis-cart-9b864d47f-dxfkj               2/2     Running            0          6m
shippingservice-5f5d75bf65-kn958         2/2     Running            0          6m
```


cartservice logs: 

```
$ kubectl logs cartservice-78969bb54d-tsvff server

Started as process with id 1
Reading host address from LISTEN_ADDR environment variable
Reading cart service port from PORT environment variable
Reading redis cache address from environment variable REDIS_ADDR
Connecting to Redis: redis-cart:6379,ssl=false,allowAdmin=true,connectRetry=5
StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. ProtocolFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 890
   at cartservice.cartstore.RedisCartStore.EnsureRedisConnected() in /app/cartstore/RedisCartStore.cs:line 79
   at cartservice.cartstore.RedisCartStore.InitializeAsync() in /app/cartstore/RedisCartStore.cs:line 60
   at cartservice.Program.<>c__DisplayClass4_0.<<StartServer>b__0>d.MoveNext() in /app/Program.cs:line 54
```

**Note**: For me, the loadgenerator pod is also not starting up, I believe due to the [initContainer cmd](https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/kubernetes-manifests/loadgenerator.yaml#L31) (curl frontend) not passing.  

```
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
```

I wonder if these 2 issues are connected - *ie.* even with Permissive mode, istio-injected pods in the same namespace cannot communicate over HTTP.

**Comment by ahmetb** [comment]
> For me, the loadgenerator pod is also not starting up

Could this be because init-containers don't have the sidecar available to them? (I'm not sure if this statement is true).

**Comment by davidebbo** [comment]
> For me, the loadgenerator pod is also not starting up, I believe due to the [initContainer cmd](https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/kubernetes-manifests/loadgenerator.yaml#L31) (curl frontend) not passing.

Indeed, I forgot to mention that, but I see the same thing. So it appears to be a pretty consistent repro.

If you guys suspect an Istio 1.1 issue (which seems plausible since it worked in 1.0), we should open Istio issues to track there.

**Comment by incfly** [comment]
> If you guys suspect an Istio 1.1 issue (which seems plausible since it worked in 1.0), we should open Istio issues to track there.

Is there any data point saying this current hipster app at HEAD version works with 1.0 as well? Just trying to ensure it's not due to the delta in this app itself.

**Comment by incfly** [comment]
Also would like to share another data point, if you annotate the `cartservice` with sidecar.istio.io/inject: false to disable the sidecar, then this error will disappear.

**Comment by davidebbo** [comment]
@incfly yes, it works fine with 1.0.4. Issue only occurs with 1.1 with proxy enabled.

**Comment by howardjohn** [comment]
Running into this with Istio 1.1 rc1 as well. If I start up a new pod (with a sidecar), run `redis-cli -h redis-cart ping` it succeeds. This indicates that it *might* be a problem with `cartservice` itself, and not directly Istio. It looks like cartservice is pretty much doing the same thing though, which is weird that it is failing but I can access with redis-cli.

**Comment by incfly** [comment]
The issue we filed on istio side can be found at
https://github.com/istio/istio/issues/12139

**Comment by ahmetb** [comment]
> This indicates that it _might_ be a problem with `cartservice` itself, and not directly Istio.

I don't think this is the case, given it works with istio 1.0 with sidecar injected. The apps have no notion of Istio, so ideally this should work fine in permissive mode.

**Comment by ahmetb** [comment]
> Is there any data point saying this current hipster app at HEAD version works with Istio 1.0 as well? Just trying to ensure it's not due to the delta in this app itself.

You can use the v0.1.0 tag and `release/*.yaml`, this is verified to be working with Istio 1.0.x. Pretty sure HEAD works with 1.0.x right now, too.

**Comment by incfly** [comment]
Folks if you're blocking on getting  this app working with Istio 1.1 release, try to change `[redis.yaml](https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/kubernetes-manifests/redis.yaml#L61)` service port name from "redis" to "tcp".

This can get cartservice working again.

**Comment by incfly** [comment]
And given the same Istio version can make `redis-cli` works with `redis-cart` server, but not for `cartservice`. I really doubt this can be a compatibility issue between the `evnoy.redis_proxy` filter with the client libraries this cartservice uses (StackExchange right?).

Next step we should try to configure an envoy next to cartservice with hardcoded redis config in front of cartservice. And if it does not work, then we should file a bug either to StackExchange or Envoy side. If it works, we need to dig a bitter deeper on Istio side.

https://github.com/envoyproxy/envoy/tree/master/examples/redis

**Comment by howardjohn** [comment]
On Istio 1.1rc2 this should be working now. Let me know if that's not the case for you

**Comment by GeckoSplinter** [comment]
Hello @howardjohn  we are on 1.1rc2 and it's not working with the last ./release

It's working with @incfly quick fix : replacing service port name from "redis" to "tcp".

**Comment by howardjohn** [comment]
Sorry I mispoke. This was fixed in https://github.com/istio/istio/pull/12236 which is in 1.1rc3 but not 1.1rc2.

@GeckoSplinter

**Comment by davidebbo** [comment]
Works for me on rc3, so closing.
