### ISSUE TITLE
Make all services respect $PORT

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#163]
Ideally all services should be easily configurable with $PORT. Right now some aren't. They either use another env var name, or hardcode a port.

Here are required changes:

- [ ] cartservice (uses $LISTEN_PORT or -–port/-p)
- [ ] productcatalogservice (uses -port defaulting to 3550)
- [ ] currencyservice (hardcodes 7000)
- [ ] shippingservice (uses $APP_PORT, defaulting to 50001)

**Comment by jan25** [comment]
Hi, is anyone working on this issue currently? If not, i can look into it. Thanks!

**Comment by ahmetb** [comment]
Feel free to pick it up. Let us know here if/when you start. Thanks.

**Comment by jan25** [comment]
Hey @ahmetb , Thanks! I started working on it

I looked at service manifest files and looks like for many services the dependency service name and port are hardcoded at several places(example [here](https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/kubernetes-manifests/checkoutservice.yaml#L39)).

I suggest we helmify all services into one chart, That way we will have single place to manage PORTs for each service. what do you think?

**Comment by ahmetb** [comment]
We won’t use helm. It adds extra complexity with minimal to no gain. We didn’t need to change the ports so far. 

It’s by design we hardcode service discovery (addr:port) of other services in Kubernetes manifests.

If we can just make services respect PORT, that’d be enough.

**Comment by ahmetb** [comment]
@jan25 have you had a chance to work on it, or should someone else pick it up?

**Comment by jan25** [comment]
@ahmetb I opened a PR that fixes the main issue of taking PORT from service manifests. However, there is scope for code clean up around the code where we read PORT from env(for example there is redundant code that sets default port if no env PORT is available). Let me know if its a good idea to do it in this PR too. Currently i marked it as WIP just in case. Suggestions/Improvements are welcome

**Comment by jan25** [comment]
@ahmetb do you think we should close this issue?

**Comment by ahmetb** [comment]
Yes, thanks.
