### ISSUE TITLE
getting can't be pulled error when trying to deploy demo app with skaffold to eks

### ISSUE THREAD

**Issue by greenszpila** [GoogleCloudPlatform/microservices-demo#1671]
Hello, I have cloned the repo and keep getting the following errors related to different deployments at each `skaffold dev` run. 
I am trying to deploy the workload to my dev EKS cluster. But it keeps failing at each `skaffold dev` execution.
``` 
 - deployment/emailservice: container server is waiting to start: emailservice: can't be pulled
 ...
  - deployment/checkoutservice: container server is waiting to start: checkoutservice:1537c4a..9a9ef can't be pulled
 ``` 
 I have docker running locally and the build phase has been completed.  Is there a way to enable debug logs? 
 What could be the issue? My nodes are 4 CPUs and 16 GB RAM each.   
 Is this something to do with pulling docker images by EKS from my desktop? Bigger snipped below: 
 
 ```
 - deployment.apps/recommendationservice created
 - deployment.apps/redis-cart created
 - deployment.apps/shippingservice created
Waiting for deployments to stabilize...
 - deployment/recommendationservice: container server is waiting to start: recommendationservice:80db29b97ccd75f68072d00539c88ae566da5d9024a9004a536c26d4b38a5b00 can't be pulled
    - pod/recommendationservice-bd99578-qj7zb: container server is waiting to start: recommendationservice:80db29b97ccd75f68072d00539c88ae566da5d9024a9004a536c26d4b38a5b00 can't be pulled
 - deployment/recommendationservice failed. Error: container server is waiting to start: recommendationservice:80db29b97ccd75f68072d00539c88ae566da5d9024a9004a536c26d4b38a5b00 can't be pulled.
Cleaning up...
 - service "adservice" deleted
 - service "cartservice" deleted
 - service "checkoutservice" deleted
 ```

**Comment by bourgeoisor** [comment]
Hi @greenszpila! What's the full `skaffold dev` command you tried to run? From the logs, it looks like Skaffold wasn't provided any image repository, so it's trying to pull from local (local from your EKS cluster, that is). It won't be able to find images from your development environment.

Your command should look like this: `skaffold dev --default-repo=<image_repo>` where `<image_repo>` is substituted with a valid image repository that you have access to (like from ECR is you stay within Amazon: https://aws.amazon.com/ecr/).

Let me know if you have any more info or questions!

**Comment by greenszpila** [comment]
@bourgeoisor  thanks for getting back. 

I am new to skaffold and just used the default `skaffold dev` command. I understood that EKS couldn't download docker images from my local desktop docker repo. 
Now I have created ECR public repo. And the skaffold command is pointing to it: `skaffold dev --default-repo public.ecr.aws/xxxx/online-boutique`  
However, I am getting `container server is waiting to start: public.ecr.aws/tag can't be pulled` 
I guess, I need to modify the default `skaffold.yaml` file now.  I will be searching for a solution but I would appreciate it if you could share some leads, thanks.

**Comment by bourgeoisor** [comment]
No worries :)

At this point I think this is not related to this repository specifically, so I'll be closing the issue. Do feel free to reopen if you suspect you're running into an issue that's directly related to it, though.

As for your next steps: I'd start with checking that your images were indeed pushed to the ECR registry (for example, can you `docker pull public.ecr.aws/<tag>` them locally? If not, then I'd look to see if you need to authenticate to ECR locally and/or pass that authentication to Skaffold before building.

If you can pull the images locally and can confirm that they are indeed in ECR, then the next step would be to see if there are certain permissions you need to give your EKS cluster (through IAM resources or otherwise).

Best of luck!
