### ISSUE TITLE
gRpc server

### ISSUE THREAD

**Issue by GhostWalkers** [GoogleCloudPlatform/microservices-demo#1675]
hello, I looked at the project and saw that for each service its own gRpc server is created and each on its own port, I would like to ask how normal practice is, because it seems very wild to me to keep in mind which port is responsible for what, it seems to me very wild, I also realized that in It is impossible to “complement” an existing gRpc server in a completely isolated microservice, it honestly doesn’t look very good. tell me how normal this practice is, and whether you are building your google services. thanks for the answer

**Comment by NimJay** [comment]
Thanks for the quick response! :)

> ... i meant adding a single gripc server so that it is possible to register new handlers in "hot" mode ... a single gripc server is started to which project services are already connected.

* Ah, if I understand correctly, I think `skaffold dev` fits your needs.
* Following the [development guide](https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/docs/development-guide.md#development-guide) (either for a local/kind cluster or a Google Kubernetes Engine cluster) will allow you to deploy the app (all microservices) while also automatically rebuild and redeploy services that you make source code changes to (i.e. "hot" mode).
* **Heads-up:** Apple M1 chips are currently not supported. Relevant [issue here](https://github.com/GoogleCloudPlatform/microservices-demo/issues/1448). :(
