### ISSUE TITLE
Failing to pull images

### ISSUE THREAD

**Issue by Alex99P** [GoogleCloudPlatform/microservices-demo#1679]
I tried to develop in the local cluster, but got the "falling to pull image" error for almost all images. 

![image](https://user-images.githubusercontent.com/67483871/231097948-91327b79-05e9-4ec7-a19e-802f0edc78a9.png)

I am new to K8s.

**Comment by NimJay** [comment]
**Question 2:** What type of local cluster are you using? A [minikube](https://minikube.sigs.k8s.io/docs/start/) cluster? A [kind](https://kind.sigs.k8s.io/docs/user/quick-start/) cluster?

**Comment by Alex99P** [comment]
Hi @NimJay, I used skaffold run in a minikube cluster.

**Comment by Alex99P** [comment]
Thank you for answers!
