### ISSUE TITLE
Web page shows which particular service fails instead of the full stack trace

### ISSUE THREAD

**Issue by incfly** [GoogleCloudPlatform/microservices-demo#169]
For example if productcatalog service fails, the frontend home page instead of printing out the full stack trace, it can print out xxx service: error code xxx, not available in appropriate place on the web page, or js console log?

This is useful for both our own development and demo purpose. As this app developer, we can easily know what's going wrong.

More importantly, we can show that to our user in a demo, what will fail and what to make it succeed, to see the before and after effect in a migration/debugging scenario.

I understand for real product you wont do this, but considering this app is for a microservice demo, so it might make sense to show more service interactions on the UI directly :)

**Comment by ahmetb** [comment]
gRPC has a very limited error format. It’s mostly an error code + string. I don’t think people in the outside world carry stack traces on RPCs. 

These would be the reasons not to implement.

**Comment by incfly** [comment]
Oh actually I looked a bit of closer, I found the error text on the web page already include that,

```
could not retrieve currencies
```

![image](https://user-images.githubusercontent.com/1661831/53671963-7677b280-3c35-11e9-9aa8-076a0b99087e.png)

That's good enough! Closing, thanks!

**Comment by ahmetb** [comment]
That error msg is from frontend. Because we errors.Wrap the error from grpc. In some cases we might’ve forgotten to do that, and that’s a bug.
