### ISSUE TITLE
Expose load generator UI

### ISSUE THREAD

**Issue by minherz** [GoogleCloudPlatform/microservices-demo#1692]
### Describe request or inquiry 
Current implementation of the load generator is configured to create a constant load on the application.
It can be useful to allow users to customize load generation by exposing GUI of the locust's load generator.

### What purpose/environment will this feature serve? 
This change will extend user's options for simulating loads on the application so it can be used in wider range of scenarios.

**Comment by minherz** [comment]
This feature request is deprioritized and the work on it will not start before 23'Q4. Please vote :+1:  and :-1:  in **Description** if you want / disregard this functionality.

**Comment by bourgeoisor** [comment]
This is unlikely to be prioritized within the next year, so I'll close the issue. We can always reopen later if prioritization changes.
