### ISSUE TITLE
Don't hardcode the GCP project name

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/microservices-demo#17]
The demo hardcodes a GCP project name (microservices-demo-app). Users who don't have access to the hardcoded project cannot run the instructions due to ACL issues.

**Comment by rakyll** [comment]
It would be just sufficient enough to replace them with gcr.io/YOUR_PROJECT/.

**Comment by ahmetb** [comment]
Skaffold has a proposal to fix this (i.e. prevent hardcoding). I’m mostly waiting for that. Right now this is documented in the instructions and at least serves me while deploying. 😊
