### ISSUE TITLE
PRODUCT_CATALOG_SERVICE_ADDR environment variable not set

### ISSUE THREAD

**Issue by ajonp** [GoogleCloudPlatform/microservices-demo#170]
Working through https://google.qwiklabs.com/focuses/4186 

File "/recommendationservice/recommendation_server.py", line 90, in <module> raise Exception('PRODUCT_CATALOG_SERVICE_ADDR environment variable not set')

I tried to export PRODUCT_CATALOG_SERVICE_ADDR = <ip of checkoutservice>

**Comment by ahmetb** [comment]
The link didn’t work for me. 
What’s the title of the codelab you are following?

**Comment by ahmetb** [comment]
when I click to your link, I get:

> Sorry, access denied to this resource.

This repository maintainers don't support any known Qwiklabs codelabs. I recommend following up in Qwiklabs feedback or issue trackers, if any.
