### ISSUE TITLE
Instructions to enable Jaeger tracing for services

### ISSUE THREAD

**Issue by aghag10** [GoogleCloudPlatform/microservices-demo#174]
Tahnks @ahmetb for following up on #108. I see that some of the services are already instrumented with Jaeger. Could you guys please add instructions to enable istio provided Jaeger service?

**Comment by ahmetb** [comment]
@aghag10 We may remove jaeger exporter in favor of oc-agent. (see #109) please don't rely on it just yet. If/when we decide to support it, we'd probably ship with JAEGER config uncommented and instructions on how to install Jaeger.

**Comment by aghag10** [comment]
@ahmetb Does oc-agent support real-time dependency/call graphs for microservices? What would be the front end service exposing traces and spans for different microservices calls?

**Comment by ahmetb** [comment]
@aghag10 no, it just standardizes collection/sampling/exporting. I'm not fully familiar with it either. However migrating to that would eliminate Stackdriver and Jaeger code from each service, instead we would just export to oc-agent, and configure oc-agent with what place(s) we wanna export the final traces (Stackdriver, Jaeger, ... or multiple of them at the same time).
