### ISSUE TITLE
Stackdriver Profiler Java agent for AdService

### ISSUE THREAD

**Issue by kalyanac** [GoogleCloudPlatform/microservices-demo#177]
AdService currently used openjdk:8-alpine. Stackdriver Profiler Java agent does not work on this image due to glibc dependency. Based on my initial experiments, supporting Alpine is a non-trivial task. 

Are there any objections to using openjdk-8-stretch? I tested with this and did not see any issues. If there are no objections, I will send a PR to update the base image and add Profiler Java agent.

**Comment by ahmetb** [comment]
I think it was primarily image size as it impacts build and push times of docker images. Pretty much everything else uses alpine. But if it’s absolutely necessary we can switch. 

Btw it’s unclear you’re a Googler from your GitHub profile. Please add a detail indicating such.

**Comment by kalyanac** [comment]
Ok, glad to hear. I'll send a PR tomorrow. 

Yes, I'm a Googler. Can you please let me know what I need to add to indicate that? I'm added to the Google & Google Cloud Platform organizations.

**Comment by ahmetb** [comment]
My bad 😊 I didn’t see it on mobile. There’s also company field in your profile if you want to fill it out.

**Comment by ahmetb** [comment]
@kalyanac also your profile doesn't show your orgs. 
You need to visit your org list and make them publicly visible on your profile. Here's what I see:

![image](https://user-images.githubusercontent.com/159209/53979743-6b080980-40c3-11e9-8281-93fb3375928a.png)

**Comment by kalyanac** [comment]
I have updated my settings to have orgs show up in my profile and the company field.

**Comment by kalyanac** [comment]
Fixed with #210
