### ISSUE TITLE
Question about the transaction

### ISSUE THREAD

**Issue by shihyuho** [GoogleCloudPlatform/microservices-demo#180]
Hi, 

I was wondering what is the best practice to do the transaction when placing the order in [checkoutService.PlaceOrder](https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/src/checkoutservice/main.go#L224)? 

<img width="704" alt="teampaper snap_2019-03-08 10-27-17 2x" src="https://user-images.githubusercontent.com/2764992/54003341-d833a180-418c-11e9-8343-6245f227b507.png">

If `cs.shipOrder` failed for some reason, what is the best way to rollback the `cs.chargeCard` call?

thank you.

**Comment by ahmetb** [comment]
Implementing a proper e-commerce service isn't in scope for this **demo** application. So transactions/rollbacks aren't relevant to this repo.
