### ISSUE TITLE
Stackdriver - Request had insufficient authentication scopes.

### ISSUE THREAD

**Issue by howardjohn** [GoogleCloudPlatform/microservices-demo#185]
shippingservice's Logs are filled with
```
Failed to export to Stackdriver: rpc error: code = PermissionDenied desc = Request had insufficient authentication scopes
```

Running on GKE.

I am running with Istio.

**Comment by ahmetb** [comment]
Can you make sure you're generating the cluster with the command provided in README. If you're using another existing cluster, it may have insufficient scopes. (I'm assuming this error is from tracing exporter registration.)

Another problem might be that you might be using a custom service account on your GKE cluster.

Another thing that can cause issues is if you've edited your "Compute Engine default service account"s permissions etc.

**Comment by askmeegs** [comment]
I wonder if we should add a "troubleshooting" section to the README,  on this?

**Comment by ahmetb** [comment]
Yeah I think it’s doable. Some error classes definitely came up multiple times. 

We’ve observed I think in some cases despite the cluster has the right scopes, the Tracing API might not be enabled (maybe that had a different message).
