### ISSUE TITLE
frontend: when scaled it keep on crashing with readinessProbe and livenessProbe errors!

### ISSUE THREAD

**Issue by Haybu** [GoogleCloudPlatform/microservices-demo#186]
running services on GKE + Istio, I scaled all deployments to perform a load test. For instance, frontend is autoscaled based on CPU percentage as follows. Pods of frontend deployment is crashing and restarting because of readiness and liveness probes, any idea why?

kubectl autoscale deployment/frontend --min=7 --max=10 --cpu-percent=80

**Comment by ahmetb** [comment]
Have you looked at the logs?

**Comment by ahmetb** [comment]
If you can provide more info, it would be appreciated.

**Comment by ahmetb** [comment]
Closed due to inactivity.
