### ISSUE TITLE
Regenerate Stackdriver service graph locally with Jaeger

### ISSUE THREAD

**Issue by aghag10** [GoogleCloudPlatform/microservices-demo#187]
Hi,

Based on issues #108, #109, I understand that Jaeger instrumentation isn't available in the services yet. However, looking at the GCP Stackdriver service monitoring documentation [1] (it seems to be using the same Hipster demo application), service graph is supported in Stackdriver. How are the detailed end-to-end traces spans and their corresponding latencies retrieved without Jaeger instrumentation (refer: DIAGNOSTICS image on the document). The spans stich together traces from related calls. E.g call to get product originated in front end service, and services like productcatalogue, currency, recommendation were invoked one after the other.
Are these traces and latency values exported somewhere if we were to deploy the application on our local K8s cluster? Essentially, would we be able to get traces all the way from front end service to all the other services invoked for a user call and get their corresponding latencies? 

[1] https://cloud.google.com/blog/products/gcp/drilling-down-into-stackdriver-service-monitoring

**Comment by ahmetb** [comment]
Right now locally we don't export anywhere. There's open issues to add Jaeger exporters everywhere (#112) and offer a local Jaeger installation.

However that effort has stalled as I think we're looking into integration `oc-agent` so that we export traces to a centralized place both locally/on cloud –then export to a desired target (stackdriver, jaeger etc).

If you are familiar with OpenCensus Agent work and willing to help, it would super appreciated.
cc: @bogdandrutu @rghetia

**Comment by aghag10** [comment]
Sorry, I'm not familiar with OpenCensus. Jaeger/Zipkins seem to be the popular instrumentation mecahnisms. 
Looking at the GCP stackdriver documentation, it seems like the services need to have some instrumentation for Stackdriver to be able to stick together individual services traces into a span. Maybe you have some stackdriver agents running inside services that export the traces to a central location?

**Comment by ahmetb** [comment]
We use OpenCensus that exports to Stackdriver. When configured correctly, it would also export to Jaeger.

I gather this rather a question so I'll go ahead and close it. For stuff like Service Graph, right now there are no offline solutions we offer. But if you use the Istio support, you can get good charts with Kiali dashboard locally.

**Comment by aghag10** [comment]
Even if we used istio, Kiali, we won't be able to get Service graphs unless the services are instrumented to popagate HTTP Jaeger headers. Hopefully, the Jeager instrumentation work will be unblocked soon. :)

**Comment by ahmetb** [comment]
@aghag10 I'm fairly certain people have given Kiali demos with this app before, but I'm not sure how. If you search issues/PRs with "jaeger" you'll see that almost all apps are instrumented with Jaeger.

Please give that a try by uncommenting the relevant environment variable and point them to a Jaeger instance.

**Comment by aghag10** [comment]
@ahmetb @rghetia I'm looking at this commit [1] to enable Jaeger tracing in one of the services. 
All it takes is to add this piece of code in a service (and exporting Jaeger env variables in yaml files)? 

static void initJaeger() {
    boolean enabled = Boolean.parseBoolean(System.getenv("JAEGER_ENABLED"));
    if (enabled) {
      // Register Jaeger Tracing.
      JaegerTraceExporter.createAndRegister("http://jaeger-collector:14268/api/traces", "adservice");
      logger.info("Jaeger initialization complete.");
    } else {
      logger.info("Jaeger initialization disabled.");
    }
  }

[1] https://github.com/GoogleCloudPlatform/microservices-demo/pull/111/commits/3ff613083238951249320f24eae9a60790540b70

**Comment by ahmetb** [comment]
Yeah, that's what I was trying to say. Per #112, some services still don't have jaeger exporters added. If you have time to implement this method in those services written in Python, Node, C#, you should be getting Jaeger tracing out of this app.

**Comment by askmeegs** [comment]
Kiali can generate the service graph without Jaeger tracing. 
It uses Prometheus metrics to generate the graph.  

https://www.kiali.io/documentation/architecture/
