### ISSUE TITLE
Support trace-log correlation in more services

### ISSUE THREAD

**Issue by sebright** [GoogleCloudPlatform/microservices-demo#188]
This issue is for tracking which services support log correlation (suggested in https://github.com/GoogleCloudPlatform/microservices-demo/pull/168#issuecomment-468548618).  Log correlation may depend on structured logging from issue #47.

- [x] adservice (#59)
- [ ] cartservice
- [ ] checkoutservice
- [ ] currencyservice
- [ ] emailservice
- [ ] frontend
- [ ] paymentservice
- [ ] productcatalogservice
- [ ] recommendationservice
- [ ] shippingservice

**Comment by ahmetb** [comment]
Thanks for tracking this.
Is there a plan to refactor more services by Stackdriver/OpenCensus team members?

**Comment by c24t** [comment]
We added a logger to the python client that exposes trace data to formatters in https://github.com/census-instrumentation/opencensus-python/pull/536. We'll have to change the formatter to include the new fields for log correlation to work in stackdriver.

I'm happy to make the changes to the email and recommendation services, but can't commit to doing it soon.

**Comment by ahmetb** [comment]
@c24t That's great, thanks.

**Comment by DanSanche** [comment]
Closing this and other `kind/improvement` issues as we attempt to move the project into a stable maintenance state. Let me know if you want to take this on again and I'll reopen
