### ISSUE TITLE
How (if) would you handle shared code?

### ISSUE THREAD

**Issue by pie6k** [GoogleCloudPlatform/microservices-demo#194]
I really like monorepo approach you've created!

I wonder how to approach situation when I've got some shared code utilities I'd like to use in many different services.

How would you approach such use-case?

Do you think having shared code is bad idea in microservices architecture?

**Comment by ahmetb** [comment]
This is  really not the right place to discuss this. The reason we use a single repository is ease of maintenance. It comes with a lot of problems if this was a real app.

**Comment by pie6k** [comment]
Isn't it supposed to show how to solve problems in 'real app'?

**Comment by ahmetb** [comment]
@pie6k That's not one of the goals of this repository. Primary goal of this app is to showcase cloud-native technologies like Kubernetes, Istio, OpenCensus etc. 

Realistically we can show the best practices only in a few areas without overcomplicating the demo app. We've thought about adding Bazel to this repository to eliminate some duplication and automatically generate protos etc. But that would make it non-approachable for many beginner users browsing the repo.

If you're interested in monorepos, recommended reading: https://cacm.acm.org/magazines/2016/7/204032-why-google-stores-billions-of-lines-of-code-in-a-single-repository/fulltext

**Comment by pie6k** [comment]
got it :) thank you for explanation
