### ISSUE TITLE
JAEGER_SERVICE_ADDR is commented out in yaml's

### ISSUE THREAD

**Issue by caulagi** [GoogleCloudPlatform/microservices-demo#198]
Why is `JAEGER_SERVICE_ADDR` commented out in the yaml files (for instance, `kubernetes-manifests/frontend.yaml`)? Is this intentional?

It seems to me that setting it to empty string in the yaml would make it easier to enable/disable jaeger integration from environment variables instead of changing the yaml files and there is already code in the services to disable jaeger when it is an empty string. Should I make a PR to fix this?

**Comment by ahmetb** [comment]
See #112.

**Comment by ahmetb** [comment]
We basically don't install jaeger itself today as part of this repo, and therefore it would fail to export. We may also end up not using Jaeger, but use Jaeger through oc-agent.
