### ISSUE TITLE
Consider using Google's common proto types  & empty proto

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#2]
Right now we redefine stuff like `message Money` or `message Empty`.

It would be good to reuse this for `message Money`:
https://github.com/googleapis/googleapis/blob/master/google/type/money.proto

Also, protobuf comes with an `message Empty` as well: https://github.com/google/protobuf/blob/master/src/google/protobuf/empty.proto

This probably requires changes to:
- app source codes using these types
- `genproto.sh` in each service

**Comment by DanSanche** [comment]
Closing this and other `kind/improvement` issues as we attempt to move the project into a stable maintenance state
