### ISSUE TITLE
Istio mTLS now supports readiness/liveness probes - update README

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/microservices-demo#211]
Current [README instructs](https://github.com/GoogleCloudPlatform/microservices-demo#optional-deploying-on-a-istio-installed-gke-cluster) to remove the liveness/readiness probes from deployments, if the user has installed Istio with STRICT mTLS. 

OSS Istio 1.1 [now supports](https://istio.io/about/notes/1.1/#security) probes in mTLS, so we may want to:

1. test that this is the case 
2. modify the README accordingly

**Comment by askmeegs** [comment]
Revision: the Istio add-on for GKE is still version `1.0.6-gke.3` as of today. We should update the README once the Add-on hits `v1.1`

**Comment by askmeegs** [comment]
Update - service-level readiness/liveness probes + istio mTLS only available starting in Istio 1.2: 
https://istio.io/news/2019/announcing-1.2/#security  (otherwise you have to configure at Istio install time) 

Add-on is still on Istio 1.1 -- will wait until it hits 1.2 to verify this / remove section from the readme.

**Comment by howardjohn** [comment]
Related: https://github.com/GoogleCloudPlatform/microservices-demo/issues/269
