### ISSUE TITLE
nodejs based services OTEL instrumentation is ignoring OTEL_SERVICE_NAME

### ISSUE THREAD

**Issue by pablochacin** [GoogleCloudPlatform/microservices-demo#2142]
### Describe the bug 
I'm deploying the online boutique using a kustomization that enables tracing by adding the `ENABLE_TRACING`, `COLLECTOR_SERVICE_ADDR ` and `OTEL_SERVICE_NAME` environment variables to all services. 

This works well for go-based services but not for `nodejs` services, which report the service name as `unknown_service.node`.

In my deployment, I'm sending traces to a Grafana agent that forwards to Grafana tempo.

### To Reproduce

This is not easy to reproduce as I'm using a custom deployment, which is documented [here](https://github.com/grafana/xk6-disruptor-demo/tree/main/demos/online-boutique)

### Logs  
```
Profiler disabled.
Tracing enabled.
```

### Screenshots 

![image](https://github.com/GoogleCloudPlatform/microservices-demo/assets/720259/f317f974-4d29-47a0-b220-b6c15a6760f4)

### Environment 
OS: Linux Ubuntu 22.04
K8s: Kind

**Comment by bourgeoisor** [comment]
cc: @NimJay and @arbrown

**Comment by iennae** [comment]
@pablochacin it looks like you might have resolved this issue. Thanks so much for reporting and offering up a fix. If I'm incorrect, please do reopen this issue.
