### ISSUE TITLE
Add test cases for payments and currency service

### ISSUE THREAD

**Issue by dineshnagarit** [GoogleCloudPlatform/microservices-demo#216]
There should be unit test cases for payments and currency microserivce.

**Comment by ahmetb** [comment]
We have limited test cases in most microservices, mostly because it’s a demo app.
However if you can contribute some, and make them part of the build process (probably the Dockerfile?) it’d be appreciated

**Comment by dineshnagarit** [comment]
@ahmetb  I am planing to work on this next week, I will keep you updated about the progress.

**Comment by DanSanche** [comment]
We're closing this and other `kind/improvement` issues as we attempt to move the project into a stable maintenance state. Let me know if still plan on working on this and I can re-open
