### ISSUE TITLE
Provide SVG of architecture diagram

### ISSUE THREAD

**Issue by sdake** [GoogleCloudPlatform/microservices-demo#220]
HI folks.  I took a look at restructuring the deployments of this demo in my kubecon talk featuring hipster shop.  See here for my diagram:

https://docs.google.com/drawings/d/17lTCavrTLkrH1rgWAifUovvbHVa4c8So8EzX_-QufYc/edit?usp=sharing

Can a copy of the `SVG` formatted diagram be provided in repo in addition to the `PNG` for others wishing to do the same?

Cheers
-steve

**Comment by ahmetb** [comment]
We frequently update the diagram so I'm not sure if we can commit to keeping both SVG + PNG up to date. Maybe we can replace it with the SVG (internally we store it in LucidChart, so you can't really edit it with another tool).

I just recommend redrawing it like you did.

**Comment by sdake** [comment]
@ahmetb thank you for the response.  As you are probably aware and alluded to in your comment, SVG is an editable format, renders well in printed conference documentation, and also renders well in most/(all?) modern web browsers.

I thought it might be helpful for others to have an up-to-date editable version to work with for conference presentations of Hipster Shop, where PNG is not suitable.  An example of where PNG is not suitable is CNCF slide decks, where printing or magnification of documentation is a requirement for accessibility.  KubeCon requires all slide material to be in some form of scalable vector format - if that is at all feasible.  An example of a material that is not feasible for SVG are photographs, where PNG is a requirement.  The arch diagram in this repo should be feasible in a vector format.

I understand you don't want to maintain two copies.  I don't know anything about LucidChart's capabilities as to whether it natively uses SVG or just has an output mode to SVG.  I used google draw for my replication of the diagram - it took me about one hour to replicate, and others could do so as well.  I don't intend personally to maintain nor support an updated version of the architecture diagram in SVG, so I feel your pain :)

Feel free to close this if you wish to take no further action.

Cheers
-steve

**Comment by sdake** [comment]
@ahmetb just a quick follow-up, I use my `svg` rendered copy here:

https://github.com/sdake/multicloud

github properly renders SVG (thankfully:).

Cheers
-steve

**Comment by ahmetb** [comment]
Super cool! I will close this issue. Hopefully people can find it by searching if they need it.

**Comment by abitrolly** [comment]
@ibenrodriguez the answer to your question at https://github.com/GoogleCloudPlatform/microservices-demo/commit/b44d855e5c5879c80435c0891abadd3c5b246043 is LucidChart.

But maybe you want https://github.com/mingrammer/diagrams - if your company can sponsor the guys to help them with maintenance, that would be appreciated a lot.
