### ISSUE TITLE
deployment to EKS

### ISSUE THREAD

**Issue by bhajian** [GoogleCloudPlatform/microservices-demo#226]
I think this is a fantastic project and we are going to use it to show how to use kubernetes EKS in AWS.
the deployment files are built only for gcloud. However, we would need to develop scripts to deploy this demo to EKS and AKS.

**Comment by ahmetb** [comment]
Not really, as long as you have a Kubernetes cluster, you should be able to deploy. There's not much in this demo specific to GKE, as it also runs locally on your laptop.
