### ISSUE TITLE
supporting most of the istio features for a demo

### ISSUE THREAD

**Issue by bhajian** [GoogleCloudPlatform/microservices-demo#227]
This is a great demo. However, it lacks some features to show the actual power of Istio.
For example:
- how Istio manages the traffic between microservices and demoing the security features of Istio.
- how to use Istio to do fault injection
- how to use Istio to mirror traffic
- how to use Istio to do Canary deployment
- how to use Istio to do retry logic when there is a fault.

**Comment by ahmetb** [comment]
@bhajian we have Istio-specific demos built with this app at https://github.com/GoogleCloudPlatform/istio-samples.

This demo cannot have an exhaustive list of all features of all the products it highlights, that would be pretty difficult to maintain.
