### ISSUE TITLE
Supporting Redis high availability

### ISSUE THREAD

**Issue by bhajian** [GoogleCloudPlatform/microservices-demo#228]
The redis deployment is creating a single node for redis but not a clustered redis. I think Redis is a single point of failure and needs to be clustered. This way, in a demo you can kill a node in the kubernetes cluster and demo to the audience that the cluster is still functioning.

**Comment by ahmetb** [comment]
This is by design to keep the demo app simple. The app gives a false sense of persistence, as it’s not actually in the demo app’s focus to show HA/persistence features (like StatefulSet or replicated/on-disk redis).
