### ISSUE TITLE
Enabling Tracing in Local Kubernetes Cluster

### ISSUE THREAD

**Issue by dufanrong** [GoogleCloudPlatform/microservices-demo#2317]
First of all, thank you for providing this impressive demo. I've successfully deployed the project on my local Kubernetes cluster. However, I noticed in the README that Cloud Operations (Stackdriver) includes information about profiling and tracing.

It mentions when the project is running outside of Google Cloud, these features remain inactive.

I'm interested in enabling tracing functionality in my local Kubernetes environment. Are there any recommendations or configuration guides available to achieve similar tracing functionality locally as mentioned in Stackdriver?

Thank you for your time and support!

**Comment by NimJay** [comment]
Hi @dufanrong, :)

You're very welcome. (The original authors of this demo was @ahmetb and a few other [ex-]Googlers, so a big thanks to them.)

Unfortunately, I cannot help you much here.
* This repo is currently in strict maintenance mode, so we won't add new features such as support for tracing on local Kubernetes clusters.
* You can also try https://github.com/open-telemetry/opentelemetry-demo/ which is actually a fork of our repo (github.com/GoogleCloudPlatform/microservices-demo). 
* If you'd like to alter the code of this repo to get local cluster tracing working:
    * here's [our development guide](https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/docs/development-guide.md)
    * here's the [pull-request where we added Tracing support](https://github.com/GoogleCloudPlatform/microservices-demo/pull/1167/files) — you'll see a lot of Google-specific code in there, which you'll want to remove for your use case.

Good luck and sorry for the late response. :)
I will close this issue now. Hope that's okay.
