### ISSUE TITLE
Running it on docker/kubernates locally Docker for Desktop

### ISSUE THREAD

**Issue by ccristian** [GoogleCloudPlatform/microservices-demo#232]
I followed all the instructions , but i get this error while running scaffold run

WARN[0001] Error processing base image (python:3-slim) for ONBUILD triggers: getting remote config: getting image: <empty transport.Error response>. Dependencies may be incomplete. 
Sending build context to Docker daemon 

FATA[0002] build failed: building [emailservice]: build artifact: docker build: error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.38/build?buildargs=null&cachefrom=null&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&forcerm=1&labels=null&memory=0&memswap=0&networkmode=&rm=0&shmsize=0&t=emailservice%3Av0.1.1-3-g1c057fc&target=&ulimits=null: creating docker context: getting relative tar paths: listing copied files: retrieving image config: getting image: <empty transport.Error response>

Thanks

**Comment by ahmetb** [comment]
Looks like a docker issue.
Can you build other docker images on that machine?

**Comment by ahmetb** [comment]
I recommend you open an issue at https://github.com/docker/for-mac/issues

You can point to this repo and just show `docker build -t foo ./src/emailservice` is not working.
