### ISSUE TITLE
Issue with authentication for emailservice in both Docker for Desktop and GKE console

### ISSUE THREAD

**Issue by Anuradha677** [GoogleCloudPlatform/microservices-demo#233]
Starting build...
Building [gcr.io/example-gcp-practice/emailservice]...
Sending build context to Docker daemon
FATA[0010] build failed: building [gcr.io/example-gcp-practice/emailservice]: build artifact: docker build: error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v
1.38/build?buildargs=null&cachefrom=null&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&forcerm=1&labels=null&memory=0&mem
swap=0&networkmode=&rm=0&shmsize=0&t=gcr.io%2Fexample-gcp-practice%2Femailservice%3Av0.1.1-3-g1c057fc&target=&ulimits=null: creating docker context: getting relative tar 
paths: listing copied files: retrieving image config: getting image: UNAUTHORIZED: authentication required; [map[Type:repository Class: Name:library/base Action:pull]]

What i need to get the authentication for emailservice?

**Comment by ahmetb** [comment]
This looks like Docker issue.
What's the output of this for you: `docker build -t foo ./src/emailservice`?

**Comment by ahmetb** [comment]
Looks like it's a skaffold issue.
https://github.com/GoogleContainerTools/skaffold/issues/2355
You need to use a skaffold version greater than v0.32.0 (not released yet), or a sufficiently older one.

**Comment by dgageot** [comment]
Skaffold v0.33.0 has been released yesterday: https://github.com/GoogleContainerTools/skaffold/releases/tag/v0.33.0
