### ISSUE TITLE
skaffold run gives error while checking cache for one service on Linux Droplet.

### ISSUE THREAD

**Issue by PraveeenPandey** [GoogleCloudPlatform/microservices-demo#2337]
root@test-s-4vcpu-8gb-blr1:~/microservices-demo# kubectl get nodes
NAME       STATUS   ROLES           AGE    VERSION
minikube   Ready    control-plane   138d   v1.27.3
root@test-s-4vcpu-8gb-blr1:~/microservices-demo# skaffold run
Generating tags...
 - adservice -> adservice:v0.5.0-528-g46aa585-dirty
 - cartservice -> cartservice:v0.5.0-528-g46aa585
 - checkoutservice -> checkoutservice:v0.5.0-528-g46aa585
 - currencyservice -> currencyservice:v0.5.0-528-g46aa585
 - emailservice -> emailservice:v0.5.0-528-g46aa585
 - frontend -> frontend:v0.5.0-528-g46aa585
 - loadgenerator -> loadgenerator:v0.5.0-528-g46aa585
 - paymentservice -> paymentservice:v0.5.0-528-g46aa585
 - productcatalogservice -> productcatalogservice:v0.5.0-528-g46aa585
 - recommendationservice -> recommendationservice:v0.5.0-528-g46aa585
 - shippingservice -> shippingservice:v0.5.0-528-g46aa585
###Checking cache...
 ###- adservice: Error checking cache.
###getting hash for artifact "adservice": getting dependencies for "adservice": file pattern [../build.gradle ../gradlew] must ###match at least one file

I want to deploy microservices-demo on a Digital ocean Linux VM , but @NimJay here it shows a error mentioned above while executing skaffold run, why is that , kindly make me understand and this and share your advice about to proceed further.

**Comment by NimJay** [comment]
Hi @PraveeenPandey,

My immediate, unorganized thoughts:
* I have not tested `skaffold run` recently, on the `main` branch.
* But our automated testing was able to run `skaffold run` successfully about 5 days ago ([in PR 2336](https://github.com/GoogleCloudPlatform/microservices-demo/pull/2336)).
    * Our automated testing uses skaffold `v2.0.1`.
    * But our [development guide](https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/docs/development-guide.md#prerequisites) recommends skaffold `v2.0.2` of higher. Make sure you're using skaffold `v2.0.2` of higher.
* The error message seems specific to skaffold.
* [This (line 46 of /skaffold.yaml)](https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/skaffold.yaml#L46) is where we tell skaffold the "context" (location) of the adservice.
* This seems similar to https://github.com/GoogleContainerTools/skaffold/issues/4491.
* Also, try building [the Dockerfile for adservice](https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/src/adservice/Dockerfile), on its own using `docker build` — to see if it's an issue with Docker or skaffold.

Also:
* This GitHub repo is under strict maintenance mode.
* We won't be able to provide tailored troubleshooting help. 
* I'm not too familiar with using Kubernetes on DigitalOcean.
* The [primary purpose](https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/docs/purpose.md) of this repo is to showcase Google Kubernetes Engine and surrounding technologies.

So my support will be limited. So sorry! :(

**Comment by bourgeoisor** [comment]
Closing since there hasn't been a reply in a few months. Feel free to reopen if you're still running into this issue.
