### ISSUE TITLE
Update copyright to be Time.now.year (or equivalent) 

### ISSUE THREAD

**Issue by thagomizer** [GoogleCloudPlatform/microservices-demo#2450]
### Describe the bug 
The copyright says 2020 and there's a request to have the current year instead.

**Comment by bourgeoisor** [comment]
This is against Google's open-source requirements regarding copyright notices (go/copyright):

> When making changes to code with an existing copyright notice, retain earliest copyright year.

I'm happy to chat about it offline.

**Comment by NimJay** [comment]
@bourgeoisor
+1 to copyright year should reflect date of first publish.
**Question:** How about we remove "© 2020 Google Inc" from the footer of the UI?

<img width="310" alt="Screenshot 2024-04-10 at 9 04 23 AM" src="https://github.com/GoogleCloudPlatform/microservices-demo/assets/10292865/64915a80-df36-45a2-8273-e161be6c6625">

**Comment by bourgeoisor** [comment]
I'll update that one to say 2020-2024, which is a similar thing we're doing with Bank of Anthos.
