### ISSUE TITLE
Refactor ShoppingAssistantService kustomize components

### ISSUE THREAD

**Issue by bourgeoisor** [GoogleCloudPlatform/microservices-demo#2468]
Once https://github.com/GoogleCloudPlatform/microservices-demo/pull/2466 is merged, we should look into cleaning up / refactoring the kustomize components.

Copying over @NimJay's suggestions:

> I believe the cleaner approach here would be to:
> 
> - remove the disable-shopping-assistant Kustomize component
> - introduce a shopping-assistant Kustomize component that includes the ServiceAccount
> - skip the src/shoppingassistantservice folder during re-generation of /release/kubernetes-manifests.yaml (during release) — so that shoppingassistantservice is not included in /release/kubernetes-manifests.yaml
> - use ServiceAccounts for all microservices in the default deployment and remove the service-accounts Kustomize component.

**Comment by roisec** [comment]
What about update helm templates to work with ShoppingAssistantService?
