### ISSUE TITLE
Adservice and shippingservice pods are in pending state

### ISSUE THREAD

**Issue by Ashjoker24** [GoogleCloudPlatform/microservices-demo#247]
Hi,
I trying to deploy this application in my own kubernetes cluster and the two pods (mentioned below) are in pending state in 2 hrs till now. What can i do for that 

NAME                                                   READY    STATUS    RESTARTS   AGE
adservice-7bcfbd85dc-nn74b                  0/2      Pending           0          2h
shippingservice-79dd686fdb-96fth         0/2     Pending            0          2h

My cluster config ->
Master - CentOS 7 (4gb RAM and 2 CPU and 32GB disk)
kubeadm version - kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:11:18Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Docker version - Docker version 19.03.2, build 6a30dfc

Minion - CentOS7 (2 minions 2gb RAM and 1 CPU with 32 gb disk)

 I trying to build it with Istio.
Istio version - 1.2.5

**Comment by askmeegs** [comment]
Hello, for either of those `Pending` pods, could you run `kubectl describe <pod-name>` to see the Events? It's possible your nodes don't have enough CPU/memory to deploy the remaining pods.
