### ISSUE TITLE
Release v0.10.0

### ISSUE THREAD

**Issue by mathieu-benoit** [GoogleCloudPlatform/microservices-demo#2496]
Any chance to get a new release and associated new container images for these apps anytime soon?

GKE Security Posture is giving me 212 CVEs with the current/latest version `0.9.0` (Dec 2023):
<img width="359" alt="image" src="https://github.com/GoogleCloudPlatform/microservices-demo/assets/11720844/de2f86e6-52ea-4719-8bab-f4f5a1f20e84">

I'm sure a new version will resolve most, if not all, of them.

This could improve some of the demos using this awesome sample apps out there, thanks! ;)

**Comment by bourgeoisor** [comment]
Yes, this was on my list for this week!
