### ISSUE TITLE
Images are not diplaying in k8s cluster 

### ISSUE THREAD

**Issue by kansal-mukul** [GoogleCloudPlatform/microservices-demo#2554]

**Comment by NimJay** [comment]
@kansal-mukul, could you please share more details? :)
1. What sort of cluster are you using? GKE? Minikube? etc?
1. Could you share the logs containing your error? (e.g., What does `kubectl get pods` output?)

**Comment by NimJay** [comment]
Closing this issue.
@kansal-mukul, feel free to re-open with more details.

**Comment by kansal-mukul** [comment]
Thanks . i checked . it was working but from my network there is some firewell issue bz of this images was not loaded. Thanks for quick reply @NimJay
