### ISSUE TITLE
Unable to fetch Bootstrap from CDN (ERR_DNS_NO_MATCHING_SUPPORTED_ALPN)

### ISSUE THREAD

**Issue by VOCTERMA** [GoogleCloudPlatform/microservices-demo#2555]
![M 6B_DDP6U63@P48C5K}OQP](https://github.com/GoogleCloudPlatform/microservices-demo/assets/47771073/811eedf7-0fb4-4c88-9743-975caae2bed4)

**Comment by bourgeoisor** [comment]
Hi @VOCTERMA! Would you mind sending in more details? For example:
- How did you deploy Online Boutique (steps / commands you've followed)
- What kind of Kubernetes cluster you've deployed on (GKE, Minikube, etc)
- If you see anything strange in the pods (something not up?) or the logs

**Comment by VOCTERMA** [comment]
> 嗨 ！您介意发送更多详细信息吗？例如：
> 
> * 您是如何部署在线精品店的（您遵循的步骤/命令）
> * 您部署了哪种类型的 Kubernetes 集群（GKE、Minikube 等）
> * 如果你在豆荚或日志中看到任何奇怪的东西（有什么东西没有打开？）或日志

Thank you for your reply. I installed K8S through Kubeadmin and learned through F12 browser debugging that:
![3{7V_ZESY@)R`A%C3`XV 12](https://github.com/GoogleCloudPlatform/microservices-demo/assets/47771073/d5be69fc-9fd5-4467-9eb3-2d45e55cea2e)

But I don't know where to make the modifications, can you tell me

**Comment by bourgeoisor** [comment]
@VOCTERMA The error `ERR_DNS_NO_MATCHING_SUPPORTED_ALPN` suggests that your browser cannot correctly complete the HTTP protocol negotiation with the CDN where Bootstrap is hosted. This could be due to a number of factors, like:
- Firewall or antivirus blocking [bootstrapcdn.com](https://www.bootstrapcdn.com/)
- Outdated or non-supported web browser
- Web browser configuration or plugin interfering

You could start by trying a different web browser and see if you still get this issue.

**Comment by VOCTERMA** [comment]
You're right, I'm trying to modify the URL address in footer.html header.html
![X{L _JYDAV3ORG7SU`{2OJ0](https://github.com/GoogleCloudPlatform/microservices-demo/assets/47771073/4905b6f2-9f7a-42fc-afa6-dcf633a59782)
But when uploading the modified file, it prompts:   Error response from daemon: container rootfs is marked read-only
Do you have a good way to solve this problem? Thank you very much

**Comment by bourgeoisor** [comment]
You would have to modify the files locally (not inside Kubernetes), and then rebuild the images / push them to your Kubernetes cluster using `skaffold run`.

**Comment by VOCTERMA** [comment]
> 您必须在本地（而不是在 Kubernetes 内部）修改文件，然后使用 .`skaffold run`

Thank you again for your reply

**Comment by bourgeoisor** [comment]
No worries! I will close the issue, let me know if you run into issues still.
