### ISSUE TITLE
Cartservice testing

### ISSUE THREAD

**Issue by hegdeph** [GoogleCloudPlatform/microservices-demo#263]
There is a testing project for cartservice. How to run this test as part of Jenkins build ? It throws below error when I execute the test as, 
dotnet test tests/cartservice/cartservice.tests.csproj

Grpc.Core.RpcException : Status(StatusCode=Unavailable, Detail="Connect Failed")

**Comment by ahmetb** [comment]
Please try to debug it. Any help is appreciated.
Tests aren't a supported surface of this repo. And they're developed quite a while ago.

**Comment by DanSanche** [comment]
Closing this and other `kind/improvement` issues as we attempt to move the project into a stable maintenance state
