### ISSUE TITLE
FATA[0018] failed to build: build failed: build failed: building [emailservice]: build artifact: denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by VHariharmath** [GoogleCloudPlatform/microservices-demo#264]
Hello,

I am trying to build this project following the README instruction but the build is failing due to subject line.

I thought the docker login is landing into this issue but it is not. Please help me on this.

`# skaffold run
Generating tags...
 - emailservice -> emailservice:v0.1.2-6-g61dd049
 - productcatalogservice -> productcatalogservice:v0.1.2-6-g61dd049
 - recommendationservice -> recommendationservice:v0.1.2-6-g61dd049
 - shippingservice -> shippingservice:v0.1.2-6-g61dd049
 - checkoutservice -> checkoutservice:v0.1.2-6-g61dd049
 - paymentservice -> paymentservice:v0.1.2-6-g61dd049
 - currencyservice -> currencyservice:v0.1.2-6-g61dd049
 - cartservice -> cartservice:v0.1.2-6-g61dd049
 - frontend -> frontend:v0.1.2-6-g61dd049
 - loadgenerator -> loadgenerator:v0.1.2-6-g61dd049
 - adservice -> adservice:v0.1.2-6-g61dd049
Checking cache...
 - emailservice: Not found. Building
 - productcatalogservice: Not found. Building
 - recommendationservice: Not found. Building
 - shippingservice: Not found. Building
 - checkoutservice: Not found. Building
 - paymentservice: Not found. Building
 - currencyservice: Not found. Building
 - cartservice: Not found. Building
 - frontend: Not found. Building
 - loadgenerator: Not found. Building
 - adservice: Not found. Building
Building [emailservice]...
Sending build context to Docker daemon  101.9kB
Step 1/14 : FROM python:3.7-slim as base
 ---> 07ee12a5eb2a
Step 2/14 : FROM base as builder
 ---> 07ee12a5eb2a
Step 3/14 : RUN apt-get -qq update     && apt-get install -y --no-install-recommends         g++     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> c940a69e2b8a
Step 4/14 : COPY requirements.txt .
 ---> Using cache
 ---> 4c91ed90ed12
Step 5/14 : RUN pip install -r requirements.txt
 ---> Using cache
 ---> f0ef059ebfd0
Step 6/14 : FROM base as final
 ---> 07ee12a5eb2a
Step 7/14 : ENV PYTHONUNBUFFERED=1
 ---> Using cache
 ---> 2346b99ebc5c
Step 8/14 : RUN apt-get -qq update     && apt-get install -y --no-install-recommends         wget
 ---> Using cache
 ---> b97ca7a424c3
Step 9/14 : RUN GRPC_HEALTH_PROBE_VERSION=v0.2.0 &&     wget -qO/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 &&     chmod +x /bin/grpc_health_probe
 ---> Using cache
 ---> caef666cd8d1
Step 10/14 : WORKDIR /email_server
 ---> Using cache
 ---> 5dec2170889d
Step 11/14 : COPY --from=builder /usr/local/lib/python3.7/ /usr/local/lib/python3.7/
 ---> Using cache
 ---> aa541a76bc8d
Step 12/14 : COPY . .
 ---> Using cache
 ---> e1c23568a644
Step 13/14 : EXPOSE 8080
 ---> Using cache
 ---> 29667ea33f9a
Step 14/14 : ENTRYPOINT [ "python", "email_server.py" ]
 ---> Using cache
 ---> e1bc9060878d
Successfully built e1bc9060878d
Successfully tagged emailservice:v0.1.2-6-g61dd049
The push refers to repository [docker.io/library/emailservice]
52f5fd83907a: Preparing
cc6d5da4c076: Preparing
6c7241e23ad6: Preparing
94f9aa4eda86: Preparing
7ee48dfdcc26: Preparing
69e45f0ef9fe: Preparing
807eb5d6d13d: Preparing
ad8ed3d607a6: Preparing
63ca78ed1eaf: Preparing
b67d19e65ef6: Preparing
69e45f0ef9fe: Waiting
807eb5d6d13d: Waiting
ad8ed3d607a6: Waiting
63ca78ed1eaf: Waiting
b67d19e65ef6: Waiting
FATA[0018] failed to build: build failed: build failed: building [emailservice]: build artifact: denied: requested access to the resource is denied `

**Comment by ahmetb** [comment]
You're trying to push image to docker.io/library/emailservice
but you don't own that repo.

Sign in to an actual registry and specify --default_repo as instructed in readme.
