### ISSUE TITLE
Where is the paymentservice API？

### ISSUE THREAD

**Issue by KSGJ-CLOUD** [GoogleCloudPlatform/microservices-demo#2647]
When I click ‘place order’, the API from http://ip/cart redirects to http://ip/cart/checkout, but there is no visible paymentservice API or interface.

![image](https://github.com/user-attachments/assets/53855027-9ca6-476b-b891-e97601f028ad)
![image](https://github.com/user-attachments/assets/280624eb-059f-4a06-b9a1-eca03454f887)

**Comment by bourgeoisor** [comment]
Hi! The paymentservice is called from the checkout service:

https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/src/checkoutservice/main.go#L366-L374

The frontend does not do any calls to the paymentservice, so you wouldn't see an endpoint (from the frontend) to it.

I'll close this issue as resolved, but feel free to comment or reopen if you have follow-up questions.
