### ISSUE TITLE
Adservice build failed

### ISSUE THREAD

**Issue by VStepulo** [GoogleCloudPlatform/microservices-demo#265]
Hi!

I'm new in google cloud but trying to deploy this microservice into GCE.
I've done everything, exactly by instruction, and started build, using the command:

"skaffold run --default-repo=gcr.io/focal-dock-260610"  (my project ID)

But it constantly failing on the adservice step:
[34mBuilding [adservice]...
[0mSending build context to Docker daemon    107kB
Step 1/17 : FROM openjdk:8-slim as builder
 ---> 41fd53971008
Step 2/17 : WORKDIR /app
 ---> Using cache
 ---> f86e643cdf22
Step 3/17 : COPY ["build.gradle", "gradlew", "./"]
 ---> Using cache
 ---> 9dfedc864929
Step 4/17 : COPY gradle gradle
 ---> Using cache
 ---> aadbbe7f17dc
Step 5/17 : RUN chmod +x gradlew
 ---> Using cache
 ---> 9e323897233a
Step 6/17 : RUN ./gradlew downloadRepos
 ---> Running in 9c4d65ef0792
[91m/usr/bin/env: ‘sh\r’: No such file or directory
[0mtime="2019-11-30T15:19:41+02:00" level=fatal msg="failed to build: build failed: build failed: building [adservice]: build artifact: unable to stream build output: The command '/bin/sh -c ./gradlew downloadRepos' returned a non-zero code: 127"

Can anyone help me, why "gradlew downloadRepos" is failing?

**Comment by ahmetb** [comment]
Are you on windows. Looks like a Cloud Run \r character got in there.

**Comment by VStepulo** [comment]
Yes, I'm on Windows, and, I don't know how the issue is dissolved by itself.

**Comment by VStepulo** [comment]
@ahmetb I think, you're right about CR \r. On the first time, when the issue is arise - I cloned repo, using git clone and LF changed to CR LF.
The second time, I used Download zip, and files are being unchanged. In order, to avoid this error on Windows, it is probably, needs to add an additional memo about cloning with "--config core.autocrlf=input"

**Comment by ahmetb** [comment]
Yeah, good point, though I'm hesitant to add yet another notice to the readme, we already have a fair amount of these.

If you're doing anything serious on windows, that should be the default setting you use anyway, and I hope others running into this problem find this page. :)
