### ISSUE TITLE
dev on mac

### ISSUE THREAD

**Issue by linnanwang** [GoogleCloudPlatform/microservices-demo#266]
Hello there,

I'm trying to run the application on my local machine, and I setup docker and kubernetes correctly.

But when I run, skaffold run, I got the following error message:

I'm using python 3.7.3, skaffold v1.0.1. Thank you.

> Listing files to watch...
>  - emailservice
> FATA[0003] watching files for artifact emailservice: listing files: listing files: expanding ONBUILD instructions: parsing ONBUILD instructions: processing base image (python:3.7-slim) for ONBUILD triggers: getting remote config: getting image: unsupported status code 405 
> (base) linnans-imac:microservices-demo linnan$ skaffold run
> Generating tags...
>  - emailservice -> emailservice:v0.1.2-6-g61dd049
>  - productcatalogservice -> productcatalogservice:v0.1.2-6-g61dd049
>  - recommendationservice -> recommendationservice:v0.1.2-6-g61dd049
>  - shippingservice -> shippingservice:v0.1.2-6-g61dd049
>  - checkoutservice -> checkoutservice:v0.1.2-6-g61dd049
>  - paymentservice -> paymentservice:v0.1.2-6-g61dd049
>  - currencyservice -> currencyservice:v0.1.2-6-g61dd049
>  - cartservice -> cartservice:v0.1.2-6-g61dd049
>  - frontend -> frontend:v0.1.2-6-g61dd049
>  - loadgenerator -> loadgenerator:v0.1.2-6-g61dd049
>  - adservice -> adservice:v0.1.2-6-g61dd049
> Checking cache...
>  - emailservice: WARN[0002] error checking cache, caching may not work as expected: getting hash for artifact emailservice: getting dependencies for emailservice: expanding ONBUILD instructions: parsing ONBUILD instructions: processing base image (python:3.7-slim) for ONBUILD triggers: getting remote config: getting image: unsupported status code 405 
> Error checking cache. Rebuilding.
>  - productcatalogservice: WARN[0002] error checking cache, caching may not work as expected: getting hash for artifact productcatalogservice: getting dependencies for productcatalogservice: expanding ONBUILD instructions: parsing ONBUILD instructions: processing base image (golang:1.12-alpine) for ONBUILD triggers: getting remote config: getting image: unsupported status code 405 
> Error checking cache. Rebuilding.
>  - recommendationservice: WARN[0002] error checking cache, caching may not work as expected: getting hash for artifact recommendationservice: getting dependencies for recommendationservice: expanding ONBUILD instructions: parsing ONBUILD instructions: processing base image (python:2.7-slim) for ONBUILD triggers: getting remote config: getting image: unsupported status code 405 
> Error checking cache. Rebuilding.
>  - shippingservice: WARN[0002] error checking cache, caching may not work as expected: getting hash for artifact shippingservice: getting dependencies for shippingservice: expanding ONBUILD instructions: parsing ONBUILD instructions: processing base image (golang:1.12-alpine) for ONBUILD triggers: getting remote config: getting image: unsupported status code 405 
> Error checking cache. Rebuilding.
>  - checkoutservice: WARN[0002] error checking cache, caching may not work as expected: getting hash for artifact checkoutservice: getting dependencies for checkoutservice: expanding ONBUILD instructions: parsing ONBUILD instructions: processing base image (golang:1.12-alpine) for ONBUILD triggers: getting remote config: getting image: unsupported status code 405 
> Error checking cache. Rebuilding.
>  - paymentservice: WARN[0002] error checking cache, caching may not work as expected: getting hash for artifact paymentservice: getting dependencies for paymentservice: expanding ONBUILD instructions: parsing ONBUILD instructions: processing base image (node:8-alpine) for ONBUILD triggers: getting remote config: getting image: unsupported status code 405 
> Error checking cache. Rebuilding.
>  - currencyservice: WARN[0002] error checking cache, caching may not work as expected: getting hash for artifact currencyservice: getting dependencies for currencyservice: expanding ONBUILD instructions: parsing ONBUILD instructions: processing base image (node:8-alpine) for ONBUILD triggers: getting remote config: getting image: unsupported status code 405 
> Error checking cache. Rebuilding.
>  - cartservice: WARN[0002] error checking cache, caching may not work as expected: getting hash for artifact cartservice: getting dependencies for cartservice: expanding ONBUILD instructions: parsing ONBUILD instructions: processing base image (microsoft/dotnet:2.1-sdk-alpine) for ONBUILD triggers: getting remote config: getting image: unsupported status code 405 
> Error checking cache. Rebuilding.
>  - frontend: WARN[0002] error checking cache, caching may not work as expected: getting hash for artifact frontend: getting dependencies for frontend: expanding ONBUILD instructions: parsing ONBUILD instructions: processing base image (golang:1.12-alpine) for ONBUILD triggers: getting remote config: getting image: unsupported status code 405 
> Error checking cache. Rebuilding.
>  - loadgenerator: WARN[0002] error checking cache, caching may not work as expected: getting hash for artifact loadgenerator: getting dependencies for loadgenerator: expanding ONBUILD instructions: parsing ONBUILD instructions: processing base image (python:3-slim) for ONBUILD triggers: getting remote config: getting image: unsupported status code 405 
> Error checking cache. Rebuilding.
>  - adservice: WARN[0002] error checking cache, caching may not work as expected: getting hash for artifact adservice: getting dependencies for adservice: expanding ONBUILD instructions: parsing ONBUILD instructions: processing base image (openjdk:8-slim) for ONBUILD triggers: getting remote config: getting image: unsupported status code 405 
> Error checking cache. Rebuilding.
> Found [docker-desktop] context, using local docker daemon.
> Building [emailservice]...
> Sending build context to Docker daemon 
> 
> FATA[0002] failed to build: build failed: build failed: building [emailservice]: build artifact: docker build: error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/build?buildargs=null&cachefrom=null&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=null&memory=0&memswap=0&networkmode=&rm=0&shmsize=0&t=emailservice%3Av0.1.2-6-g61dd049&target=&ulimits=null&version=: creating docker context: getting relative tar paths: expanding ONBUILD instructions: parsing ONBUILD instructions: processing base image (python:3.7-slim) for ONBUILD triggers: getting remote config: getting image: unsupported status code 405 
>

**Comment by ahmetb** [comment]
Weird. What's your `docker version`?

**Comment by ahmetb** [comment]
Actually this seems to be a skaffold issue
https://github.com/GoogleContainerTools/skaffold/issues/2718

**Comment by linnanwang** [comment]
it is working now. For your record, this is simply due to not signing into the docker. ;)
