### ISSUE TITLE
tracing

### ISSUE THREAD

**Issue by linnanwang** [GoogleCloudPlatform/microservices-demo#267]
Hello there,

Thanks for this awesome package, and I'm able to successfully run it on my local docker. I'm new at this area, and I don't know how to collect traces from hipstar. But it looks like it supports for opencensus, and I tried to list all the services, below is the list, but it looks like opensensus is not running. Could you please advise how to collect traces using opensensus with this system? Thank you. 

> adservice-676bc7474c-5htlg               1/1     Running   0          4h52m
> cartservice-79d94d9965-26fdr             1/1     Running   1          4h52m
> checkoutservice-8cb9f6bd7-z67g7          1/1     Running   0          4h52m
> currencyservice-7746999c89-49bv2         1/1     Running   0          4h52m
> emailservice-8dccfbb97-zmnsb             1/1     Running   0          4h52m
> frontend-59966d8485-t4xjh                1/1     Running   0          4h52m
> loadgenerator-5b7b65c5cf-crphh           1/1     Running   0          4h52m
> paymentservice-7f7d589796-ghdqr          1/1     Running   0          4h52m
> productcatalogservice-d9b5c7956-476fq    1/1     Running   0          4h52m
> recommendationservice-6db998c64d-dgp5n   1/1     Running   0          4h52m
> redis-cart-774766c7df-r5btt              1/1     Running   0          4h52m
> shippingservice-c699664fc-pvmk8          1/1     Running   0          4h52m
>

**Comment by askmeegs** [comment]
Hi Linnan - [OpenCensus](https://opencensus.io/) is a tracing library that you include in your code - it does not run as its own service. OpenCensus standardizes the formatting/sampling of a trace. Then, you configure the service instrumented with OpenCensus with an [exporter](https://opencensus.io/exporters/), such as Stackdriver. That's the tracing backend that actually stores your traces - for Stackdriver, that runs in Google Cloud, not inside your user cluster.
