### ISSUE TITLE
pods crash on aarch64

### ISSUE THREAD

**Issue by aadspinner** [GoogleCloudPlatform/microservices-demo#2688]
### Describe the bug 

I have tried to build each service seperately to run pods on aarch64 oci ec2 (VM.Standard.A1.Flex) with 4 cpu and 10gb ram.) pods crashes.
### To Reproduce 

 sudo docker buildx build --platform linux/aarch64 -t cartservice:latest . --load
sudo docker buildx build --platform linux/aarch64 -t cartservice:latest . --load
  adservice-766c974448-x27c4                 0/1     CrashLoopBackOff        157 (2m38s ago)   13h

### Logs  

exec /app/build/install/hipstershop/bin/AdService: exec format error
### Screenshots 

![Screenshot (1)](https://github.com/user-attachments/assets/2498d349-7c7c-42d2-aed8-13008cd925d6)

### Environment 
 linux ubuntu 22.04 Jammy
 Client Version: v1.30.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.4
  Client: Docker Engine - Community
 Version:           27.1.2
 API version:       1.46
 Go version:        go1.21.13
 Git commit:        d01f264
 Built:             Mon Aug 12 11:53:50 2024
 OS/Arch:           linux/arm64
 Context:           default

**Comment by bourgeoisor** [comment]
`exec format error` means the images are compiled for a different architecture than what is expected. Are you trying to deploy on EKS? Are you sure that the node pool of your Kubernetes cluster is aarch64?

**Comment by aadspinner** [comment]
> `exec format error` means the images are compiled for a different architecture than what is expected. Are you trying to deploy on EKS? Are you sure that the node pool of your Kubernetes cluster is aarch64?

I have tried both builds, arm64 and aarch64 on oci ec2 with this config VM.Standard.A1.Flex. Both formats crashes the pods. Only format runs is amd64, which is runnning like a charm on my aws ec2. Thanks!!

**Comment by bourgeoisor** [comment]
Sounds like your VM is running on amd64 then if that's what works! You'd have to create an arm VM to run arm-based containers, for example. Closing as this sounds like a problem not specific to this repo. Feel free to reopen if there is something strange happening specifically with microservices-demo!
