### ISSUE TITLE
Load generator fails with Istio strict mTLS

### ISSUE THREAD

**Issue by howardjohn** [GoogleCloudPlatform/microservices-demo#269]
The init container is trying to call the frontend before Envoy has started. This will send plaintext traffic, which will fail since the frontend is requiring mTLS traffic only.

**Comment by ahmetb** [comment]
🤔 Hmm we can remove the init container maybe (IIRC it only makes sure frontend comes up), instead maybe we can just fail the requests. That'll show some failures in load generator output, but it'll eventually still send load.

**Comment by howardjohn** [comment]
@ahmetb I would suggest either that or have load gen crashloop until frontend comes up (not sure how feasible that is). That is how `fortio` works as far as I know.

**Comment by ahmetb** [comment]
yeah, we can do something like a liveness probe on the loadgen to curl the frontend.

**Comment by howardjohn** [comment]
I was thinking as part of the code for loadgen. How fortio works (referring to this since I think their solution makes sense here) is that if you do 

`load foo.com`

It will send a single request to `foo.com`. If it fails, it will exit with some exit code. If it passes, it will then send a bunch of load to foo.com and record success/failures.

Either way works though
