### ISSUE TITLE
Multiple frontend services result in pilot warning logs

### ISSUE THREAD

**Issue by howardjohn** [GoogleCloudPlatform/microservices-demo#271]
The deployment installs two services, frontend and frontend-external. Do we need to have two? Can we just have a single load balancer service? 

Otherwise the logs of pilot show

```
        "pilot_conflict_inbound_listener": {
            "frontend-b64f4c9bb-jt4k6.micro": {
                "proxy": "frontend-b64f4c9bb-jt4k6.micro",
                "message": "Conflicting inbound listener:10.28.0.29:8080. existing: frontend-external.micro.svc.cluster.local, incoming: frontend.micro.svc.cluster.local"
            }
        },
```

If there is a good reason to have both, we should explain why -- users presumably are looking at this for best practices, so if we are doing something non-standard it would make sense to explain why possible?

**Comment by ahmetb** [comment]
> Can we just have a single load balancer service?

We already have a single LoadBalancer Service. The other one is an external load balancer for external clients to access. It's required for vanilla GKE installations.

We need the ClusterIP Service for stuff like load generator to work (by resolving http://frontend).

**Comment by howardjohn** [comment]
what I meant was can we have just `frontend-external` (and probably rename it frontend)? Load generator can call http://frontend-external without any issue right?

**Comment by ahmetb** [comment]
I'm actually not sure if this would work smoothly, as we now go through potentially public internet. Also this would probably break someone. I'd say unless it's necessary, let's not do this. (I'm not sure why the pilot logs are showing something wrong here.)

**Comment by ahmetb** [comment]
Actually I recalled the reason:

> can we have just `frontend-external` (and probably rename it frontend)?

This won't work since many Kubernetes distributions do not have support for Service type=LoadBalancer (minikube, on-prem, private GKE...). We still want the deployment to work for those.

**Comment by howardjohn** [comment]
Does http://frontend-external/ really go through the open internet? My understanding is it's using the internal cluster IP. For that same reason minikube still works.

I would have to double check this but I believe this is how it works since I test istio Ingress without a load balancer often. It works fine, just the external IP address stays pending

**Comment by ahmetb** [comment]
At any rate, when we delete something, we’ll most likely break someone downstream. There are 1st party scripts that rely on this, too. Unless critical and required, I’m hesitant.
