### ISSUE TITLE
Can anyone tell me which application architecture is used for the services? Like MVC, MVP or MVVM?

### ISSUE THREAD

**Issue by cyantarek** [GoogleCloudPlatform/microservices-demo#278]
I'm learning about gRPC and application architecture and architectural patterns.

Now I want to know which architectural pattern is used for services in this demo? Like MVC, MVP, MVVM is used in web app and android development.

It would be helpful for me. Thanks.

**Comment by ahmetb** [comment]
Most of those don’t apply as we don’t operate on real data. Please inspect the source code and the architecture diagram in README.
