### ISSUE TITLE
update loadgenerator to be able to connect to external IP (with HTTPS)

### ISSUE THREAD

**Issue by prune998** [GoogleCloudPlatform/microservices-demo#285]
For the moment the `loadgenerator` connect to `frontend:80`, the local service which is taken from the `FRONTEND_ADDR` env var.

As a testing purpose, we would like to be able to also test: 
- sending load to an external IP
- sending load to an external IP + an ingress gateway, maybe using HTTPS

While testing it, I saw two changed to be made : 
- update locust config (locustfile.py) to allow unsecure certificates (self signed:
```
class UserBehavior(TaskSet):

    def on_start(self):
        self.client.verify = False
        index(self)
```

- updating loadgen.sh to take a full URL instead of <host>:<port>, plit it up and add needed config if using SSL: 
```
# split the FRONTEND_ADDR
pattern='^(([[:alnum:]]+)://)?(([[:alnum:]]+)@)?([^:^@]+)(:([[:digit:]]+))?$'
if [[ "${FRONTEND_ADDR}" =~ $pattern ]]; then
        proto=${BASH_REMATCH[2]}
        user=${BASH_REMATCH[4]}
        host=${BASH_REMATCH[5]}
        port=${BASH_REMATCH[7]}
else
    echo >&2 "FRONTEND_ADDR should be an URL: <http/s>:<user>@<host>:<port>"
    exit 1
fi

SNI_OPTS=""

if [[ -n "${FRONTEND_IP}" ]]; then

    # set the resolution in the host file
    echo "${FRONTEND_IP}  ${host}" >> /etc/hosts

    ## also tell curl to resolve the IP
    SNI_OPTS="--resolve ${host}:${port}:${FRONTEND_IP}"
fi

# if one request to the frontend fails, then exit
STATUSCODE=$(curl -sk -o /dev/null --write-out "%{http_code}" ${SNI_OPTS} ${FRONTEND_ADDR})
```

This will work as long as the pod is run as root (default) and we can write to /etc/hosts in it.
I did not found any other way of configuring locust to support SNI.

I can PR if you think it's a good addition.

**Comment by ahmetb** [comment]
We prefer not to introduce any new code branches for maintenance reasons. Feel free to fork and adapt to your changes.
