### ISSUE TITLE
adservice image faild if you want to build from root directory

### ISSUE THREAD

**Issue by danielyaghini** [GoogleCloudPlatform/microservices-demo#292]
in the adservice folder would be described:
to build the docker image
From the repository root, run:
docker build --file src/adservice/Dockerfile .

but it caus the following error:
Step 3/17 : COPY ["build.gradle", "gradlew", "./"]
COPY failed: stat /var/lib/docker/tmp/docker-builder288251425/build.gradle: no such file or directory

**Comment by ahmetb** [comment]
What OS are you building on?

**Comment by danielyaghini** [comment]
with Github action runs-on: ubuntu-latest

**Comment by ahmetb** [comment]
@DanSanche has our GH Workflows worked so far? It seems like the hosted worker is not working.

**Comment by danielyaghini** [comment]
hier my workflow unter github action:
`
name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --file src/adservice/Dockerfile .`

can you see if you can reproduce the error?

**Comment by danielyaghini** [comment]
Here is my workflow under the github action:
`
name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --file src/adservice/Dockerfile .
`

cloud you check if you can reproduce the error?

**Comment by DanSanche** [comment]
@ahmetb GitHub actions haven't been enabled for the repo yet. This is separate from that branch

It looks like the adservice README instructs you to build the container from the repo root, but the Dockerfile expects you to build it from the src/adservice directory. Is there any reason we'd want to build the Dockerfile from the root? That seems unnecessarily. I think we should just update the README

@danielyaghini it should work if you just use `docker build --file src/adservice/Dockerfile src/adservice` instead

**Comment by DanSanche** [comment]
closing this since we updated the README to build from `src/adservice`
