### ISSUE TITLE
Public URL no longer serving

### ISSUE THREAD

**Issue by kintel** [GoogleCloudPlatform/microservices-demo#294]
The public URL (http://35.238.163.103) is no longer serving traffic. Has this been moved to a new IP address?

**Comment by ahmetb** [comment]
@DanSanche you should have access to `microservices-demo-app` project, can you please take a look?

**Comment by ahmetb** [comment]
It seems like the workloads are somehow deleted from the cluster (but svcs are there). Just need to apply the release YAML.

**Comment by DanSanche** [comment]
It looks like an istio certificate error. I'll take a look soon

**Comment by ahmetb** [comment]
@DanSanche last time I checked there wasn't simply any deployments in the cluster. It would be good to get this endpoint up and running soon, since the repo is highly visible.

**Comment by DanSanche** [comment]
The problem was the istio-ca-secret root certificate expired on Jan 11, 2020. I used [this guide](https://istio.io/docs/ops/configuration/security/root-transition/) to extend the expiry to 2030. It's back up now
