### ISSUE TITLE
Local Setup -RPC Error

### ISSUE THREAD

**Issue by aashishk7** [GoogleCloudPlatform/microservices-demo#301]
I have setup the application on local. While using the same , I am getting below error :
rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 10.98.35.74:8080: connect: connection refused

**Comment by aashishk7** [comment]
This is the pod status i have :
Have tried deleting CrashLoopBackOff once , but not helping

NAME                                     READY   STATUS             RESTARTS   AGE
adservice-8578bd558d-pvwsp               1/1     Running            0          29s
cartservice-5497c98c86-nkrv4             1/1     Running            0          15m
checkoutservice-59944c85bb-t5ktd         1/1     Running            0          15m
currencyservice-6bf785ccf8-2gdp2         1/1     Running            0          15m
emailservice-5dbc4d6485-6q4bt            0/1     CrashLoopBackOff   4          2m57s
emailservice-7898667ddf-twmv4            0/1     CrashLoopBackOff   5          2m57s
frontend-5dc8df5c75-fg2fm                1/1     Running            0          15m
loadgenerator-6c7f574fc9-bcwnl           1/1     Running            2          15m
paymentservice-77cb775498-c8d7k          1/1     Running            0          15m
productcatalogservice-5546ff9dfb-5xfwl   1/1     Running            0          15m
recommendationservice-587f569678-77tw5   0/1     Running            5          2m57s
recommendationservice-68b68467bb-8r5vn   0/1     CrashLoopBackOff   4          2m57s
redis-cart-5c659c7c94-dzt4z              1/1     Running            0          15m
shippingservice-859846698-nckff          1/1     Running            0          15m

**Comment by aashishk7** [comment]
This emailservice and recommendationservice pods are not coming up , please suggest the solution @broady @chingor13 @rakyll @alpire

**Comment by ahmetb** [comment]
Hello, you don’t need to @ everyone to gather attention. Those who maintain the repo get issue notifications.

**Comment by aashishk7** [comment]
> Hello, you don’t need to @ everyone to gather attention. Those who maintain the repo get issue notifications.

**Comment by ahmetb** [comment]
Please send `kubectl logs` and `kubectl describe` from those crashlooping pods.

**Comment by aashishk7** [comment]
Below is the logs for **email service** crashing when i am trying to set up on Local 

Logs
kubectl logs emailservice-ffd45c8c8-gnlxn
{"timestamp": 1582922497.308961, "severity": "INFO", "name": "emailservice-server", "message": "starting the email service in dummy mode."}
{"timestamp": 1582922497.30913, "severity": "INFO", "name": "emailservice-server", "message": "Profiler disabled."}
{"timestamp": 1582922497.3091836, "severity": "INFO", "name": "emailservice-server", "message": "Tracing enabled."}
Traceback (most recent call last):
  File "email_server.py", line 190, in <module>
    transport=AsyncTransport)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 199, in __init__
    client = Client(project=project_id)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace/client.py", line 43, in __init__
    super(Client, self).__init__(project=project, credentials=credentials)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/client.py", line 223, in __init__
    _ClientProjectMixin.__init__(self, project=project)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/client.py", line 175, in __init__
    project = self._determine_default(project)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/client.py", line 190, in _determine_default
    return _determine_default_project(project)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/_helpers.py", line 186, in _determine_default_project
    _, project = google.auth.default()
  File "/usr/local/lib/python3.7/site-packages/google/auth/_default.py", line 306, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started

Describe
Name:           emailservice-ffd45c8c8-gnlxn
Namespace:      default
Priority:       0
Node:           docker-desktop/192.168.65.3
Start Time:     Sat, 29 Feb 2020 01:44:34 +0530
Labels:         app=emailservice
                app.kubernetes.io/managed-by=skaffold-v1.4.0
                pod-template-hash=ffd45c8c8
                skaffold.dev/builder=local
                skaffold.dev/cleanup=true
                skaffold.dev/deployer=kubectl
                skaffold.dev/docker-api-version=1.40
                skaffold.dev/run-id=8ceabe32-80b5-46ff-9a1f-2f064a6c466b
                skaffold.dev/tag-policy=git-commit
                skaffold.dev/tail=true
Annotations:    <none>
Status:         Running
IP:             10.1.0.237
Controlled By:  ReplicaSet/emailservice-ffd45c8c8
Containers:
  server:
    Container ID:   docker://bca4ea207253f57067271f109b759b6d5fafb1dea254be5e78fe46fbc95a2c55
    Image:          emailservice:5ea900dc770cd1964ddff60fd34b31bc5b81d0362b90fa78ca6e6bfed7227cd5
    Image ID:       docker://sha256:5ea900dc770cd1964ddff60fd34b31bc5b81d0362b90fa78ca6e6bfed7227cd5
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sat, 29 Feb 2020 02:16:49 +0530
      Finished:     Sat, 29 Feb 2020 02:16:54 +0530
    Ready:          False
    Restart Count:  13
    Limits:
      cpu:     200m
      memory:  128Mi
    Requests:
      cpu:      100m
      memory:   64Mi
    Liveness:   exec [/bin/grpc_health_probe -addr=:8080] delay=0s timeout=1s period=5s #success=1 #failure=3
    Readiness:  exec [/bin/grpc_health_probe -addr=:8080] delay=0s timeout=1s period=5s #success=1 #failure=3
    Environment:
      PORT:              8080
      DISABLE_PROFILER:  1
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lz7qb (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  default-token-lz7qb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-lz7qb
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From                     Message
  ----     ------     ----                   ----                     -------
  Normal   Scheduled  33m                    default-scheduler        Successfully assigned default/emailservice-ffd45c8c8-gnlxn to docker-desktop
  Warning  Unhealthy  33m                    kubelet, docker-desktop  Readiness probe failed: timeout: failed to connect service ":8080" within 1s
  Warning  Unhealthy  33m                    kubelet, docker-desktop  Liveness probe failed:
  Warning  Unhealthy  33m (x2 over 33m)      kubelet, docker-desktop  Readiness probe failed:
  Warning  Unhealthy  33m                    kubelet, docker-desktop  Liveness probe errored: rpc error: code = Unknown desc = container not running (b721d20a5b170876f03ac69352442cb81f5eddf9596dab48ca55006b080d1b91)
  Normal   Pulled     32m (x4 over 33m)      kubelet, docker-desktop  Container image "emailservice:5ea900dc770cd1964ddff60fd34b31bc5b81d0362b90fa78ca6e6bfed7227cd5" already present on machine
  Normal   Created    32m (x4 over 33m)      kubelet, docker-desktop  Created container server
  Normal   Started    32m (x4 over 33m)      kubelet, docker-desktop  Started container server
  Warning  Unhealthy  32m (x2 over 33m)      kubelet, docker-desktop  Liveness probe failed: timeout: failed to connect service ":8080" within 1s
  Normal   Killing    32m                    kubelet, docker-desktop  Container server failed liveness probe, will be restarted
  Warning  BackOff    3m43s (x143 over 33m)  kubelet, docker-desktop  Back-off restarting failed container

**Comment by tec-web** [comment]
Yeah, I am getting same issue with same pods emailservice & recommendationservice.

File "/usr/local/lib/python3.7/site-packages/google/auth/_default.py", line 306, in default         raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)                                       google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Pl ease set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the applicati on. For more information, please see https://cloud.google.com/docs/authentication/getting-started
--

Windows 10 Pro, Docker Desktop 2.2.03 Engine 19.03.5 Compose 1.25.4, Kubernetes v1.15.5

**Comment by ahmetb** [comment]
Note: before pasting output, please select the comment and press the `<>` button in the comment editor.

**Comment by aashishk7** [comment]
`kubectl logs emailservice-ffd45c8c8-gnlxn
{"timestamp": 1582922497.308961, "severity": "INFO", "name": "emailservice-server", "message": "starting the email service in dummy mode."}
{"timestamp": 1582922497.30913, "severity": "INFO", "name": "emailservice-server", "message": "Profiler disabled."}
{"timestamp": 1582922497.3091836, "severity": "INFO", "name": "emailservice-server", "message": "Tracing enabled."}
Traceback (most recent call last):
File "email_server.py", line 190, in
transport=AsyncTransport)
File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 199, in init
client = Client(project=project_id)
File "/usr/local/lib/python3.7/site-packages/google/cloud/trace/client.py", line 43, in init
super(Client, self).init(project=project, credentials=credentials)
File "/usr/local/lib/python3.7/site-packages/google/cloud/client.py", line 223, in init
_ClientProjectMixin.init(self, project=project)
File "/usr/local/lib/python3.7/site-packages/google/cloud/client.py", line 175, in init
project = self._determine_default(project)
File "/usr/local/lib/python3.7/site-packages/google/cloud/client.py", line 190, in _determine_default
return _determine_default_project(project)
File "/usr/local/lib/python3.7/site-packages/google/cloud/_helpers.py", line 186, in _determine_default_project
_, project = google.auth.default()
File "/usr/local/lib/python3.7/site-packages/google/auth/_default.py", line 306, in default
raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started`

**Comment by aashishk7** [comment]
`Name: emailservice-ffd45c8c8-gnlxn
Namespace: default
Priority: 0
Node: docker-desktop/192.168.65.3
Start Time: Sat, 29 Feb 2020 01:44:34 +0530
Labels: app=emailservice
app.kubernetes.io/managed-by=skaffold-v1.4.0
pod-template-hash=ffd45c8c8
skaffold.dev/builder=local
skaffold.dev/cleanup=true
skaffold.dev/deployer=kubectl
skaffold.dev/docker-api-version=1.40
skaffold.dev/run-id=8ceabe32-80b5-46ff-9a1f-2f064a6c466b
skaffold.dev/tag-policy=git-commit
skaffold.dev/tail=true
Annotations:
Status: Running
IP: 10.1.0.237
Controlled By: ReplicaSet/emailservice-ffd45c8c8
Containers:
server:
Container ID: docker://bca4ea207253f57067271f109b759b6d5fafb1dea254be5e78fe46fbc95a2c55
Image: emailservice:5ea900dc770cd1964ddff60fd34b31bc5b81d0362b90fa78ca6e6bfed7227cd5
Image ID: docker://sha256:5ea900dc770cd1964ddff60fd34b31bc5b81d0362b90fa78ca6e6bfed7227cd5
Port: 8080/TCP
Host Port: 0/TCP
State: Waiting
Reason: CrashLoopBackOff
Last State: Terminated
Reason: Error
Exit Code: 1
Started: Sat, 29 Feb 2020 02:16:49 +0530
Finished: Sat, 29 Feb 2020 02:16:54 +0530
Ready: False
Restart Count: 13
Limits:
cpu: 200m
memory: 128Mi
Requests:
cpu: 100m
memory: 64Mi
Liveness: exec [/bin/grpc_health_probe -addr=:8080] delay=0s timeout=1s period=5s #success=1 #failure=3
Readiness: exec [/bin/grpc_health_probe -addr=:8080] delay=0s timeout=1s period=5s #success=1 #failure=3
Environment:
PORT: 8080
DISABLE_PROFILER: 1
Mounts:
/var/run/secrets/kubernetes.io/serviceaccount from default-token-lz7qb (ro)
Conditions:
Type Status
Initialized True
Ready False
ContainersReady False
PodScheduled True
Volumes:
default-token-lz7qb:
Type: Secret (a volume populated by a Secret)
SecretName: default-token-lz7qb
Optional: false
QoS Class: Burstable
Node-Selectors:
Tolerations: node.kubernetes.io/not-ready:NoExecute for 300s
node.kubernetes.io/unreachable:NoExecute for 300s
Events:
Type Reason Age From Message

Normal Scheduled 33m default-scheduler Successfully assigned default/emailservice-ffd45c8c8-gnlxn to docker-desktop
Warning Unhealthy 33m kubelet, docker-desktop Readiness probe failed: timeout: failed to connect service ":8080" within 1s
Warning Unhealthy 33m kubelet, docker-desktop Liveness probe failed:
Warning Unhealthy 33m (x2 over 33m) kubelet, docker-desktop Readiness probe failed:
Warning Unhealthy 33m kubelet, docker-desktop Liveness probe errored: rpc error: code = Unknown desc = container not running (b721d20a5b170876f03ac69352442cb81f5eddf9596dab48ca55006b080d1b91)
Normal Pulled 32m (x4 over 33m) kubelet, docker-desktop Container image "emailservice:5ea900dc770cd1964ddff60fd34b31bc5b81d0362b90fa78ca6e6bfed7227cd5" already present on machine
Normal Created 32m (x4 over 33m) kubelet, docker-desktop Created container server
Normal Started 32m (x4 over 33m) kubelet, docker-desktop Started container server
Warning Unhealthy 32m (x2 over 33m) kubelet, docker-desktop Liveness probe failed: timeout: failed to connect service ":8080" within 1s
Normal Killing 32m kubelet, docker-desktop Container server failed liveness probe, will be restarted
Warning BackOff 3m43s (x143 over 33m) kubelet, docker-desktop Back-off restarting failed container`

**Comment by mtoslalibu** [comment]
I have the same issue. Recommendation service fails when it tries to authenticate to stackdriver. And I wonder why connecting to tracing service is in the critical path? Could someone help me?

**Comment by Sarang-Sangram** [comment]
If you guys have the K8 setup locally and  getting error in the log file which is referring to `google.auth.exceptions.DefaultCredentialsError` then you have to enable below environment variables which are commented out by default :
```
        - name: DISABLE_STATS
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
```
You should be able to edit the deployment or just clean everything and trigger a new setup.

**Comment by ahmetb** [comment]
@Sarang-Sangram good point!

We should still keep this open, as it is intended to work out-of-the-box locally as well as on GKe.

**Comment by pandasauce** [comment]
@Sarang-Sangram's solution doesn't seem to help:

```
$ kubectl logs emailservice-76f7b8cb47-2wxfp
{"timestamp": 1584963628.6182392, "severity": "INFO", "name": "emailservice-server", "message": "starting the email service in dummy mode."}
{"timestamp": 1584963628.618482, "severity": "INFO", "name": "emailservice-server", "message": "Profiler disabled."}
{"timestamp": 1584963628.6185439, "severity": "INFO", "name": "emailservice-server", "message": "Tracing enabled."}
Traceback (most recent call last):
  File "email_server.py", line 190, in <module>
    transport=AsyncTransport)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 199, in __init__
    client = Client(project=project_id)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace/client.py", line 43, in __init__
    super(Client, self).__init__(project=project, credentials=credentials)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/client.py", line 223, in __init__
    _ClientProjectMixin.__init__(self, project=project)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/client.py", line 175, in __init__
    project = self._determine_default(project)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/client.py", line 190, in _determine_default
    return _determine_default_project(project)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/_helpers.py", line 186, in _determine_default_project
    _, project = google.auth.default()
  File "/usr/local/lib/python3.7/site-packages/google/auth/_default.py", line 306, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
```

**Comment by DanSanche** [comment]
This issue should be fixed in https://github.com/GoogleCloudPlatform/microservices-demo/pull/318
