### ISSUE TITLE
Some of the pods are in crashLoopBackOff mode - Readiness/Liveness Probe failure

### ISSUE THREAD

**Issue by lordcf** [GoogleCloudPlatform/microservices-demo#302]
Hi I have deployed this app on local kubernetes cluster which is istio enabled.
While deploying the Hipster app some of the pods of services like Currency, Email, Load Generator and Recommendation service are going into CrashLoopBackOff state.
Below is the screenshot: 
![image](https://user-images.githubusercontent.com/25821409/76059506-0a94fc00-5fa5-11ea-92a8-a3549be0e501.png)

On describing the container it is showing the error as :
![2](https://user-images.githubusercontent.com/25821409/76060136-9e1afc80-5fa6-11ea-82dc-921b5c00eb43.PNG)

Kindly let me know how should I proceed.

**Comment by Sarang-Sangram** [comment]
Check the pod logs , if its referring something like `google.auth.exceptions.DefaultCredentialsError` then you have to enable below environment variables which are commented out by default ( This works in GCP , but since you deploying it in your local K8 cluster , hence it couldn't find the google auth creds )  :
```       
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
```

Also you might want to increase the timeout values for the probes.

**Comment by lordcf** [comment]
@Sarang-Sangram Thankyou for your reply.
 i tried enabling the environment variables suggested by you , after that email and recommendation services are in running state but currency , load generator and payment are still failing even after increasing  the timeout values for the probes.
![63508462](https://user-images.githubusercontent.com/25821409/76186727-445e4080-61f9-11ea-85b7-622a71117b5f.PNG)
![779F9C6D](https://user-images.githubusercontent.com/25821409/76186789-7e2f4700-61f9-11ea-9b9f-157096eda0fa.PNG)
![BA2B17C7](https://user-images.githubusercontent.com/25821409/76186796-81c2ce00-61f9-11ea-9b57-53e9c98f9d9e.PNG)

**Comment by Sarang-Sangram** [comment]
@lordcf From the log you shared seems like the specific service is trying to connect to the frontend service. Did you do a `nodeport` for the frontend service ?

**Comment by lordcf** [comment]
@Sarang-Sangram frontend service is of type cluster-IP only. I am using the exact same deployment as is in this repo.

**Comment by ahmetb** [comment]
Can you please share logs or `kubectl describe` output from the crashing pods?

I think this is worth investigating, I suspect it's similar to some of the ongoing issues.

**Comment by danielcgithub** [comment]
Hi @ahmetb 
I am having the same issue.  

```
 kubectl get pods
NAME                                     READY   STATUS             RESTARTS   AGE
adservice-8579b8b596-cwhcg               1/1     Running            0          4m23s
cartservice-5c97c6dc76-gt2p5             1/1     Running            1          4m23s
checkoutservice-5b694559-s4kwn           1/1     Running            0          4m23s
currencyservice-655fbc4677-9mb79         1/1     Running            0          4m23s
emailservice-584c5c6956-4f8n2            0/1     CrashLoopBackOff   5          4m23s
frontend-7fd846559d-f2chx                1/1     Running            0          4m23s
loadgenerator-64966896f4-xz5g6           1/1     Running            3          4m23s
paymentservice-7b89944f77-vbmr6          1/1     Running            0          4m23s
productcatalogservice-7df6fc7855-4crvz   1/1     Running            0          4m23s
recommendationservice-55477b8bcc-4894j   0/1     CrashLoopBackOff   6          4m23s
redis-cart-867496bb66-j22kx              1/1     Running            0          4m23s
shippingservice-c6955b8dc-smk2v          1/1     Running            0          4m22s
```

Here is 
1. describe of the email service: [emailservdescribe.log](https://github.com/GoogleCloudPlatform/microservices-demo/files/4365124/emailservdescribe.log)
2. logs of email service: [emailservice.log](https://github.com/GoogleCloudPlatform/microservices-demo/files/4365127/emailservice.log)
3. describe of recommendation service: [recservicedescribe.log](https://github.com/GoogleCloudPlatform/microservices-demo/files/4365132/recservicedescribe.log)
4. logs of recommendation service: [recommendationservice.log](https://github.com/GoogleCloudPlatform/microservices-demo/files/4365134/recommendationservice.log)

**Comment by DanSanche** [comment]
The emailservice and recommendationservice should be fixed on master. If you're able to share the logs for the other services, I'll investigate

**Comment by anilreddyv** [comment]
for on-prem cluster 

+ kubectl logs -f currencyservice-7b47ccdfd4-brg5h
Profiler enabled.
Tracing enabled.
@google-cloud/trace-agent ERROR StackdriverTracer#start: Tracing might not work as the following modules were loaded before the trace agent was initialized: [@google-cloud/common, @google-cloud/profiler, @google-cloud/projectify, @google-cloud/promisify, @protobufjs/aspromise, @protobufjs/base64, @protobufjs/eventemitter, @protobufjs/float, @protobufjs/inquire, @protobufjs/pool, @protobufjs/utf8, abbrev, agent-base, ansi-regex, aproba, are-we-there-yet, arrify, balanced-match, base64-js, bignumber.js, brace-expansion, buffer-equal-constant-time, code-point-at, concat-map, console-control-strings, console-log-level, core-util-is, debug, delay, delegates, detect-libc, duplexify, ecdsa-sig-formatter, end-of-stream, ent, es6-promisify, extend, findit2, fs.realpath, gauge, gaxios, gcp-metadata, glob, google-auth-library, gtoken, has-unicode, https-proxy-agent, inflight, inherits, is-fullwidth-code-point, isarray, json-bigint, jwa, jws, long, lru# Please edit the object below. Lines beginning with a '#' will be ignored,
-cache, mime, minimatch, ms, node-fetch, node-pre-gyp, nopt, npmlog, number-is-nan, object-assign, once, os-homedir, os-tmpdir, osenv, p-limit, p-try, parse-duration, parse-ms, path-is-absolute, pify, pprof, pretty-ms, process-nextick-args, protobufjs, readable-stream, retry-request, rimraf, safe-buffer, semver, set-blocking, signal-exit, source-map, split, stream-shift, string-width, strip-ansi, teeny-request, through, through2, util-deprecate, uuid, wide-align, wrappy, yallist]
Debugger enabled.
{"severity":"info","time":1609803660706,"message":"Starting gRPC server on port 7000...","pid":1,"hostname":"currencyservice-7b47ccdfd4-brg5h","name":"currencyservice-server","v":1}
➜  microservices-demo git:(master) ✗ vi kubernetes-manifests/currencyservice.yaml

**Comment by minhdang241** [comment]
> Check the pod logs , if its referring something like `google.auth.exceptions.DefaultCredentialsError` then you have to enable below environment variables which are commented out by default ( This works in GCP , but since you deploying it in your local K8 cluster , hence it couldn't find the google auth creds ) :
> 
> ```
>         - name: DISABLE_TRACING
>           value: "1"
>         - name: DISABLE_PROFILER
>           value: "1"
> ```
> 
> Also you might want to increase the timeout values for the probes.

it solved the problem. Thank you very much!!!
