### ISSUE TITLE
Rebrand app with Online Boutique store branding

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#306]
This helps Google not maintain forks of this repo. Right now, Anthos Codelab depends on Online Boutique –which is deployed via fork of a fork of a fork of a fork of this repo –which isn't ideal.

As far as I see, this involves refactoring frontend + changing some strings. There might be several other microservice changes that I'm hoping are trivial that we don't have to go out of our way too much.

cc: @subfuzion @DanSanche @askmeegs

**Comment by Daniel-Sanche** [comment]
@ahmetb  Do you know who maintains the online boutique fork? I'm having trouble finding anything other than the pre-built images

**Comment by subfuzion** [comment]
@Daniel-Sanche Right now codelab uses [my specific fork](https://github.com/subfuzion/onlineboutique) for the ACM config (which I want to offload) and @askmeegs has the app fork.

**Comment by Daniel-Sanche** [comment]
Ok great, I'll discuss it with Megan when she gets back. Thanks!

**Comment by askmeegs** [comment]
I can take this! Source code for the two forked services (productcatalog and frontend) lives in Cloud Source Repo that I took on ownership for, a few months back.
