### ISSUE TITLE
Run on kind

### ISSUE THREAD

**Issue by yashbhutwala** [GoogleCloudPlatform/microservices-demo#308]
- [ ] add docs to run on kind
- [x] fix https://github.com/GoogleCloudPlatform/microservices-demo/issues/301#issuecomment-593782772

**Comment by ahmetb** [comment]
Hello, can you explain some background here? Was there a request to run this on kind?

**Comment by Daniel-Sanche** [comment]
@yashbhutwala I added some instructions [here](https://github.com/GoogleCloudPlatform/microservices-demo/compare/kind-instructions?expand=1). Let me know what you think
