### ISSUE TITLE
Fork issue into building checkoutservice

### ISSUE THREAD

**Issue by benaichouchem** [GoogleCloudPlatform/microservices-demo#309]
Hi Team, I forked this repo, and then I changed some references for the file from **/github.com/GoogleCloudPlatform/microservices-demo/..**. to **/github/benaichouchem/microservices-demo** and now I can't seem to build checkoutservice, always getting this error:

`vendor/github.com/benaichouchem/microservices-demo/src/checkoutservice/money/money.go:20:2: cannot find package "github.com/GoogleCloudPlatform/microservices-demo/src/checkoutservice/genproto" in any of:
`
I have been trying to figure this out for the last 2 days, any help is appreciated

**Comment by ahmetb** [comment]
Your question is mostly about Godep. I suspect we won't be able to find time to help with that.

If you change all strings properly, you shouldn't be seeing `GoogleCloudPlatform` in the output –so there's that.

**Comment by benaichouchem** [comment]
I have scanned the project several times, there is no mention of GoogleCloudPlatform in my working area at all. I deleted some references from the Gopkg.lock, seems to build. Not sure if it the digest code that is still referencing something in the original repo.

**Comment by ahmetb** [comment]
> Not sure if it the digest code that is still referencing something in the original repo.

I don't know what the digest code is. I don't edit godep files from scratch. I recommend you nuke Gopkg files and try again to create them (or not, if not needed).

**Comment by benaichouchem** [comment]
yeah that's what seems to work. Thanks for your help.
