### ISSUE TITLE
Add SLOs to microservices-demo

### ISSUE THREAD

**Issue by ocervell** [GoogleCloudPlatform/microservices-demo#320]
Now that Service Level Objectives are [available](https://cloud.google.com/monitoring/service-monitoring) in Stackdriver, it would be awesome to have a couple SLOs defined for this app.

**Comment by jkohen** [comment]
This app uses Istio, and Stackdriver has Istio integration for SLIs. Is that what you're looking for? Caveat: I haven't tested it myself.

**Comment by ocervell** [comment]
Let's add some instructions to the README to show the awesome SLO dashboards that we can do then ;)

**Comment by ahmetb** [comment]
This content likely belongs to an external tutorial/codelab that uses this repo. So I recommend tracking it externally, unless there’s a clean way of declaratively configuring SLOs/alerts vis files we can check in here.

**Comment by Daniel-Sanche** [comment]
Closing, but feel free to re-open if you want to discuss this further
