### ISSUE TITLE
Currency conversion after checkout results in HTTP 405

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/microservices-demo#333]
If you click "place order" in the UI with items in your cart, and the success page shows up, then from that success page, try to convert the currency in the top-right, I see an HTTP 405 error.

Solution - make sure the order success page handlers + HTML template are configured to support currency conversion

**Comment by ahmetb** [comment]
> Solution - make sure the order success page handlers + HTML template are configured to support currency conversion

I think this is happening because when you change currency, you get redirected to `/cart/checkout` but with a `GET` request. However that endpoint does not support `GET`. 

I think the best option would be to hide the currency conversion form on this page through a template variable.
