### ISSUE TITLE
Optimize screenshot PNGs in readme

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#339]
I actually saw this in code review but then I noticed the old PNGs were also around 1-2 MB.  Probably a little room for improvement if we pass these to online PNG optimizers. It seems like the main issue is that the resolution is simply too large.

**Comment by TPS** [comment]
#379 implements this, pending CLA approval.

**Comment by TPS** [comment]
@ahmetb Now that #379 is implemented, close FTW?
