### ISSUE TITLE
Skaffold fails on GKE (option 2) at step 4

### ISSUE THREAD

**Issue by palladius** [GoogleCloudPlatform/microservices-demo#340]
I'm following option 2. Stage 1,2,3 work perfectly.
Stage 4, skaffold FAILS. Note that docker works and git is in /usr/bin so error messages seem weird.

----------
$ skaffold version
v0.25.0

# doing all install steps, keeping output only of the last which was good.
[..]

$ gcloud auth configure-docker -q
ARNING: Your config file at [/home/riccardo/.docker/config.json] contains these credential helper entries:

{
  "credHelpers": {
    "us.gcr.io": "gcloud", 
    "staging-k8s.gcr.io": "gcloud", 
    "asia.gcr.io": "gcloud", 
    "gcr.io": "gcloud", 
    "marketplace.gcr.io": "gcloud", 
    "eu.gcr.io": "gcloud"
  }
}
Adding credentials for all GCR repositories.
WARNING: A long list of credential helpers may cause delays running 'docker build'. We recommend passing the registry name to configure only the registry you are using.
gcloud credential helpers already registered correctly.

$ skaffold run --default-repo="gcr.io/825862901243"
WARN[0000] config version (skaffold/v1beta2) out of date: upgrading to latest (skaffold/v1beta7) 
Generating tags...
 - gcr.io/825862901243/emailservice -> WARN[0000] Unable to find git commit: starting command &{git [git rev-parse --short HEAD] [] src/emailservice <nil> 0xc0005c4158 0xc0005c4168 [] <nil> <nil> <nil> <nil> 0xc000261b40 false [] [0xc0005c4158 0xc0005c4168] [0xc0005c4150 0xc0005c4160] [] <nil> <nil>}: exec: "git": executable file not found in $PATH 
gcr.io/825862901243/emailservice:dirty
 - gcr.io/825862901243/productcatalogservice -> WARN[0000] Unable to find git commit: starting command &{git [git rev-parse --short HEAD] [] src/productcatalogservice <nil> 0xc0005c4178 0xc0005c4188 [] <nil> <nil> <nil> <nil> 0xc000261ca0 false [] [0xc0005c4178 0xc0005c4188] [0xc0005c4170 0xc0005c4180] [] <nil> <nil>}: exec: "git": executable file not found in $PATH 
gcr.io/825862901243/productcatalogservice:dirty
 - gcr.io/825862901243/recommendationservice -> WARN[0000] Unable to find git commit: starting command &{git [git rev-parse --short HEAD] [] src/recommendationservice <nil> 0xc0005c4198 0xc0005c41a8 [] <nil> <nil> <nil> <nil> 0xc000261e00 false [] [0xc0005c4198 0xc0005c41a8] [0xc0005c4190 0xc0005c41a0] [] <nil> <nil>}: exec: "git": executable file not found in $PATH 
gcr.io/825862901243/recommendationservice:dirty
 - gcr.io/825862901243/shippingservice -> WARN[0000] Unable to find git commit: starting command &{git [git rev-parse --short HEAD] [] src/shippingservice <nil> 0xc0005c41b8 0xc0005c41c8 [] <nil> <nil> <nil> <nil> 0xc000261f60 false [] [0xc0005c41b8 0xc0005c41c8] [0xc0005c41b0 0xc0005c41c0] [] <nil> <nil>}: exec: "git": executable file not found in $PATH 
gcr.io/825862901243/shippingservice:dirty
 - gcr.io/825862901243/checkoutservice -> WARN[0000] Unable to find git commit: starting command &{git [git rev-parse --short HEAD] [] src/checkoutservice <nil> 0xc0005c41d8 0xc0005c41e8 [] <nil> <nil> <nil> <nil> 0xc00059c0c0 false [] [0xc0005c41d8 0xc0005c41e8] [0xc0005c41d0 0xc0005c41e0] [] <nil> <nil>}: exec: "git": executable file not found in $PATH 
gcr.io/825862901243/checkoutservice:dirty
 - gcr.io/825862901243/paymentservice -> WARN[0000] Unable to find git commit: starting command &{git [git rev-parse --short HEAD] [] src/paymentservice <nil> 0xc0005c41f8 0xc0005c4208 [] <nil> <nil> <nil> <nil> 0xc00059c220 false [] [0xc0005c41f8 0xc0005c4208] [0xc0005c41f0 0xc0005c4200] [] <nil> <nil>}: exec: "git": executable file not found in $PATH 
gcr.io/825862901243/paymentservice:dirty
 - gcr.io/825862901243/currencyservice -> WARN[0000] Unable to find git commit: starting command &{git [git rev-parse --short HEAD] [] src/currencyservice <nil> 0xc0005c4218 0xc0005c4228 [] <nil> <nil> <nil> <nil> 0xc00059c380 false [] [0xc0005c4218 0xc0005c4228] [0xc0005c4210 0xc0005c4220] [] <nil> <nil>}: exec: "git": executable file not found in $PATH 
gcr.io/825862901243/currencyservice:dirty
 - gcr.io/825862901243/cartservice -> WARN[0000] Unable to find git commit: starting command &{git [git rev-parse --short HEAD] [] src/cartservice <nil> 0xc0005c4238 0xc0005c4248 [] <nil> <nil> <nil> <nil> 0xc00059c4e0 false [] [0xc0005c4238 0xc0005c4248] [0xc0005c4230 0xc0005c4240] [] <nil> <nil>}: exec: "git": executable file not found in $PATH 
gcr.io/825862901243/cartservice:dirty
 - gcr.io/825862901243/frontend -> WARN[0000] Unable to find git commit: starting command &{git [git rev-parse --short HEAD] [] src/frontend <nil> 0xc0005c4258 0xc0005c4268 [] <nil> <nil> <nil> <nil> 0xc00059c640 false [] [0xc0005c4258 0xc0005c4268] [0xc0005c4250 0xc0005c4260] [] <nil> <nil>}: exec: "git": executable file not found in $PATH 
gcr.io/825862901243/frontend:dirty
 - gcr.io/825862901243/loadgenerator -> WARN[0000] Unable to find git commit: starting command &{git [git rev-parse --short HEAD] [] src/loadgenerator <nil> 0xc0005c4278 0xc0005c4288 [] <nil> <nil> <nil> <nil> 0xc00059c7a0 false [] [0xc0005c4278 0xc0005c4288] [0xc0005c4270 0xc0005c4280] [] <nil> <nil>}: exec: "git": executable file not found in $PATH 
gcr.io/825862901243/loadgenerator:dirty
 - gcr.io/825862901243/adservice -> WARN[0000] Unable to find git commit: starting command &{git [git rev-parse --short HEAD] [] src/adservice <nil> 0xc0005c4298 0xc0005c42a8 [] <nil> <nil> <nil> <nil> 0xc00059c900 false [] [0xc0005c4298 0xc0005c42a8] [0xc0005c4290 0xc0005c42a0] [] <nil> <nil>}: exec: "git": executable file not found in $PATH 
gcr.io/825862901243/adservice:dirty
Tags generated in 803.685µs
Starting build...
Building [gcr.io/825862901243/emailservice]...
FATA[0000] build failed: building [gcr.io/825862901243/emailservice]: build artifact: docker build: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/build?buildargs=null&cachefrom=null&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=null&memory=0&memswap=0&networkmode=&rm=0&shmsize=0&t=gcr.io%2F825862901243%2Femailservice%3Adirty&target=&ulimits=null: dial unix /var/run/docker.sock: connect: permission denied 

$ which git
/usr/bin/git

$ docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.
[...]

**Comment by palladius** [comment]
downloaded latest skaffold - it's now doing plenty of stuff. 

$ skaffold version
v1.8.0

I believe you can close it, but maybe put a minim skaffold version requirement .

**Comment by ahmetb** [comment]
There's already a minimum skaffold version requirement, has that not worked? It's usually a good idea to have latest skaffold (so maybe we should remove the requirement).

**Comment by Fatahir** [comment]
how did you solve this issue? I am also facing the same issue. I have v1.10.0 skaffold version. Here is the output of `skaffold run`
![Screenshot from 2020-05-20 15-48-45](https://user-images.githubusercontent.com/33696029/82437920-a9fc6200-9ab1-11ea-8821-862846657016.png)
