### ISSUE TITLE
Incorrect image tag name

### ISSUE THREAD

**Issue by huikang** [GoogleCloudPlatform/microservices-demo#342]
After I run `skaffold build`, the image tags are named as `v0.1.4-22-gdbde2f3`. The git commit is correct which matches the latest master `dbde2f3`. However, why it begins with "v0.1.4"? Should it be v0.2.0?

`

**Comment by ahmetb** [comment]
Likely because you don't have the tags locally. Though I'm not sure why would you need it to precisely match the upstream tag.

**Comment by huikang** [comment]
Thanks. Even I pull the latest tag, it still doesn't update the image tag.
```
git tag
v0.1.0
v0.1.1
v0.1.2
v0.1.3
v0.1.4
v0.1.5
v0.2.0
```

Is this an issue related to skaffold?

**Comment by ahmetb** [comment]
Very likely, I recommend filing there with a repro.

**Comment by ahmetb** [comment]
Though I would encourage you to take a look at which git cmd skaffold executes in the source code first. Maybe it's a `git` thing.
