### ISSUE TITLE
update Go services to use Modules

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#35]
Right now, all Go services are copy/pasting the

- initTracing()
- initProfiling()
- initStats()
- [initDebugger() – does not exist yet]

methods. The problem with extracting these into a utility package is that each `src/{SERVICE}` is self-contained and doesn't depend to `src/{ANOTHER_DIR}`.

Not sure how to solve this.

**Comment by ShevaXu** [comment]
I am trying to solve this using Go modules, but it also depends on sth outside `src/{SERVICE}`, just no sure how important it has to be self-contained.

**Comment by ahmetb** [comment]
Yeah the Go modules probably is the best choice, however we'd need to add go.mod to each go microservice, as well as to the project-root (to be able to import the utility package).

Then we need to pin each service's dependency to the root repo. This may complicate the local development especially (as it would likely go fetch the package from upstream as opposed to local disk, as we wouldn't include `replace "module" => ../path` syntax in the go.mod files.

Sooo I'm not exactly sure if this issue is high priority. But if you manage to get it to work on your fork, I am excited in seeing it.

**Comment by ShevaXu** [comment]
So far I feel Go module just don't work with the mono-repo setting. The only way I can think of is the `replace` directive but then it loses the version.

What I am doing is putting the proto files and the utility/common package in another repo, that way you can give this dependency a "version" (which depends on the git tagging). The services remain in a single repo each with a `go.mod` file.

**Comment by ahmetb** [comment]
> The only way I can think of is the `replace` directive but then it loses the version.

`replace` directive works only locally. We would remove "replace" while adding to the repo. Ideally go services don't have to use common utils as the same version. So while "checkoutservice" is at v0.6, it could still be using common utils from v0.2 of the same repo, and it should be ok.

Multiple modules on a monorepo == pain. I've experienced this first hand. But it's totally possible.

**Comment by ShevaXu** [comment]
> replace directive works only locally. We would remove "replace" while adding to the repo.

I am not sure if I understand it right, if adding the "replace" to the repo, the relative path import should work on the build system or when other ppl check the whole repo out? But then it can only be the "latest" version, the same commit with the service to build.

**Comment by ahmetb** [comment]
We would use `replace` directive only as us (== repo maintainers) when we need to test changes locally. Users would not check out go.mod files with `replace` directives in them. This is how `replace` is meant to be used.

**Comment by DanSanche** [comment]
Closing this and other `kind/improvement` issues as we attempt to move the project into a stable maintenance state
