### ISSUE TITLE
cartservice: make the image smaller

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#36]
Currently cartservice is 1.8 GiB. Takes forever to build and push. This probably accounts for a significant chunk of initial build time. 

There are base images like dotnet:2.1-aspnetruntime-alpine which can help reduce this.

**Comment by ahmetb** [comment]
https://www.hanselman.com/blog/ExperimentalReducingTheSizeOfNETCoreApplicationsWithMonosLinker.aspx

**Comment by orthros** [comment]
Taking a look at this

**Comment by ahmetb** [comment]
fixed in #46.
