### ISSUE TITLE
Running microservices with istio

### ISSUE THREAD

**Issue by Fatahir** [GoogleCloudPlatform/microservices-demo#360]
i have created a local kubernetes cluster on ubuntu using kubeadm and I run this application on cluster successfully. Now I deleted all the pods of this namespace and want to run this application with istio. Readme.md only guide about how to run this application without istio. Can anyone tell me all the steps to run this application with istio enabled?

**Comment by ahmetb** [comment]
README.md has Istio-specific instructions.
https://github.com/GoogleCloudPlatform/microservices-demo#option-4-deploying-on-a-istio-enabled-gke-cluster

**Comment by Fatahir** [comment]
I have read that but didn't understand clearly. Kindly correct me if i am wrong. Step 1 is similar to my local kubernetes cluster. Step 2, 3 and 4 for the installation and enable istio on cluster. After these steps I think when i run get pods then all istio-system namespace pods will be running.  Copy step 5 for running yaml file, At step 6, i have to run the application on cluster as i did it early.

**Comment by ahmetb** [comment]
Sorry, but we don't have a lot of bandwidth to support individual help requests.
Running on Istio simply involves deploying provided manifest files.

**Comment by Fatahir** [comment]
okay
