### ISSUE TITLE
Please restore the `session-id` and `request-id` references

### ISSUE THREAD

**Issue by jamesawebb** [GoogleCloudPlatform/microservices-demo#361]
The `session-id` and `request-id` references were removed from the footer (`src/frontend/templates/footer.html`) in v0.2.0 as a part of the "footer cleanup" in https://github.com/GoogleCloudPlatform/microservices-demo/commit/814088f788fd014b433546d4f03e97f148dd2ac8.  Could we restore these?  They were useful to observe (relevant) logs in Cloud Logging.

**Comment by ahmetb** [comment]
Yep, seems like it got lost briefly during frontend design change. These help us correlate requests to logs, so we can add back.
