### ISSUE TITLE
Atleast one invalid signature was encountered 

### ISSUE THREAD

**Issue by saranyagupta05** [GoogleCloudPlatform/microservices-demo#362]
I am trying to build and deploy microservices images to a single-node Kubernetes cluster running on my machine using minikube. 
I am using the readme provided. 
While following the installation process, and on running command `skaffold run` (according to Option 1: Running locally) to build and deploy my application, I get some errors:

```
Step 10/11 : RUN apt-get -qq update     && apt-get install -y --no-install-recommends         curl
 ---> Running in 43d61232617c
W: GPG error: http://deb.debian.org/debian buster InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian buster InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian buster-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian buster-updates InRelease' is not signed.
W: GPG error: http://security.debian.org/debian-security buster/updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://security.debian.org/debian-security buster/updates InRelease' is not signed.
failed to build: couldn't build "loadgenerator": unable to stream build output: The command '/bin/sh -c apt-get -qq update     && apt-get install -y --no-install-recommends         curl' returned a non-zero code: 100

```
I receive these errors when trying to build loadgenerator. 
How can I resolve this issue?

**Comment by ahmetb** [comment]
This is most likely something wrong on your side or temporarily.
Either debian repos were temporarily down or someone is trying to intercept your traffic.

**Comment by saranyagupta05** [comment]
> This is most likely something wrong on your side or temporarily.
> Either debian repos were temporarily down or someone is trying to intercept your traffic.

Thanks! Is there any way in which I can fix this?

**Comment by ahmetb** [comment]
Probably nothing we can do or advise.
