### ISSUE TITLE
Proposal: Make the online store stateful

### ISSUE THREAD

**Issue by ntolia** [GoogleCloudPlatform/microservices-demo#365]
Is there openness to making the Redis pod (`kubernetes-manifests/redis.yaml`) stateful? It would involve the creation of a PVC and tweaking `redis-server` args.

Happy to open a PR but wanted to first check if it would be within the scope of this project.

**Comment by WillieWookiee** [comment]
I have actually done this already. The way to do it is using a remote redis server. It is supported, but there is an issue with just configuring it in the current state. It needs to have the alpine image updated and another fix after that, see the previous issue I mentioned for it. 

I basically utilized GCP's Redis PaaS offering and was able to get it working.

**Comment by ahmetb** [comment]
It’s unlikely we’ll make architectural changes at this point. 

One are the reasons that this demo application is quite popular is likely because it’s easy to get it up and running without any configuration, and if there was a stateful database, it probably wouldn’t be as easy to do so.  :)

**Comment by WillieWookiee** [comment]
@ahmetb Not sure if you consider this an architectural change, but you guys have the code already there to use a remote Redis server. It is just specifying an ENV variable. The only problem is that it needs to have the dockerfile updated to reflect the latest alpine with another line for libcompat6 fix. I have tested it and it works great. It doesn't affect the running of the demo as-is, but adds functionality based on if the user wants it.

**Comment by ntolia** [comment]
@ahmetb There is no real architectural change apart from adding a PVC and command line tweaks.  See  https://github.com/kastenhq/microservices-demo/commit/1a272e75c09e98380b5c612e2f95105b9e12c512 as an example and with things like the CSI hostpath driver, using storage is quite easy these days on even a laptop/kind. 

That said, I completely understand if this is outside of the scope of the project. Please feel free to close the issue.

**Comment by WillieWookiee** [comment]
@ntolia The easier way is to use a remote Redis server, but I understand what you are saying making it on a persistent disk.

**Comment by ntolia** [comment]
> @ntolia The easier way on GCP is to use a remote Redis server, but I understand what you are saying making it on a persistent disk.

Using a PVC makes the application self-contained and it should work on pretty much any distribution or machine (including your laptop) and without an external Internet connection and with hostpath provisioning. Should match @ahmetb's goal better but, even though I think my proposed change (https://github.com/kastenhq/microservices-demo/commit/1a272e75c09e98380b5c612e2f95105b9e12c512) is minimal, I understand if it is out of scope.

**Comment by djmailhot** [comment]
Closing this issue as out of scope for this project.
