### ISSUE TITLE
Lot of CVEs into images

### ISSUE THREAD

**Issue by dhruvdarji1** [GoogleCloudPlatform/microservices-demo#373]
Hi,

Is there anyone working towards getting these 2.0 version images updated so that it doesnt contain CVEs (atleast not HIGH and etcs )

Last updated on images were in April 2020

**Comment by ahmetb** [comment]
Can you explain why is this critical for a demo app?

**Comment by dhruvdarji1** [comment]
Well...Most people using this App to demonstrate K8S benefits etc. However K8S needs various other components around it within Enterprise environment. For example, Container Registry etc. ....To demonstrate end to end benefit of containers/K8S to enterprise organisation,it vital to have these images free of vulnerabilities ...Enterprise looks at not just technical demos for individual technology s but instead looks overall coverage like Container Benefits to Org using K8S, Benefits of Container registry from security point of view...

I understand different apps can be used for different purposes..but this app is widely used for makes more sense to be used in End to end Demos rather just covering K8S deployment 

Hope this makes sense.

**Comment by ahmetb** [comment]
We cannot possibly keep 10 images in this app up to date with latest CVEs. We try to tag releases regularly so the images get rebuilt. However, at the end, this app is not optimized for "container image security scanning" demos.

If you need something different for your repos, please Fork so you can maintain images at the cadence you want.
