### ISSUE TITLE
AWS Go dependencies

### ISSUE THREAD

**Issue by ocervell** [GoogleCloudPlatform/microservices-demo#39]
I was wondering why we have a bunch of AWS go dependencies that AFAIK we are not using within the go services code. A good example is in [this file](https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/src/productcatalogservice/Gopkg.lock#L40).

**Comment by ahmetb** [comment]
Thanks for bringing it up. Looks like this is caused by a recent change to OpenCensus libraries. I'll open an issue there.

```
vendor/contrib.go.opencensus.io/exporter/stackdriver/monitoredresource/aws_identity_doc_utils.go
18:	"github.com/aws/aws-sdk-go/aws/ec2metadata"
19:	"github.com/aws/aws-sdk-go/aws/session"
```

**Comment by ahmetb** [comment]
Now fixed.
