### ISSUE TITLE
Storage of product and cart information 

### ISSUE THREAD

**Issue by saranyagupta05** [GoogleCloudPlatform/microservices-demo#392]
Hi, I have set up the Online Boutique application on my local machine using minikube. For experimental purposes, I add products to cart, and use the checkout service (provide all details etc.), but after I bring down a container all the information is lost. I understand that this is supposed to happen, but I want to understand how this architecture persists the product and cart related information. Is there any database somewhere? 
Thanks.

**Comment by ahmetb** [comment]
No, the app is stateless. You can create a database and persist data instead of redis.

**Comment by saranyagupta05** [comment]
Got it! Thank you!
