### ISSUE TITLE
Cannot 'skaffold run' using Docker Windows (AdService cannot build)

### ISSUE THREAD

**Issue by JohnGDev** [GoogleCloudPlatform/microservices-demo#401]
1) git clone https://github.com/GoogleCloudPlatform/microservices-demo.git
2) cd microservices-demo
3) skaffold run

skaffold runs but fails here:

Successfully built a5b5d1959c53
Successfully tagged loadgenerator:v0.1.4-34-g18a78e2
[34mBuilding [adservice]...
[0mSending build context to Docker daemon  114.7kB
Step 1/17 : FROM openjdk:8-slim as builder
 ---> 11bdd2ff2337
Step 2/17 : WORKDIR /app
 ---> Using cache
 ---> c2563b2d0a2a
Step 3/17 : COPY ["build.gradle", "gradlew", "./"]
 ---> Using cache
 ---> b8700bade9f8
Step 4/17 : COPY gradle gradle
 ---> Using cache
 ---> 9f8b72483e19
Step 5/17 : RUN chmod +x gradlew
 ---> Using cache
 ---> 324311a5d173
Step 6/17 : RUN ./gradlew downloadRepos
 ---> Running in 46afb9f8c8f0
[91m/usr/bin/env: ‘sh\r’: No such file or directory
[0m[31mfailed to build: couldn't build "adservice": unable to stream build output: The command '/bin/sh -c ./gradlew downloadRepos' returned a non-zero code: 127[0m

**Comment by JohnGDev** [comment]
cleaned EOF

**Comment by IamShubhamGupto** [comment]
@JohnGDev 
Could you elaborate?
