### ISSUE TITLE
failed to build: couldn't build "loadgenerator"

### ISSUE THREAD

**Issue by jculio** [GoogleCloudPlatform/microservices-demo#406]
- Precisely:
ERROR: Failed building wheel for gevent

-  Solution: change in `src/loadgenerator/Dockerfile`
FROM python:3-slim as base    -->    FROM python:3.6-slim as base

**Comment by ahmetb** [comment]
I can repro, not sure why it's broken all of a sudden. (_smh python..._)

**Comment by jculio** [comment]
UPDATE for TAG:v0.2.0:
I left in the Dockerfile the original -> `FROM python:3-slim as base`

ERROR:
```
/usr/local/lib/python3.9/site-packages/pip/_internal/commands/install.py:235: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
ERROR: Location-changing options found in --install-option: ['--prefix'] from command line. This is unsupported, use pip-level options like --user, --prefix, --root, and --target instead.
```

SOLUTION:
added -> `RUN python -m pip install --force-reinstall pip==20.1.1`
before the line -> `RUN pip install --install-option="--prefix=/install" -r requirements.txt`

REASON:
Installation fails with latest pip version 20.2.3

**Comment by zinderic** [comment]
The builder definition is a bit dated (builder FROM line is from 2019-01-11) and it is too relaxed in my opinion. Maybe we can just fix the builder to a 2 years old image? Like this:

-FROM python:3-slim as base
+FROM python:3.7.2-slim as base

Just made a quick test and it seems to work.

**Comment by baseer216** [comment]
Hello

I'm a total noob when it comes to containers. 

I've updated Dockerfile

FROM python:3.8-slim as base

FROM base as builder

RUN apt-get -qq update \
    && apt-get install -y --no-install-recommends \
        g++

COPY requirements.txt .
RUN python -m pip install --force-reinstall pip==20.1.1
RUN pip install --prefix="/install" -r requirements.txt

FROM base
COPY --from=builder /install /usr/local

COPY . .
RUN chmod +x ./loadgen.sh
RUN apt-get -qq update \
    && apt-get install -y --no-install-recommends \
        curl
ENTRYPOINT ./loadgen.sh

still getting

<img width="973" alt="Screen Shot 2020-10-19 at 10 15 04 AM" src="https://user-images.githubusercontent.com/2078522/96489204-fa5c2500-11f3-11eb-8735-0b14cb19ebc3.png">

what am I missing?
