### ISSUE TITLE
OpenTelemetry Support

### ISSUE THREAD

**Issue by kshcherban** [GoogleCloudPlatform/microservices-demo#422]
Please advise do you plan to migrate from OpenCensus to OpenTelemetry?
I've seen some discussion around it in #109 but there's no track of any progress.

**Comment by ahmetb** [comment]
cc @simonz130 do you know of any progress?

**Comment by askmeegs** [comment]
We hope to migrate this app from OpenCensus to OpenTelemetry in the April-May 2021 timeframe, thanks for your patience.

**Comment by askmeegs** [comment]
Update: after discussing with our team, we have decided to keep the upstream OnlineBoutique as a reference for OpenCensus, until its eventual deprecation.

The Cloud Ops Sandbox provides an OnlineBoutique + OpenTelemetry reference. You are also welcome to fork this repo and replace OpenCensus with OpenTelemetry.

**Comment by jkowall** [comment]
Checking in on this issue, do you expect to update to Otel still? Thanks.

**Comment by julianocosta89** [comment]
Hello all,
if someone else comes across this ticket, I've forked and instrumented the Online Boutique with OpenTelemetry:
https://github.com/julianocosta89/microservices-demo

I've added an OpenTelemetry Collector and Jaeger to it as well.

I've also removed the OpenCensus and Cloud Operations (Stackdriver). 
All the changes are documented in this PR:
https://github.com/julianocosta89/microservices-demo/pull/1

**Comment by jkowall** [comment]
We did the same, here is the fork with lots of Otel added. https://github.com/logzio/microservices-demo

**Comment by mathieu-benoit** [comment]
Just adding this new CNCF blog article for reference too: https://www.cncf.io/blog/2022/04/04/learn-opentelemetry-tracing-with-this-lightweight-microservices-demo/.

**Comment by julianocosta89** [comment]
@mathieu-benoit the Otel community is working on a demo that was based on the hipster shop: https://github.com/open-telemetry/opentelemetry-demo

**Comment by mathieu-benoit** [comment]
Wow, thanks @julianocosta89, the idea was already to leverage the content you previously shared with us: https://github.com/GoogleCloudPlatform/microservices-demo/issues/422#issuecomment-1026247664. We will now make sure that we are leveraging the latest and greatest from https://github.com/open-telemetry/opentelemetry-demo. Thanks for sharing, much appreciated!
CC: @arbrown and @minherz

**Comment by arbrown** [comment]
As an update:

As of #1180, we have a kustomize module for deploying the OpenTelemetry Collector and turning on distributed tracing in the microservices. Expect basic support for custom metrics and managed Prometheus this year.
