### ISSUE TITLE
Extend or write unit tests for all services

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/microservices-demo#427]

**Comment by donmccasland** [comment]
This is now on the sample app roadmap

**Comment by bourgeoisor** [comment]
I think we should still do this. Commenting to reset SLO.

**Comment by minherz** [comment]
@NimJay do we plan to address this? If we do can we maybe split it into smaller FRs or to narrow the scope?

**Comment by bourgeoisor** [comment]
@NimJay what do you think?

**Comment by NimJay** [comment]
* We don't have bandwidth to unit-test each microservice.
