### ISSUE TITLE
grpc v1.15 will break health check protocol

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#43]
grpc 1.15 has added a new rpc to `health.proto`:

      rpc Watch(HealthCheckRequest) returns (stream HealthCheckResponse);	

Since we implement the `service Health` directly and its `rpc Check`, addition of this method will break at least some parts of `microservices-demo`.

For Go, this 100% breaks all services with grpc-go@v1.15. So I went ahead and pinned all `grpc-go` dependencies to `=v1.14.0` constraint in `Gopkg.toml`.

For dynamic languages like Node, Python: I would not be surprised if next time we update requirements.txt/package.json, health servers will stop starting because `rpc Watch` isn't implemented.

**Comment by askmeegs** [comment]
I believe this was fixed (for grpc-go) https://github.com/grpc/grpc-go/issues/2318

And the go services are now running `grpc 1.17` https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/src/productcatalogservice/Gopkg.toml#L58

**Comment by dfawley** [comment]
Note that you must embed the `Unimplemented<service_name>Server` in your service implementation to avoid being broken by newly-added methods.

**Comment by ahmetb** [comment]
Let’s keep reopen. @dfawley is this only for Go and other compiled languages -or does it include dynamic languages as well?

**Comment by dfawley** [comment]
AFAIK only Go had this problem - in general, adding RPCs to a service should be considered a backward compatible change.

**Comment by ahmetb** [comment]
BTW I think we already return codes.Unimplemented for [`rpc Watch()`](https://github.com/grpc/grpc/blob/b3b00ad858f094f742e1e8fd46b2b453ce580c5c/src/proto/grpc/health/v1/health.proto#L62). Go is probably covered from that side –until another breaking change is to be added.

**Comment by ahmetb** [comment]
@dfawley I'm looking for `type UnimplementedHealthServer` here https://godoc.org/google.golang.org/grpc/health/grpc_health_v1 but doesn't seem to be added there. (I see it in some other OSS projects.)

**Comment by dfawley** [comment]
Sorry for the confusion - https://github.com/grpc/grpc-go/pull/3025 will add it.  We needed to upgrade the `protoc-gen-go` version to pick up the new feature.

**Comment by Daniel-Sanche** [comment]
@ahmetb Is this issue still relevant?

**Comment by ahmetb** [comment]
I think we can close. grpc-go addressed this.
