### ISSUE TITLE
failed to build paymentservice, failed to build LLB, failed to load cache key

### ISSUE THREAD

**Issue by npitaev** [GoogleCloudPlatform/microservices-demo#431]
Facing build issue for the paymentservice, which might be similar to the issue #406 failed to build: couldn't build "loadgenerator", however the solution from that issue, does not help. IMO we need somehow to tweak src/paymentservice/Dockerfile but I am not sure how.

Error while following option 2 install on GCP - the following output after executing skaffold run --default-repo=gcr.io/[my valid project ID]

Building [paymentservice]...
[+] Building 0.3s (5/13)
 => [internal] load build definition from Dockerfile                     0.0s
 => => transferring dockerfile: 1.32kB                                   0.0s
 => [internal] load .dockerignore                                        0.0s
 => => transferring context: 53B                                         0.0s
 **=> ERROR [internal] load metadata for docker.io/library/node:8-alpine   0.1s
 => ERROR [base 1/1] FROM docker.io/library/node:8-alpine                0.1s**
 => => resolve docker.io/library/node:8-alpine                           0.1s
 => [internal] load build context                                        0.0s
 => => transferring context: 145.14kB                                    0.0s

  [internal] load metadata for docker.io/library/node:8-alpine:

  [base 1/1] FROM docker.io/library/node:8-alpine:

f**ailed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: docker.io/library/node:8-alpine not found
failed to build: couldn't build "paymentservice": running build: exit status 1**

**Comment by askmeegs** [comment]
Thanks for reporting this. I'm investigating.
I'm also seeing this error in cartservice: 

```
Building [cartservice]...
[+] Building 0.5s (7/14)
 => [internal] load build definition from Dockerfile                                                                                                                                                             0.0s
 => => transferring dockerfile: 1.38kB                                                                                                                                                                           0.0s
 => [internal] load .dockerignore                                                                                                                                                                                0.0s
 => => transferring context: 64B                                                                                                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/alpine:3.8                                                                                                                                                    0.3s
 => ERROR [internal] load metadata for docker.io/microsoft/dotnet:2.1-sdk-alpine                                                                                                                                 0.1s
 => ERROR [builder 1/4] FROM docker.io/microsoft/dotnet:2.1-sdk-alpine                                                                                                                                           0.1s
 => => resolve docker.io/microsoft/dotnet:2.1-sdk-alpine                                                                                                                                                         0.1s
 => [internal] load build context                                                                                                                                                                                0.0s
 => CANCELED [stage-1 1/5] FROM docker.io/library/alpine:3.8@sha256:2bb501e6173d9d006e56de5bce2720eb06396803300fe1687b58a7ff32bf4c14                                                                             0.1s
 => => resolve docker.io/library/alpine:3.8@sha256:2bb501e6173d9d006e56de5bce2720eb06396803300fe1687b58a7ff32bf4c14                                                                                              0.0s
------
 > [internal] load metadata for docker.io/microsoft/dotnet:2.1-sdk-alpine:
------
------
 > [builder 1/4] FROM docker.io/microsoft/dotnet:2.1-sdk-alpine:
------
failed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: docker.io/microsoft/dotnet:2.1-sdk-alpine not found
```

**Comment by askmeegs** [comment]
It's likely that the culprit is a recent commit that added a default Docker Buildkit option - https://github.com/GoogleCloudPlatform/microservices-demo/commit/9e84e61ecc9d28278bee30a900e56c002614024c 

Related issue: https://github.com/docker/buildx/issues/426

**Comment by askmeegs** [comment]
Leaving this issue open until I can figure out the underlying reason for this error. In the meantime I am reverting the commit that enables buildkit.

**Comment by briandealwis** [comment]
I noted on https://github.com/GoogleContainerTools/skaffold#5015 that this is a problem in Moby/Docker/Containerd when using a registry mirror like `mirror.gcr.io` (https://github.com/moby/buildkit/issues/1271) that has been fixed in newer releases of Docker.  I further noted there that when running Skaffold with Minikube, Skaffold uses the Minikube's Docker daemon for the builds rather than the local Docker daemon.

I've tried building both with the local docker daemon and with minikube 0.14.2, with `useBuildkit: true` and the build completes.

**Comment by askmeegs** [comment]
Thanks for this info, Brian! Two things, 

First, re: Docker versions, it seems like I was testing this on the latest Linux version of Docker engine. So I'm not sure if I needed up grade something else, to see the fix you're seeing? https://docs.docker.com/engine/release-notes/#version-1903

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
```

Second, I'm not sure if registry mirrors are the only thing causing the cache key errors, I also saw errors with this image (log messages above) - `docker.io/microsoft/dotnet:2.1-sdk-alpine`

**Comment by npitaev** [comment]
Many thanks, folks, for the comment!
I forgot to mention, that as workaround you can spin up the whole thing using cloud build option (-p gcb):
`skaffold run **-p gcb** --default-repo=gcr.io/<your GCP project ID>`
It looks like the cloud build setup has the right dependencies.

**Comment by briandealwis** [comment]
I hit this same issue on the weekend, and I do use `mirror.gcr.io` as a registry mirror, but I'm running the latest Docker for Mac.  So I'm not sure entirely sure where the problems lie.  I haven't dug into this further.

I will note that BuildKit uses a different code-path from a normal `docker build`, and they can be distinguished by the build output.  Use `DOCKER_BUILDKIT=1 docker build ...` to use the BuildKit builder.
