### ISSUE TITLE
skaffold build error - paymentservice

### ISSUE THREAD

**Issue by JZ3736** [GoogleCloudPlatform/microservices-demo#432]
Hi,

As recommended by the group, open issue for error encountered refer to screenshot

While skaffold building paymentService, it exits with error below, suspected " image node:8 might have been deleted."

![Screen Shot 2020-11-07 at 9 12 06 PM](https://user-images.githubusercontent.com/25289870/98470673-4c6de600-21b5-11eb-91c1-b929359a7554.png)

**Comment by mathieu-benoit** [comment]
FYI: seems to be the same error as reported here https://github.com/GoogleCloudPlatform/microservices-demo/issues/431

**Comment by askmeegs** [comment]
Thanks for reporting this! Closing this in favor of #431 which is a duplicate.
