### ISSUE TITLE
Upgrade recommendationservice to Python3

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/microservices-demo#433]
https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/src/recommendationservice/Dockerfile#L15

**Comment by mathieu-benoit** [comment]
FYI: I started that one for this: https://github.com/GoogleCloudPlatform/microservices-demo/pull/435

**Comment by askmeegs** [comment]
Ah, you're right, sorry about that! I'll close mine.

**Comment by mathieu-benoit** [comment]
Fixed by https://github.com/GoogleCloudPlatform/microservices-demo/pull/435
