### ISSUE TITLE
v0.2.1: incorrect image names in deployment yaml

### ISSUE THREAD

**Issue by didier-durand** [GoogleCloudPlatform/microservices-demo#453]
Hi there,

It seems that image names are incorrect in deployment yaml of v.0.2.1:

```
curl https://raw.githubusercontent.com/GoogleCloudPlatform/microservices-demo/v0.2.1/release/kubernetes-manifests.yaml | grep 'image:'

image: gcr.io/google-samples/microservices-demo/*:v0.2.1
image: gcr.io/google-samples/microservices-demo/*:v0.2.1
image: gcr.io/google-samples/microservices-demo/*:v0.2.1
image: gcr.io/google-samples/microservices-demo/*:v0.2.1
image: gcr.io/google-samples/microservices-demo/*:v0.2.1
image: gcr.io/google-samples/microservices-demo/*:v0.2.1
image: gcr.io/google-samples/microservices-demo/*:v0.2.1
image: gcr.io/google-samples/microservices-demo/*:v0.2.1
image: gcr.io/google-samples/microservices-demo/*:v0.2.1
image: gcr.io/google-samples/microservices-demo/*:v0.2.1
```
it seems that the star  should be replaced by proper image name for each microservice

**Comment by mathieu-benoit** [comment]
Looks like there is an issue in there https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/hack/make-release-artifacts.sh#L72, FYI @askmeegs

**Comment by askmeegs** [comment]
Apologies, this was a sed mishap during the v0.2.1 release, fixing asap! Thanks for bringing it to our attention.

**Comment by askmeegs** [comment]
Thanks for bringing this to our attention! Fixed: https://github.com/GoogleCloudPlatform/microservices-demo/releases/tag/v0.2.1 

v0.2.1 tag is now tied to the commit that fixed the asterisk error. (Caused by using the wrong `sed` during the release process, my mistake.)

**Comment by didier-durand** [comment]
@askmeegs : You're welcome. Thanks for the fix. I will now be able to try it on v0.2.1. Didier
