### ISSUE TITLE
Recommendation Service is not starting on local deployment

### ISSUE THREAD

**Issue by arunatechtalk** [GoogleCloudPlatform/microservices-demo#457]
I tried deploying this app on my local mac desktop.
Followed the instructions as mentioned in local development section of the readme.
One of the services failed to start.

NAME                                     READY   STATUS             RESTARTS   AGE
adservice-5895cb7977-phgl5               1/1     Running            0          38m
cartservice-5d4c44f44b-xl2mt             1/1     Running            3          38m
checkoutservice-69d857656c-n4zvs         1/1     Running            0          38m
currencyservice-6477bfffb5-l2spv         1/1     Running            0          38m
emailservice-86d46f5f55-jkt8s            1/1     Running            0          38m
frontend-7b79f6f477-qhkd8                1/1     Running            0          38m
loadgenerator-545b9b549-nm6vt            1/1     Running            5          38m
paymentservice-7d7776dd99-lxjkt          1/1     Running            0          38m
productcatalogservice-5c4ccf5698-k8xr7   1/1     Running            0          38m
recommendationservice-6c8595fccc-58bcq   0/1     CrashLoopBackOff   13         38m
redis-cart-55bb7f4785-7m7g7              1/1     Running            0          38m
shippingservice-8798bb9b9-k27vn          1/1     Running            0          38m
Adityas-MacBook-Pro:microservices-demo arunavempaty$ kubectl getnames

By Clicking the cart, this error is displayed on the browser

rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 10.107.64.141:8080: connect: connection refused"
failed to get product recommendations
main.(*frontendServer).viewCartHandler
	/src/handlers.go:233
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2042
github.com/gorilla/mux.(*Router).ServeHTTP
	/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212
main.(*logHandler).ServeHTTP
	/src/middleware.go:81
main.ensureSessionID.func1
	/src/middleware.go:103
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2042
go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP
	/go/pkg/mod/go.opencensus.io@v0.21.0/plugin/ochttp/server.go:86
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2843
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1925
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374

**Comment by arunatechtalk** [comment]
looks like this is expecting the google credentials which will obviously fail in local deployment.

30 seconds to retry Stackdriver Profiler agent initialization"}
{"timestamp": 1607315187.5049503, "severity": "INFO", "name": "recommendationservice-server", "message": "Tracing enabled."}
{"timestamp": 1607315187.508615, "severity": "INFO", "name": "recommendationservice-server", "message": "Tracing disabled."}
{"timestamp": 1607315187.5087895, "severity": "INFO", "name": "recommendationservice-server", "message": "Debugger enabled."}
Traceback (most recent call last):
  File "/recommendationservice/recommendation_server.py", line 129, in <module>
    version='1.0.0'
  File "/usr/local/lib/python3.7/site-packages/googleclouddebugger/__init__.py", line 152, in enable
    _StartDebugger()
  File "/usr/local/lib/python3.7/site-packages/googleclouddebugger/__init__.py", line 72, in _StartDebugger
    _flags.get('service_account_json_file'))
  File "/usr/local/lib/python3.7/site-packages/googleclouddebugger/gcp_hub_client.py", line 207, in SetupAuth
    scopes=_CLOUD_PLATFORM_SCOPE)
  File "/usr/local/lib/python3.7/site-packages/google/auth/_default.py", line 338, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/recommendationservice/recommendation_server.py", line 131, in <module>
    except (Exception, err):
NameError: name 'err' is not defined

**Comment by arunatechtalk** [comment]
Can someone look at this?

**Comment by mathieu-benoit** [comment]
Hi @arunatechtalk, like discussed on a similar issue reported recently: https://github.com/GoogleCloudPlatform/microservices-demo/issues/455, you could leverage `DISABLE_TRACING`, `DISABLE_PROFILER` and `DISABLE_DEBUGGER` to `1` here: https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/kubernetes-manifests/recommendationservice.yaml#L48.

FYI: this work-in-progress PR will propose a solution to silently catch this in the code: https://github.com/GoogleCloudPlatform/microservices-demo/pull/460.

Closing that issue for now, thanks.
