### ISSUE TITLE
Error building cartservice

### ISSUE THREAD

**Issue by yogeek** [GoogleCloudPlatform/microservices-demo#458]
Hello :) 

I cloned the code and I am trying to build the cartservice docker image on my ubuntu VM but I have the following error :
```
$ docker build -t cartservice .
Sending build context to Docker daemon  427.5kB
Step 1/10 : FROM mcr.microsoft.com/dotnet/sdk:5.0 as builder
 ---> 933354c487f6
Step 2/10 : WORKDIR /app
 ---> Using cache
 ---> 84bb85aa284d
Step 3/10 : COPY . .
 ---> Using cache
 ---> 73dcdd68b1c3
Step 4/10 : RUN dotnet publish -r linux-musl-x64 --self-contained true -c release -o /cartservice
 ---> Running in d2a103e15c70
Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /app/cartservice.csproj (in 1.22 min).
/app/tests/CartServiceTests.cs(19,7): error CS0246: The type or namespace name 'Xunit' could not be found (are you missing a using directive or an assembly reference?) [/app/cartservice.csproj]
/app/tests/CartServiceTests.cs(29,10): error CS0246: The type or namespace name 'FactAttribute' could not be found (are you missing a using directive or an assembly reference?) [/app/cartservice.csproj]
/app/tests/CartServiceTests.cs(29,10): error CS0246: The type or namespace name 'Fact' could not be found (are you missing a using directive or an assembly reference?) [/app/cartservice.csproj]
/app/tests/CartServiceTests.cs(54,10): error CS0246: The type or namespace name 'FactAttribute' could not be found (are you missing a using directive or an assembly reference?) [/app/cartservice.csproj]
/app/tests/CartServiceTests.cs(54,10): error CS0246: The type or namespace name 'Fact' could not be found (are you missing a using directive or an assembly reference?) [/app/cartservice.csproj]
/app/tests/CartServiceTests.cs(96,10): error CS0246: The type or namespace name 'FactAttribute' could not be found (are you missing a using directive or an assembly reference?) [/app/cartservice.csproj]
/app/tests/CartServiceTests.cs(96,10): error CS0246: The type or namespace name 'Fact' could not be found (are you missing a using directive or an assembly reference?) [/app/cartservice.csproj]
The command '/bin/sh -c dotnet publish -r linux-musl-x64 --self-contained true -c release -o /cartservice' returned a non-zero code: 1
```

Anything I missed please ?

**Comment by mathieu-benoit** [comment]
Hi @yogeek, trying to see if can reproduce, in the meantime just curious, are you running this command from this folder `~/microservices-demo/src/cartservice`? Could you also make sure you have the latest version of the `master` branch with `git pull`?

**Comment by mathieu-benoit** [comment]
Interestingly I just did this:
```
git clone https://github.com/GoogleCloudPlatform/microservices-demo microservices-demo-2
cd microservices-demo-2/src/cartservice
docker build -t cartservice .
```
And was succesfully able to build that `cartservice` container locally.
Could you please run those 3 commands above to see if you still have the issue? And let's see from there.

**Comment by yogeek** [comment]
Hello @mathieu-benoit and thank you for your help !

Indeed, your commands are working well. I investigated a little bit and it appears that I copied the `src/cartservice` in a separate folder with `cp -r src/cartservice/*` before building the image : and so, the little hidden `.dockerignore` file was not part of my directory, and I guess this caused the error because of [this line](https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/src/cartservice/.dockerignore#L3) : do you confirm the errors above comes from code in the `test` directory ?

Bonus question : how can these tests be launched for this microservice please ? (I saw that these were commented [here](https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/.github/workflows/ci-master.yaml#L36-L39) : is this because of the time it takes ?)

Thanks !

**Comment by mathieu-benoit** [comment]
Great to hear it works as expected, thanks for following up.

For your bonus question, there is an open issue https://github.com/GoogleCloudPlatform/microservices-demo/issues/428 to re-enable these .NET unit tests.

Closing this current issue for now.

**Comment by yogeek** [comment]
Perfect, thank you again !
