### ISSUE TITLE
Problem with 3 microservices during app deployment

### ISSUE THREAD

**Issue by sayom88** [GoogleCloudPlatform/microservices-demo#464]
After clone this repository, deployed the sample app to the cluster using the command mentioned kubectl apply -f ./release/kubernetes-manifests.yaml

But when I am running the command to check the status of the pod, observing that 3 services are not running:
1.cartservice
2.loadgenerator
3.recommendationservice

Also to access the web frontend, when I run the command kubectl get service frontend-external, it is showing like this. 

Can you please suggest why the 3 services are not running and why the frontend-external service is not returning external ip please. Tnx

![image](https://user-images.githubusercontent.com/16284729/101764963-afc99b80-3b06-11eb-8a83-ff55ea4ee705.png)

**Comment by mathieu-benoit** [comment]
Hi @sayom88, could you indicate more about your setup please? Are you using GKE? With WorkloadIdentity? What `kubectl get all,secrets` is telling you? Furthermore, you may want to run few `kubectl logs` on the 3 pods in `CrashLoopBackOff`. Let's see from there.

**Comment by sayom88** [comment]
Hi @mathieu-benoit  thanks for getting back....no I am using Openshift Cluster.... when i run the kubectl get all,secrets, i am sharing the attachment.
[output.txt](https://github.com/GoogleCloudPlatform/microservices-demo/files/5673195/output.txt)

**Comment by mathieu-benoit** [comment]
Ok, you should get more information to see what's happening with:
- `kubectl logs` on the `loadgenerator` pod
- `kubectl describe deploy cartservice`
- `kubectl describe deploy recommendationservice`

**Comment by mathieu-benoit** [comment]
Furthermore @sayom88, you need to get the latest version of `master` because you may have been impacted by the issue on `cartservice` like explained here: https://github.com/GoogleCloudPlatform/microservices-demo/issues/469, the associated fix was merged into master since we spoke earlier on that thread.

**Comment by sayom88** [comment]
Hi @mathieu-benoit i have taken the latest version only....is it due to the fact that I am deployed in Openshift cluster and not on Google Kubernestes cluster?

**Comment by mathieu-benoit** [comment]
Hi @sayom88, could you please provide the information of the last section named `Events` of the output when you run these commands:
```
kubectl describe deploy loadgenerator
kubectl describe deploy cartservice
kubectl describe deploy recommendationservice
```

**Comment by ttsrg** [comment]
I've faced same problem using slow node. Instance 4cpu has fixed this problem for testing purposes.  

Possible  decrease CPU limits into manifest helps to start app on 2xCPU node.


```
kubectl describe node <node-srv>
  Resource                    Requests      Limits
  --------                    --------      ------
  cpu                         2210m (55%)   2825m (70%)
  memory                      1598Mi (10%)  2882Mi (18%)
```

**Comment by mathieu-benoit** [comment]
Thanks @ttsrg, you are correct that could be one of the reason among different other reasons (that's why seeing what those `kubectl describe deploy` say, could help narrow the issues). I actually faced the CPU limits you mention, maybe it's a good future contribution to this repo to improve that part, agree with you.

**Comment by ttsrg** [comment]
> Possible decrease CPU limits into manifest helps to start app on 2xCPU node.

Ou no, if we use istio , we have to have free resources.  I guess 4xCPU minimal requirements.....

**Comment by sayom88** [comment]
Hi @mathieu-benoit @ttsrg  sharing all the details of the failed services. May I request can you kindly take a look into them please and suggest the needful please. Tnx.
[currencyservice.txt](https://github.com/GoogleCloudPlatform/microservices-demo/files/5695099/currencyservice.txt)
[shippingservice.txt](https://github.com/GoogleCloudPlatform/microservices-demo/files/5695100/shippingservice.txt)
[loadgenerator.txt](https://github.com/GoogleCloudPlatform/microservices-demo/files/5695101/loadgenerator.txt)
[cartservice.txt](https://github.com/GoogleCloudPlatform/microservices-demo/files/5695102/cartservice.txt)
[adservice.txt](https://github.com/GoogleCloudPlatform/microservices-demo/files/5695103/adservice.txt)

**Comment by mathieu-benoit** [comment]
From there we don't have more details about why you have `0 available | 1 unavailable`. Have you tried to see if `kubectl describe pod` on the associated pods, give you more insights?
```
kubectl describe pod -l app=cartservice 
kubectl describe pod -l app=currencyservice 
kubectl describe pod -l app=adservice 
kubectl describe pod -l app=shippingservice 
kubectl describe pod -l app=loadgenerator 
```

**Comment by sayom88** [comment]
Hi @mathieu-benoit  here you go:
[recommendationservice.txt](https://github.com/GoogleCloudPlatform/microservices-demo/files/5696221/recommendationservice.txt)
[cartservice.txt](https://github.com/GoogleCloudPlatform/microservices-demo/files/5696225/cartservice.txt)
[loadgenerator.txt](https://github.com/GoogleCloudPlatform/microservices-demo/files/5696226/loadgenerator.txt)

**Comment by mathieu-benoit** [comment]
Not going to fix the issue, but please make sure you apply the latest version of the `cartservice`'s deployment file: https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/release/kubernetes-manifests.yaml. I can see you don't apply it again since the latest update/fix on it.

_Disclaimer, I'm not an OpenShift expert and I'm trying to do my best to help you investigating your issues._

Have you looked at what is saying the last events of `kubectl get events`? Furthermore, any chance to get more info on those specific pods with `kubectl logs`?

_Note: please make sure you are not sharing any sensitive information in your files._

**Comment by sayom88** [comment]
Hi @mathieu-benoit can you please confirm one thing.....what is the Kubernetes cluster configuration required to deploy this app? Can this be deployed in a free Kubernetes cluster that the cloud vendors provides?

**Comment by mathieu-benoit** [comment]
Hi @sayom88, GKE mostly but different scenario exist with `minikube`, `kind`, etc. for example: https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/docs/development-guide.md. Now if you have issues with the minimal deployments (`release/kubernetes-manifests`) that may help to improve that repo if appropriate.

**Comment by sayom88** [comment]
Hi @mathieu-benoit  so I see that for local setup, the Kubernetes cluster has to be at least:
    4 CPUs
    4.0 GiB memory
    32 GB disk space

Is that the case as well for any Kubernetes cluster in the cloud platform?

**Comment by sayom88** [comment]
Hi @mathieu-benoit ,i have done a fresh deployment today using the latest version....now i see only loadgenerator service is having the CrashLoopBackOff ,other services are running fine....
![image](https://user-images.githubusercontent.com/16284729/102362069-f4a77380-3fd9-11eb-9b94-0c29304f2883.png)

Now as you have suggested i am doing kubectl describe pod -l app=loadgenerator, i get this details
[loadgenerator.txt](https://github.com/GoogleCloudPlatform/microservices-demo/files/5703336/loadgenerator.txt)

**Comment by mathieu-benoit** [comment]
You have `0/1` for `cartservice` and `redis` too. Again, `kubectl get events`, `kubectl describe pod` on both and `kubectl logs` on those 3 pods may provide you more information...

**Comment by ttsrg** [comment]
@sayom88 could you run next commands please:  

```
kubectl get ev
kubectl describe node <name-of-node>
```

**Comment by ttsrg** [comment]
> Hi @mathieu-benoit so I see that for local setup, the Kubernetes cluster has to be at least:
> 4 CPUs
> 4.0 GiB memory
> 32 GB disk space
> 
> Is that the case as well for any Kubernetes cluster in the cloud platform?

It's minimal requiremets

**Comment by sayom88** [comment]
Hi @ttsrg today I have done a fresh new deployment using the latest codebase in one of my AKS Cluster....this is the what is the current situation now:
![image](https://user-images.githubusercontent.com/16284729/102481332-96d16500-4087-11eb-955f-124d5f4d8b8f.png)

This is the external ip: http://20.75.153.221/

Also sharing the details of the loadgenerator and cartservice service this time....
[loadgenerator.txt](https://github.com/GoogleCloudPlatform/microservices-demo/files/5708951/loadgenerator.txt)
[cartservice.txt](https://github.com/GoogleCloudPlatform/microservices-demo/files/5708969/cartservice.txt)

Can you please suggest what tweeking needs to be done now to get this working?

**Comment by mathieu-benoit** [comment]
For `cartservice`, you could see in the `Events` section that there is erros like `Readiness probe errored` which is caused because you still have an old version of the deployment with the env variable `ASPNETCORE_URLS:  http://0.0.0.0:7070`. Again, like mentioned earlier in this thread, fixed with this PR # https://github.com/GoogleCloudPlatform/microservices-demo/pull/470. Could you make sure you are doing `kubectl apply -f release/kubernetes-manifest.yaml` with latest version of the `master` or `release/v0.2.1` branches? Let's which error will remain from there...

**Comment by sayom88** [comment]
Hello @mathieu-benoit  Finally it works fine.... tnx....this is the url http://40.88.228.228/ 

Only I suggestion here is, how to remove the GoogleCloud icon since I have deployed this in Azure cloud platform. Is there any way to remove this banner please?

![image](https://user-images.githubusercontent.com/16284729/102509377-7c5db280-40ac-11eb-8006-9c0d310605f6.png)

**Comment by mathieu-benoit** [comment]
Glad you made it! Closing this issue then.

For your question about the `Google Cloud` label, you could apparently change the value of the `ENV_PLATFORM` env variable here: https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/release/kubernetes-manifests.yaml#L258. Here are the values available: https://github.com/GoogleCloudPlatform/microservices-demo/blob/65b5da1a9b3ebdb2cccee3c8e80a927de02cb29d/src/frontend/handlers.go#L104, so looks like you could replace the `gcp` value by `azure`. Cheers!

**Comment by sayom88** [comment]
tnx @mathieu-benoit and @ttsrg
