### ISSUE TITLE
Managed grpc change broke cart service

### ISSUE THREAD

**Issue by elfinhe** [GoogleCloudPlatform/microservices-demo#469]
Change from https://github.com/GoogleCloudPlatform/microservices-demo/pull/454 has broken the cart service, because the image does not have the latest code?

Steps to reproduce:

```
git clone https://github.com/GoogleCloudPlatform/microservices-demo.git
kubectl create ns test-ns
kubectl apply -f microservices-demo/release -n test-ns
```

```
kubectl describe -n test-ns pod  cartservice-598bc7d6d7-cn9vw

...


Events:
  Type     Reason     Age                  From                                        Message
  ----     ------     ----                 ----                                        -------
  Normal   Scheduled  3m11s                default-scheduler                           Successfully assigned test-ns/cartservice-598bc7d6d7-cn9vw to gke-c3-default-pool-764e6842-j2zp
  Warning  Unhealthy  98s (x5 over 2m38s)  kubelet, gke-c3-default-pool-764e6842-j2zp  Readiness probe failed: timeout: failed to connect service ":7070" within 1s
  Warning  Unhealthy  91s (x6 over 2m31s)  kubelet, gke-c3-default-pool-764e6842-j2zp  Liveness probe failed: timeout: failed to connect service ":7070" within 1s
  Normal   Killing    91s (x2 over 2m11s)  kubelet, gke-c3-default-pool-764e6842-j2zp  Container server failed liveness probe, will be restarted
  Normal   Pulled     90s (x4 over 3m9s)   kubelet, gke-c3-default-pool-764e6842-j2zp  Container image "gcr.io/google-samples/microservices-demo/cartservice:v0.2.1" already present on machine
  Normal   Created    90s (x4 over 3m8s)   kubelet, gke-c3-default-pool-764e6842-j2zp  Created container server
  Normal   Started    90s (x4 over 3m8s)   kubelet, gke-c3-default-pool-764e6842-j2zp  Started container server

```

**Comment by elfinhe** [comment]
@askmeegs @mathieu-benoit

**Comment by mathieu-benoit** [comment]
Thanks for the feedback, I will look at this as soon as I can.

**Comment by elfinhe** [comment]
seems like release/ is still using cartservice:v0.2.1, where the latest code was not pushed.

**Comment by mathieu-benoit** [comment]
Yep, indeed, I updated the `release/kubernetes-manifest.yaml` in master branch, which actually should be generated when the next new release will happen.
In the meantime, since you would like to deploy the prebuilt `0.2.1` container images, I encourage you to grab the source code from the associated release here https://github.com/GoogleCloudPlatform/microservices-demo/releases/tag/v0.2.1 (zip file) or from the associated branch: https://github.com/GoogleCloudPlatform/microservices-demo/tree/release/v0.2.1.

**Comment by mathieu-benoit** [comment]
Hi @elfinhe, https://github.com/GoogleCloudPlatform/microservices-demo/pull/470 fixing this, has just been merged into master. That should fix your issue, thanks for raising this that early and let us know if everything is coming back to normal with this. Thanks.

**Comment by elfinhe** [comment]
Thanks so much for the quick response and fix.

**Comment by mathieu-benoit** [comment]
Assuming this has been fixed, closing it for now but feel free to reopen it if you still have the issue, thanks.
