### ISSUE TITLE
JSON Structured logs for Stackdriver Logging

### ISSUE THREAD

**Issue by ymotongpoo** [GoogleCloudPlatform/microservices-demo#47]
Currently services in this demo, at least those written in Go, are emitting logs to stderr as of now, which makes the appearance of logs confusing because some info level logs are treated as error level ones, due to Stackdriver Logging's default setting. Changing the log destination to stdout solves this.

Also, all log messages are in text payload. Though this is the demonstration of GKE, it would be great if it can demonstrate the features of Stackdriver Logging as well. For that, using JSON (structured log format) can show how Stackdriver Logging can handle the log more efficiently such as handy filters.

## Progress tracker

(added by ahmetb, cc: @ymotongpoo  )

- [x] adservice (#59)
- [ ] cartservice
- [x] checkoutservice (#48)
- [x] currencyservice (#66)
- [x] emailservice (#66)
- [x] frontend
- loadgenerator (not eligible, produces human-readable output)
- [x] paymentservice (#66)
- [x] productcatalogservice (#48)
- [x] recommendationservice (#66)
- [x] shippingservice (#48)

**Comment by askmeegs** [comment]
cartservice is the only service remaining to complete this -- closing in favor of https://github.com/GoogleCloudPlatform/microservices-demo/issues/154
