### ISSUE TITLE
Some of the pods are in crashLoopBackOff mode - Readiness/Liveness Probe failure 

### ISSUE THREAD

**Issue by anilreddyv** [GoogleCloudPlatform/microservices-demo#484]
Some of the services are failing on-prem K8 cluster (version v1.18.8). Using master brach of the demo service

➜  microservices-demo git:(master) ✗ k get pods
+ kubectl get pods
NAME                                     READY   STATUS             RESTARTS   AGE
adservice-5597994964-thxn9               2/2     Running            0          86s
cartservice-6d6d946fcc-47rmx             2/2     Running            2          87s
checkoutservice-866b66b488-g6j7n         2/2     Running            0          88s
currencyservice-7659845fcd-9jclr         1/2     CrashLoopBackOff   3          87s
emailservice-5845d49d76-j7qxb            2/2     Running            0          88s
frontend-6866fc5d54-gnr9h                2/2     Running            0          88s
loadgenerator-6c685459fd-gxvvx           1/2     CrashLoopBackOff   3          87s
paymentservice-7598dcfcd4-fvfcl          1/2     CrashLoopBackOff   3          87s
productcatalogservice-c64dc9b48-hlb4c    2/2     Running            0          87s
recommendationservice-5d67cd476b-sjdjm   1/2     Running            4          88s
redis-cart-57bd646894-tzhq4              2/2     Running            0          86s
shippingservice-755f77b984-97z9c         2/2     Running            0          86s

➜  microservices-demo git:(master) ✗ k logs currencyservice-7659845fcd-9jclr -c server
+ kubectl logs currencyservice-7659845fcd-9jclr -c server

Profiler enabled.
Tracing enabled.
@google-cloud/trace-agent ERROR StackdriverTracer#start: Tracing might not work as the following modules were loaded before the trace agent was initialized: [@google-cloud/common, @google-cloud/profiler, @google-cloud/projectify, @google-cloud/promisify, @protobufjs/aspromise, @protobufjs/base64, @protobufjs/eventemitter, @protobufjs/float, @protobufjs/inquire, @protobufjs/pool, @protobufjs/utf8, abbrev, agent-base, ansi-regex, aproba, are-we-there-yet, arrify, balanced-match, base64-js, bignumber.js, brace-expansion, buffer-equal-constant-time, code-point-at, concat-map, console-control-strings, console-log-level, core-util-is, debug, delay, delegates, detect-libc, duplexify, ecdsa-sig-formatter, end-of-stream, ent, es6-promisify, extend, findit2, fs.realpath, gauge, gaxios, gcp-metadata, glob, google-auth-library, gtoken, has-unicode, https-proxy-agent, inflight, inherits, is-fullwidth-code-point, isarray, json-bigint, jwa, jws, long, lru-cache, mime, minimatch, ms, node-fetch, node-pre-gyp, nopt, npmlog, number-is-nan, object-assign, once, os-homedir, os-tmpdir, osenv, p-limit, p-try, parse-duration, parse-ms, path-is-absolute, pify, pprof, pretty-ms, process-nextick-args, protobufjs, readable-stream, retry-request, rimraf, safe-buffer, semver, set-blocking, signal-exit, source-map, split, stream-shift, string-width, strip-ansi, teeny-request, through, through2, util-deprecate, uuid, wide-align, wrappy, yallist]
Debugger enabled.
{"severity":"info","time":1609804374613,"message":"Starting gRPC server on port 7000...","pid":1,"hostname":"currencyservice-7659845fcd-9jclr","name":"currencyservice-server","v":1}

➜  microservices-demo git:(master) ✗ k logs -f paymentservice-7598dcfcd4-fvfcl -c server
+ kubectl logs -f paymentservice-7598dcfcd4-fvfcl -c server
@google-cloud/trace-agent ERROR StackdriverTracer#start: Tracing might not work as the following modules were loaded before the trace agent was initialized: [@google-cloud/common, @google-cloud/profiler, @google-cloud/projectify, @google-cloud/promisify, @protobufjs/aspromise, @protobufjs/base64, @protobufjs/eventemitter, @protobufjs/float, @protobufjs/inquire, @protobufjs/pool, @protobufjs/utf8, abbrev, agent-base, ansi-regex, aproba, are-we-there-yet, arrify, balanced-match, base64-js, bignumber.js, brace-expansion, buffer-equal-constant-time, code-point-at, concat-map, console-control-strings, console-log-level, core-util-is, debug, delay, delegates, detect-libc, duplexify, ecdsa-sig-formatter, end-of-stream, ent, es6-promisify, extend, findit2, fs.realpath, gauge, gaxios, gcp-metadata, glob, google-auth-library, gtoken, has-unicode, https-proxy-agent, inflight, inherits, is-fullwidth-code-point, isarray, json-bigint, jwa, jws, long, lru-cache, mime, minimatch, ms, node-fetch, node-pre-gyp, nopt, npmlog, number-is-nan, object-assign, once, os-homedir, os-tmpdir, osenv, p-limit, p-try, parse-duration, parse-ms, path-is-absolute, pify, pprof, pretty-ms, process-nextick-args, protobufjs, readable-stream, retry-request, rimraf, safe-buffer, semver, set-blocking, signal-exit, source-map, split, stream-shift, string-width, strip-ansi, teeny-request, through, through2, util-deprecate, uuid, wide-align, wrappy, yallist]

**Comment by anilreddyv** [comment]
I have disabled following on all the deployment too

        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"

**Comment by velcrine** [comment]
+1 cartservice fails to communicate with redis, even though redis gets ready. Because of cartservice, load generator also crashes.

**Comment by adamjsr** [comment]
Seeing the same with a 5-node v1.21.1 OSS K8s cluster on CentOS7 in EC2 (t3.small) and a 3-node v1.18.19 OSS K8s cluster in EC2 Amazon Linux (t3.2xlarge).

**Comment by adamjsr** [comment]
> Seeing the same with a 5-node v1.21.1 OSS K8s cluster on CentOS7 in EC2 (t3.small) and a 3-node v1.18.19 OSS K8s cluster in EC2 Amazon Linux (t3.2xlarge).

Signed up for GKE and got it to work, although the loadgenerator crashed and restarted a half-dozen times before the pods stabilized.  The cart service also crashed several times before stabilizing.

**Comment by askmeegs** [comment]
Hello! We have just released v0.2.4 which addresses retry logic and stability for both cartservice and the loadgenerator. Hopefully this resolves the startup issues you're seeing. We are also working on supporting non GKE on GCP environments but those will likely only include the Anthos  supported environments, including EKS and Anthos on prem Baremetal. 

https://cloud.google.com/anthos/deployment-options 

That integration work is being tracked here - #563. Closing this for now, feel free to reopen if you see separate issues related to GCP auth.
