### ISSUE TITLE
emailservice: Make the image smaller

### ISSUE THREAD

**Issue by orthros** [GoogleCloudPlatform/microservices-demo#49]
Currently the `emailservice` image size is 1.32 GB. 

This takes up a lot of build and publish time, especially from a clean system.

**Comment by orthros** [comment]
Taking a look at this

**Comment by ahmetb** [comment]
@orthros fyi #45 had relevant work
but I couldn't get this one to work (it was requiring Cython, then gcc, so I gave up).
