### ISSUE TITLE
Instrument all services with Stackdriver Profiler

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#5]
- [x] adservice
- [ ] cartservice
- [x] checkoutservice
- [x] currencyservice
- [x] emailservice
- [x] frontend
- [x] paymentservice
- [x] productcatalogservice
- [x] recommendationservice
- [x] shippingservice

**Comment by askmeegs** [comment]
@DanSanche  - explore this for 1 service

**Comment by ahmetb** [comment]
Note that the Profiler is only available for certain languages. And among those languages:

- some of them support only cpu or only memory profiling
- some languages require the app to be executed via a debugger process (which would be a PID1 inside container)
  - we need to be careful such processes are able to forward signals, reap zombie children, and forward the logs.
  - similarly, the subprocess (app) should still execute when it fails to connect to Stackdriver.

For now we can try adding to 1-2 more services but I don’t think the Profiler support is ready for everything yet. Feel free to chat @-mtwo about this.

**Comment by DanSanche** [comment]
Hmm it looks like profiling is already enabled in at least 8 services. Should I be working on adding polish/fixing todos? Or what else needs to be done here before this can be closed out?

**Comment by ahmetb** [comment]
Can you list which ones so we can mark them?
I think we can keep the bug open as a documentation of the support for profiler.

**Comment by DanSanche** [comment]
Current status: All services are supported except `cartservice`, because C# isn't yet supported by Profiler. `recommendationservice` and `emailservice` must be turned on by adjusting an environment variable in the kubernetes manifest.

I'm happy to look more at this issue if there are outstanding issues, but so far it looks good to me

**Comment by ahmetb** [comment]
That’s actually really good. Maybe we should add a section to the readme on how to configure the profiler.

**Comment by ahmetb** [comment]
That’s actually really good. Maybe we should add a section to the readme on how to configure the profiler.

**Comment by DanSanche** [comment]
Closing this and other `kind/improvement` issues as we attempt to move the project into a stable maintenance state
