### ISSUE TITLE
Pod recommendationservice-78965f984b is looping in CrashLoopBackOff state

### ISSUE THREAD

**Issue by Plat0nicS0lid** [GoogleCloudPlatform/microservices-demo#528]
Hi,
trying to start microservices-demo on minikube, but the pod recommendationservice-78965f984b is in CrashLoopBackOff state.

Minikube has 6 Cpus and 8192 Memory.

kubectl get nodes
NAME       STATUS   ROLES                  AGE   VERSION
minikube   Ready    control-plane,master   21m   v1.20.2

kubectl get pods
NAME                                     READY   STATUS             RESTARTS   AGE
adservice-f787c8dcd-fdnfv                1/1     Running            0          10m
cartservice-67b89ffc69-cbdc4             1/1     Running            3          10m
checkoutservice-75db8bf6f6-vxgjk         1/1     Running            0          10m
currencyservice-68887d98fd-sw8kd         1/1     Running            0          10m
emailservice-5f8fc7dbb4-fzr5g            1/1     Running            0          10m
frontend-5c4745dfdb-8spm5                1/1     Running            0          10m
loadgenerator-86f46dcb88-4jxt6           1/1     Running            5          10m
paymentservice-6658569876-n6t5d          1/1     Running            0          10m
productcatalogservice-587f8bc64-7kjvm    1/1     Running            0          10m
recommendationservice-78965f984b-rqqpm   0/1     CrashLoopBackOff   7          10m
redis-cart-74594bd569-6qdmf              1/1     Running            0          10m
shippingservice-6998959488-knb84         1/1     Running            0          10m

kubectl logs recommendationservice-78965f984b-rqqpm
{"timestamp": 1617793064.1957085, "severity": "INFO", "name": "recommendationservice-server", "message": "initializing recommendationservice"}
{"timestamp": 1617793064.1959376, "severity": "INFO", "name": "recommendationservice-server", "message": "Profiler enabled."}
{"timestamp": 1617793070.8317711, "severity": "INFO", "name": "recommendationservice-server", "message": "Unable to start Stackdriver Profiler Python agent. Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started"}
{"timestamp": 1617793070.832098, "severity": "INFO", "name": "recommendationservice-server", "message": "Sleeping 10 seconds to retry Stackdriver Profiler agent initialization"}

kubectl describe pod recommendationservice-78965f984b-rqqpm   
Name:         recommendationservice-78965f984b-rqqpm
Namespace:    default
Priority:     0
Node:         minikube/192.168.99.115
Start Time:   Wed, 07 Apr 2021 12:43:40 +0200
Labels:       app=recommendationservice
              pod-template-hash=78965f984b
Annotations:  <none>
Status:       Running
IP:           172.17.0.7
IPs:
  IP:           172.17.0.7
Controlled By:  ReplicaSet/recommendationservice-78965f984b
Containers:
  server:
    Container ID:   docker://835e73f7c29fee9c50aff7b9a0ccdca23ae45d2066f063aafac62b2ee98cdb6b
    Image:          gcr.io/google-samples/microservices-demo/recommendationservice:v0.2.2
    Image ID:       docker-pullable://gcr.io/google-samples/microservices-demo/recommendationservice@sha256:ffc4bc50561db6137a2ae917155ad3568cc8a815a4b031b59a241993602bc285
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Wed, 07 Apr 2021 12:57:39 +0200
      Finished:     Wed, 07 Apr 2021 12:57:59 +0200
    Ready:          False
    Restart Count:  9
    Limits:
      cpu:     200m
      memory:  450Mi
    Requests:
      cpu:      100m
      memory:   220Mi
    Liveness:   exec [/bin/grpc_health_probe -addr=:8080] delay=0s timeout=1s period=5s #success=1 #failure=3
    Readiness:  exec [/bin/grpc_health_probe -addr=:8080] delay=0s timeout=1s period=5s #success=1 #failure=3
    Environment:
      PORT:                          8080
      PRODUCT_CATALOG_SERVICE_ADDR:  productcatalogservice:3550
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-plhpd (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-plhpd:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-plhpd
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  <unknown>                              Successfully assigned default/recommendationservice-78965f984b-rqqpm to minikube
  Normal   Pulling    16m                 kubelet, minikube  Pulling image "gcr.io/google-samples/microservices-demo/recommendationservice:v0.2.2"
  Normal   Pulled     15m                 kubelet, minikube  Successfully pulled image "gcr.io/google-samples/microservices-demo/recommendationservice:v0.2.2" in 47.638892456s
  Normal   Started    14m (x2 over 15m)   kubelet, minikube  Started container server
  Warning  Unhealthy  14m (x6 over 15m)   kubelet, minikube  Liveness probe failed:
  Normal   Killing    14m (x2 over 14m)   kubelet, minikube  Container server failed liveness probe, will be restarted
  Normal   Created    14m (x3 over 15m)   kubelet, minikube  Created container server
  Normal   Pulled     14m (x2 over 14m)   kubelet, minikube  Container image "gcr.io/google-samples/microservices-demo/recommendationservice:v0.2.2" already present on machine
  Warning  Unhealthy  10m (x26 over 15m)  kubelet, minikube  Readiness probe failed:
  Warning  BackOff    59s (x56 over 13m)  kubelet, minikube  Back-off restarting failed container

Help needed to bring it online.

Many thanks and best regards,
Sascha

**Comment by askmeegs** [comment]
Hello, because you're running this on minikube, you either need to set up GOOGLE_APPLICATION_CREDENTIALS or disable tracing, profiling, metrics.

See: 
https://github.com/GoogleCloudPlatform/microservices-demo/issues/457#issuecomment-741928978 

+ we have an open issue to improve instructions for non GKE environments trying to communicate with GCP APIs. 
https://github.com/GoogleCloudPlatform/microservices-demo/issues/359
