### ISSUE TITLE
Do we have OpenAPI (Swagger) spec for the applications

### ISSUE THREAD

**Issue by sagarpatil23192** [GoogleCloudPlatform/microservices-demo#532]
Do we have OpenAPI (Swagger) spec for all the API's in the applications? If yes please help me with that. I will be needing it to create a Service Profile using Linkerd

**Comment by ahmetb** [comment]
I don't think we have Swagger specs for any, as all services use gRPC/Protobuf.

**Comment by sagarpatil23192** [comment]
@ahmetb If we have a protobuf format for all the services if will be helpful

**Comment by ahmetb** [comment]
Proto files are available in the repository.
