### ISSUE TITLE
Enable tracing using Jaegar 

### ISSUE THREAD

**Issue by sagarpatil23192** [GoogleCloudPlatform/microservices-demo#533]
For doing this we just need to uncomment JAEGER_SERVICE_ADDR env in the deployment manifest and provide the correct value that's it??

Also, I read a few issues which stated tracing feature is not enabled for all the micro-services. So just to confirm we have it enabled for all the microservices right

**Comment by sagarpatil23192** [comment]
Also, I checked the issue: https://github.com/GoogleCloudPlatform/microservices-demo/issues/198 where it stats using oc_agent. Need clarification on the usage

**Comment by sagarpatil23192** [comment]
We have integrated this application with linkerd and using linked's jaeger integration for tracing. I edited the JAEGER_SERVICE_ADDR env in the respective deployment manifest and deployed the application. I check the logs for all the applications which integrate with jeager and get the message
{"message":"jaeger initialization completed.","severity":"info","timestamp":"2021-04-21T04:56:59.376363674Z"}
But I am not able to view the services on the Jeager UI in the service drop down. But I can get the traces via the linker-proxy operations tab.

**Comment by sagarpatil23192** [comment]
Just an update the Initialization for jaeger is successful. But all the applications sending the traces to jaeger are having same error logs:
 Error when uploading spans to Jaeger: failed to upload traces; HTTP status code: 404

**Comment by sagarpatil23192** [comment]
Treid setting the env JAEGER_SERVICE_ADDR to "collector.linkerd-jaeger:55678" and also "collector.linkerd-jaeger:55678/api/traces" but same outcome. Same error as above

**Comment by sagarpatil23192** [comment]
The 404 got fixed as I was using the wrong port. Setting the env JAEGER_SERVICE_ADDR  to "collector.linkerd-jaeger:14268" worked and I am able to see the services in the Service drop down on the Jaeger UI. But as mentioned in the issue https://github.com/GoogleCloudPlatform/microservices-demo/issues/385 for the process in any trace the tags are always blank. I am sending spans from multiple clusters to a central jaeger so I can't identify from which pod is the trace coming from

**Comment by bourgeoisor** [comment]
Hello! It seems like your questions got answered and that you're getting the same issue as https://github.com/GoogleCloudPlatform/microservices-demo/issues/385
I will be closing this ticket in favour of the former to resolve the duplicate.
