### ISSUE TITLE
Add kustomize support

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/microservices-demo#536]
Add Kustomize base + overlay structure to replace the following -- 

- hack script that produces kubernetes-manifests -->  release/kubernetes-manifests workflow (use kustomize to inject image tag + generate manifests) 

This will enable teams that need to customize the manifests, allowing them to either contribute their own overlay upstream, or fork the repo + build an overlay there.

**Comment by bourgeoisor** [comment]
This is planned and in our roadmap for 2022.

**Comment by bourgeoisor** [comment]
This is still planned, but we are looking into Bank of Anthos first. Commenting to reset SLO.

**Comment by bourgeoisor** [comment]
@NimJay with https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/kustomize having merged upstream, could you describe what is left to be done for this issue -- for example a list of pending action items?

**Comment by NimJay** [comment]
Thanks for bringing this up, Olivier.
I believe there's a few things we need to do:
1. Add automation inside of the existing release automation ([`/hack/make-release-artifacts.sh`](https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/hack/make-release-artifacts.sh#L63)) to generate the `/kustomize/base/` folder. More details can be found in [this comment](https://github.com/GoogleCloudPlatform/microservices-demo/pull/937#issuecomment-1206609480).
2. Go through the flavours inside [`docs/`](https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/docs) and identify which flavours need to be ported to Kustomize. I believe it's just the following we still need to worry about:
    1. [/docs/service-mesh.md](https://github.com/GoogleCloudPlatform/microservices-demo/blob/release/v0.3.9/docs/service-mesh.md)
    2. [/docs/network-policies](https://github.com/GoogleCloudPlatform/microservices-demo/tree/release/v0.3.9/docs/network-policies)
    3. [/docs/workload-identity.md](https://github.com/GoogleCloudPlatform/microservices-demo/blob/release/v0.3.9/docs/workload-identity.md) (we'd just be replacing the `sed` command in step 3)
4. Create a Kustomize component (inside `/kustomize/components/`) for each flavour identified in step 2. I've started work on porting over the `NetworkPolicy` flavour in https://github.com/GoogleCloudPlatform/microservices-demo/pull/1081.

**Comment by mathieu-benoit** [comment]
Closing this one as Kustomize is now officially documented and supported here: https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/kustomize.

Let's add more variations/overlays by directly opening associated and specific PRs.
