### ISSUE TITLE
 How do I integrate registries with these microservices

### ISSUE THREAD

**Issue by zhaocheng173** [GoogleCloudPlatform/microservices-demo#544]

**Comment by bourgeoisor** [comment]
Hi @zhaocheng173, thank you for your question. Could you provide us with more details on what exactly you're trying to accomplish so we can help you further?

**Comment by askmeegs** [comment]
Hello @zhaocheng173, thank you for opening this issue but I think we need a bit more context. Closing this issue for now; feel free to reopen with details.
