### ISSUE TITLE
LoadBalancer vs Ingress resource type

### ISSUE THREAD

**Issue by ocervell** [GoogleCloudPlatform/microservices-demo#548]
I noticed we're using the `LoadBalancer` type for the `frontend` service YAML [here](https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/kubernetes-manifests/frontend.yaml#L105) which is the only external-facing entry point.

Any idea why we're not using `Ingress` k8s type instead ? 

As a reminder, `Ingress` type - on most Clouds - will create an external HTTP(s) load balancer, while `LoadBalancer` will create an external TCP load balancer, which I often find less appropriate for an e-commerce / web platform (e.g for observability, you don't get the request count metric from a TCP LB, but just the number of TCP packets going through it, which makes it harder to set up SLOs for instance).

Thanks !

**Comment by ahmetb** [comment]
Historical reason was that:

1. ingress doesn't work locally
2. ingress takes very long (10-20 mins) to be ready on GKE as it's a global GCLB.

Neither was really attractive. But you can always add one in your local setup/fork.

**Comment by askmeegs** [comment]
I second @ahmetb's second point - for demo purposes, services of type loadbalancer spin up faster. 
That said, we do have Ingress resources in the repo -- https://github.com/GoogleCloudPlatform/microservices-demo/tree/master/.github/master-cluster which we use to map the onlineboutique.dev domain to a "production" instance of this app.  Feel free to use these.
