### ISSUE TITLE
Concurrency issues

### ISSUE THREAD

**Issue by lyr5333** [GoogleCloudPlatform/microservices-demo#569]
I use JMeter to test only 2800tps. I see that redis uses Redis: alpine Is there a bottleneck in Redis. How can concurrency be improved? Thank you very much!

**Comment by askmeegs** [comment]
Hello, could you please provide some more details on what you mean by "bottleneck?" 

When you're load testing with JMeter, what problems are you seeing?

**Comment by askmeegs** [comment]
Hello, I'm going to close this issue for now due to not enough information about the problem. Feel free to reopen with additional context + logs. Thanks!
