### ISSUE TITLE
image build time doubled after image size optimizations

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#58]
Below is a snapshot of the build times listed at https://travis-ci.com/GoogleCloudPlatform/microservices-demo/builds.

It looks like after merging PRs

1. #51 emailservice image optimization
2. #52 loadgenerator image optimizations

the build times has risen from 12 minutes on average to 22 minutes (after #51), and then to **26 minutes** (after #52).

So we're probably providing a faster image push experience, but now the overall build time has doubled. I assume we're probably now serving the developers with high upload bandwidths worse.

![image](https://user-images.githubusercontent.com/159209/46177282-2ef49100-c267-11e8-8043-1d2efac50488.png)

cc: @orthros

**Comment by orthros** [comment]
I've been taking a look at this, and the biggest time sink is actually `pip install grpcio grpcio-tools`. 

On my local machine this can take upwards of 8 minutes on alpine. I'm currently in the process of submitting some PRs to the gRPC team that will give `slim` and `alpine` images for python, which we can then use as the base for `loadgenerator` and `emailservice`

**Comment by orthros** [comment]
I've opened PRs with the gRPC docker images repository to better fill out their options

* [New library for grpcio 1.12.1](https://github.com/grpc/grpc-docker-library/pull/64)
* [Alpine for existing libraries](https://github.com/grpc/grpc-docker-library/pull/62)
* [Python-slim based images](https://github.com/grpc/grpc-docker-library/pull/62/files)

**Comment by orthros** [comment]
Opened additional PRs with the gRPC docker images repository in the event we want to upgrade gRPC versions

* [Added Python 1.14.* images](https://github.com/grpc/grpc-docker-library/pull/66)
* [Added Python 1.15.0 images](https://github.com/grpc/grpc-docker-library/pull/65)

**Comment by orthros** [comment]
Okay. If/when my PRs are merged I'll retool our python services to update to 1.15 and update images appropriately.

**Comment by ahmetb** [comment]
#120 solved this by moving back to glibc based images for Python services and cleaning up requirements.txt files.
