### ISSUE TITLE
Missing Trace Header Propagation?

### ISSUE THREAD

**Issue by therealmitchconnors** [GoogleCloudPlatform/microservices-demo#582]
When I install the Hipster Shop with Istio, and open a Jaeger dashboard, all my traces have only 2 spans (origin and destination).  I believe this is because the hipster microservices are not properly forwarding trace headers, as documented at https://istio.io/latest/docs/tasks/observability/distributed-tracing/overview/#trace-context-propagation.

This application would showcase Tracing much better if you could trace traffic from ingress all the way to backend services.

**Comment by ahmetb** [comment]
This tool does trace context propagation, as I know the folks at Istio team validated their integration with Stackdriver Trace (now called Google Cloud Trace) using this demo application.

However, the processes are not implemented to upload traces to Jaeger; only to Google Cloud Trace. (Browse the source code of any service, you'll see it attempts to connect to GCP to initialize a trace exporter.) That's probably why you're only seeing traces from the ingress and not from the individual applications.

**Comment by therealmitchconnors** [comment]
Maybe I should clarify.  I can see that several of the microservices in hipster shop propagate their own trace spans to Cloud Trace.  However, Istio is designed to add consistent trace spans across all services in a service mesh with no change to the service's implementation.  It does this by capturing all traffic in and out of the pod, and sending the relevant data to whichever tracing service the user configures (in this case, I've configured Istio to use Jaeger).

One caveat to this operation is that Istio cannot match outbound requests from a service to the inbound requests which caused them, as at any time the service may be handling many inbound requests.  For this reason, services need to propagate the headers listed in the link above so that Istio can properly connect the trace spans.  This is completely separate from traces which the application sends itself, useful though they may be.

**Comment by ahmetb** [comment]
As far as I know (and historically made sure of it), this app picks up and propagates the trace IDs originating from Istio correctly, but it only exports them to Cloud Trace. We demoed this capability on stage at Next'18 Keynote (see Melody/Morgan's segment).

Maybe the trace context header convention has changed since then, but I doubt that's the case.

**Comment by bourgeoisor** [comment]
Closing this issue has it's been >6 months since the last comment. Feel free to reopen if this is still relevant!
