### ISSUE TITLE
Unable to run this service on Local Kubeadm k8s cluster 

### ISSUE THREAD

**Issue by Jayashankara-DM-135** [GoogleCloudPlatform/microservices-demo#585]
$ sudo kubectl get pod
sudo: unable to resolve host k8s-master-node: Connection timed out
NAME                                     READY   STATUS                  RESTARTS   AGE
adservice-5844cffbd4-k2m5k               0/1     Running                 4          4m56s
cartservice-fdc659ddc-b2qsc              0/1     CrashLoopBackOff        5          4m57s
checkoutservice-64db75877d-n29bj         1/1     Running                 0          4m58s
currencyservice-9b7cdb45b-4f8xm          1/1     Running                 0          4m57s
emailservice-64d98b6f9d-brds5            1/1     Running                 0          4m58s
frontend-76ff9556-l4xb5                  1/1     Running                 0          4m57s
loadgenerator-589648f87f-vzl8v           0/1     Init:ImagePullBackOff   0          4m57s
paymentservice-65bdf6757d-lm8hc          1/1     Running                 0          4m57s
productcatalogservice-5cd47f8cc8-wpx84   1/1     Running                 0          4m57s
recommendationservice-b75687c5b-xv9b9    0/1     CrashLoopBackOff        6          4m58s
redis-cart-74594bd569-n879h              0/1     ImagePullBackOff        0          4m57s
shippingservice-778554994-7dndz          1/1     Running                 0          4m57s

$ 
$ sudo kubectl get service frontend-external | awk '{print $4}'
sudo: unable to resolve host k8s-master-node: Connection timed out
EXTERNAL-IP
<pending>
$ 

Can you please share steps to run this app on Kubeadm cluster.

**Comment by ahmetb** [comment]
The error messages look like your Kubernetes setup is broken. Try `kubectl get nodes` and it probably won't work either.

**Comment by Jayashankara-DM-135** [comment]
No, I can get nodes details.
$ sudo kubectl get nodes
sudo: unable to resolve host k8s-master-node: Connection timed out
NAME                STATUS   ROLES    AGE    VERSION
k8s-master-node     Ready    master   126m   v1.19.2
k8s-worker-node-1   Ready    <none>   125m   v1.19.2

$

**Comment by Jayashankara-DM-135** [comment]
Looks to issue with pulling redis image. Not sure why redis image pull is failing.

$ sudo kubectl describe pod redis-cart-74594bd569-n879h
sudo: unable to resolve host k8s-master-node: Connection timed out
Name:         redis-cart-74594bd569-n879h
Namespace:    default
Priority:     0
Node:         k8s-worker-node-1/10.0.2.6
Start Time:   Fri, 06 Aug 2021 23:15:49 +0530
Labels:       app=redis-cart
              pod-template-hash=74594bd569
Annotations:  cni.projectcalico.org/podIP: 192.168.148.152/32
              cni.projectcalico.org/podIPs: 192.168.148.152/32
Status:       Pending
IP:           192.168.148.152
IPs:
  IP:           192.168.148.152
Controlled By:  ReplicaSet/redis-cart-74594bd569
Containers:
  redis:
    Container ID:   
    Image:          redis:alpine
    Image ID:       
    Port:           6379/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     125m
      memory:  256Mi
    Requests:
      cpu:        70m
      memory:     200Mi
    Liveness:     tcp-socket :6379 delay=0s timeout=1s period=5s #success=1 #failure=3
    Readiness:    tcp-socket :6379 delay=0s timeout=1s period=5s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /data from redis-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-hk6bh (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  redis-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  default-token-hk6bh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-hk6bh
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  43m                    default-scheduler  Successfully assigned default/redis-cart-74594bd569-n879h to k8s-worker-node-1
  Warning  Failed     42m                    kubelet            Failed to pull image "redis:alpine": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.43.1:53: read udp 10.0.2.6:39693->192.168.43.1:53: i/o timeout
  Warning  Failed     42m                    kubelet            Failed to pull image "redis:alpine": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.43.1:53: read udp 10.0.2.6:44198->192.168.43.1:53: i/o timeout
  Warning  Failed     41m                    kubelet            Failed to pull image "redis:alpine": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.43.1:53: read udp 10.0.2.6:57349->192.168.43.1:53: i/o timeout
  Normal   Pulling    40m (x4 over 43m)      kubelet            Pulling image "redis:alpine"
  Warning  Failed     40m (x4 over 42m)      kubelet            Error: ErrImagePull
  Warning  Failed     40m                    kubelet            Failed to pull image "redis:alpine": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.43.1:53: read udp 10.0.2.6:55585->192.168.43.1:53: i/o timeout
  Warning  Failed     7m55s (x142 over 42m)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    2m59s (x163 over 42m)  kubelet            Back-off pulling image "redis:alpine"
jmallesh@k8s-master-node:~/microservices-demo$
