### ISSUE TITLE
Instrument all services with Stackdriver debugger

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#6]
- [ ] adservice
- [ ] cartservice
- [ ] checkoutservice
- [x] currencyservice
- [x] emailservice
- [ ] frontend
- [x] paymentservice
- [ ] productcatalogservice
- [x] recommendationservice
- [ ] shippingservice

**Comment by DanSanche** [comment]
What are your thoughts on having the source code automatically appear in the debugger? Right now users have to manually link to the hipstershop repo in the Cloud Console. We could have it appear automatically by embedding a `[source-context.json] file(https://cloud.google.com/debugger/docs/source-context)` that points to this repo's HEAD in each service's container. I think it's a bit hacky and could lead to confusion, but it is an option

**Comment by DanSanche** [comment]
There may be some issues getting this running with the golang services
- It seems like it expects default credentials, so it may cause issues when running locally
- even on GKE, I was running into [this issue](https://github.com/googleapis/google-cloud-go/issues/1079) when setting breakpoints. I'm not sure if there's a good workaround.

**Comment by DanSanche** [comment]
Closing this and other `kind/improvement` issues as we attempt to move the project into a stable maintenance state
