### ISSUE TITLE
load balancer failure in context of GCP tutorial on Kubernetes

### ISSUE THREAD

**Issue by tspyrou** [GoogleCloudPlatform/microservices-demo#601]
![image](https://user-images.githubusercontent.com/46945466/134700114-c0e9bd88-5b57-4876-856e-d91a87057ab9.png)

I am learning GCP Kubernetes and was wondering if this is a known issue with the tutorial.

**Comment by donmccasland** [comment]
Hey there!  Thanks for flagging this.  Can you point us to the tutorial you were using when you ran into it?

**Comment by bourgeoisor** [comment]
I've deployed `microservices-demo` using the same steps as the [GKE Quickstart](https://console.cloud.google.com/getting-started?tutorial=gke_quickstart) and [GKE Autopilot Quickstart](https://console.cloud.google.com/getting-started?tutorial=gke_autopilot) tutorials and haven't been able to replicate this failed event. In both scenarios, I see the LB getting created correctly:

```
kubectl describe service/frontend-external
. . .
. . .
Events:
  Type    Reason                Age   From                Message
  ----    ------                ----  ----                -------
  Normal  EnsuringLoadBalancer  2m6s  service-controller  Ensuring load balancer
  Normal  EnsuredLoadBalancer   79s   service-controller  Ensured load balancer
```

Screenshot from Cloud Code:
![image](https://user-images.githubusercontent.com/3271352/134840778-62f7c169-084e-4d41-8009-8847f1853311.png)


Could you describe the steps needed to reproduce this issue?

**Comment by NimJay** [comment]
Hi @tspyrou. 🙂

Are you able to provide the full error message?
```
Error syncing load balancer: ...
```

I am wondering if it was a quota issue (see [relevant Reddit post](https://www.reddit.com/r/googlecloud/comments/lxi9wv/error_syncing_load_balancer/))?
