### ISSUE TITLE
Additional Cymbal Front-end Tweaks

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/microservices-demo#614]
* #574 was completed in Sept 2021.
* Related to #574, the Cymbal team suggested a few additional improvements in Oct 2021 that might be worth adding:
  - [ ] "Hover" and "press" states for buttons (see [Google-internal Figma comment](https://www.figma.com/file/UlhTLEvRFIw8vK5wAzD7Vq?node-id=208%3A1456&fuid=992140796602883105#120736975))
  - [x] "Online Boutique" logo color change (see [Google-internal Figma comment](https://www.figma.com/file/UlhTLEvRFIw8vK5wAzD7Vq?node-id=6%3A14&fuid=992140796602883105#120474333))

**Comment by bourgeoisor** [comment]
@NimJay is this issue still active?

**Comment by NimJay** [comment]
@bourgeoisor Thanks for bring my attention to this. :)

This ticket is very low priority.
Next time this ticket reaches out-of-SLO, let's definitely close it.
I'll leave it open for now in case someone wants a fun, easy ticket to work on.
Definitely a good beginner ticket — so I've just added the "good first issue" label.
I'll add screenshots (for anyone without access to the Figma prototypes) of the changes to be made. :)

**1. Button States**
<img width="597" alt="Screen Shot 2022-05-10 at 9 45 27 AM" src="https://user-images.githubusercontent.com/10292865/167643360-4a599f92-bcc3-428b-8a10-336db334a462.png">

**2. Logo**
<img width="979" alt="Screen Shot 2022-05-10 at 9 54 11 AM" src="https://user-images.githubusercontent.com/10292865/167645266-43993141-1c79-445a-991b-0a48a21c0dae.png">
