### ISSUE TITLE
Upgrade Istio manifest apiVersion

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/microservices-demo#617]
* The Istio manifests (`.yaml` files) currently use `apiVersion: networking.istio.io/v1alpha3`.
https://github.com/GoogleCloudPlatform/microservices-demo/blob/884439c7437cab8d66da4657d8043278e01c33dc/istio-manifests/frontend.yaml#L15
* We want to upgrade the `apiVersion` to `networking.istio.io/v1beta1`.
* According to [this discuss.istio.io thread](https://discuss.istio.io/t/is-api-version-networking-istio-io-v1alpha3-considered-to-be-deprecated-on-1-5-0/7278), there is no difference in behaviour.
  * But we should still test the [Deploying to an Istio-enabled cluster](https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/docs/service-mesh.md) instructions.

**Comment by NimJay** [comment]
I have deprioritized this issue from `p2` to `p3` because another Googler suggested that this might be a waste of time because `v1alpha3` and `v1beta3` are identical.

**Comment by ckim328** [comment]
cooling down from oslo!
