### ISSUE TITLE
service name change

### ISSUE THREAD

**Issue by ezemegwara** [GoogleCloudPlatform/microservices-demo#623]
I want to rename some services for test I am working on in Linkerd, so  instead of using `adservice` in services.yaml, I will have `adservice-east`. so the `frontend` will send request to `adservice-east` instead of `adservice`

I am not a GO programmer, I would be grateful if anybody can point me where this can be done in the `frontservice` source code

**Comment by askmeegs** [comment]
Hello! The backend addresses are configurable in the frontend Deployment YAML. You should not have to change any of the frontend go code.
https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/kubernetes-manifests/frontend.yaml#L68
