### ISSUE TITLE
Indicate Cloud Region/Location in Front-end

### ISSUE THREAD

**Issue by alizaidis** [GoogleCloudPlatform/microservices-demo#628]
Adding tutorial to showcase this application running in a multi-cluster, multi-region setup. Need an easy way for the user to tell the location/region of the pod responding to the client request.

Working on a fix for this. PR incoming shortly.

**Comment by askmeegs** [comment]
Thanks Ali! You may be able to port what we have for this in the Bank of Anthos app. 
https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/master/src/frontend/frontend.py#L68

**Comment by askmeegs** [comment]
Note to whoever takes this -- let's do cluster, region, and zone for good measure.
If not GKE, list "unknown" for now.

**Comment by Shabirmean** [comment]
@alizaidis  This is fixes in https://github.com/GoogleCloudPlatform/microservices-demo/pull/636
