### ISSUE TITLE
Jaeger Trace shows only 2 spans per trace

### ISSUE THREAD

**Issue by SapnaGirdhani1** [GoogleCloudPlatform/microservices-demo#635]
Hi Team,

When I try to trace requests to Online Boutique Application , I can see multiple traces with two spans each. Transaction does not come as single trace. For example, If I hit the application and add a product in cart. I can see multiple traces in Jaeger - loadgenerator to frontend , frontend to productcatalog, frontend to currency and so on. There is no single trace for one transaction. 
Please help me on the same. Thanks!
![GoogleApp_Jaeger](https://user-images.githubusercontent.com/79440049/143422378-773cda8b-ca71-4246-8de5-30524b387780.png)

**Comment by Fengrui-Liu** [comment]
Same problem!

**Comment by bourgeoisor** [comment]
@NimJay do you know if this is intentional design, or a bug?

**Comment by NimJay** [comment]
Sorry, I'm not too familiar with Jaegar (and logging best practices).

I'm [reading up on spans and traces now](https://www.aspecto.io/blog/jaeger-tracing-the-ultimate-guide/#:~:text=A%20span%20represents%20an%20action%20(HTTP%20request%2C%20call%20to%20a%20DB%2C%20etc)%20and%20is%20Jaeger%E2%80%99s%20most%20basic%20unit%20of%20work.).

If I understand correctly, a "span" would be a single HTTP/gRPC request, and a "trace" is a set of requests that are related.
And ideally, on Online Boutique, there would be a "trace" for every user action (e.g., when the user pays for their cart), and all the related "spans" would be labelled with the correct "trace" id.
Am I on the right track?

I'm looking at old GitHub PRs relevant to tracing (e.g., [this](https://github.com/GoogleCloudPlatform/microservices-demo/pull/55)), and I can't seem to find anything about implementing what I've described in the previous paragraph.

I wonder if this will be addressed when we come around to implement OpenTelemetry.
I also wonder if this is something Leonid could provide some guidance on.

**Comment by NimJay** [comment]
CC: @arbrown (in case you had some thoughts)
More specifically, did you have thoughts about the best practices for organizing spans? 
Also, is my understanding correct (from my previous comment)?

**Comment by minherz** [comment]
@SapnaGirdhani1 can you please confirm that the trace id for all these entries is the same while the span ids are different?
Looking at the code I see that the OpenCensus framework is currently used to generate tracing logs in `frontend` and `productcatalog` while `currencyservice` uses Cloud Tracing client library. Getting your answer will help render out possible option that the trace id does not propagate between the calls.

**Comment by arbrown** [comment]
Traces will be overhauled when we fix #422, and we consolidate traces from OpenCensus/Cloud tracing to be all OTel.

**Comment by ahrarmonsur** [comment]
@SapnaGirdhani1 requesting more information to help us resolve the issue for you.

Additionally, bringing visibility to an initiative under consideration to remove Jaeger from `microservices-demo` repo in favor of showcasing Google Cloud Operations.
https://github.com/GoogleCloudPlatform/microservices-demo/issues/947

**Comment by mathieu-benoit** [comment]
FYI: Jaeger support will be removed by #1088.

**Comment by mathieu-benoit** [comment]
Closing this one as Jaeger has been removed from the project: https://github.com/GoogleCloudPlatform/microservices-demo/pull/1088, coming in 0.3.10.
