### ISSUE TITLE
misspelled RecommendationService in architecture

### ISSUE THREAD

**Issue by fty4** [GoogleCloudPlatform/microservices-demo#650]
### Issue
The `RecommendationService` is misspelled in the architecture image.

Instead of writing _recommendation_ with two `m`´s its only one.

### To Reproduce 
1. open https://github.com/GoogleCloudPlatform/microservices-demo/blob/f703536128463e1327bd67f30e9bdb7160e7931b/docs/img/architecture-diagram.png

### Screenshots 
<img width="350px" src="https://user-images.githubusercontent.com/16336640/145055151-86e1fc01-18fd-4137-bafa-fbb9f0ebe72d.png"/>

### Additional context 
Unfortunately there is no SVG provided to create a PR by myself.

**Comment by mathieu-benoit** [comment]
Thanks for raising this, it's now fixed with the new architecture diagram: https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/docs/img/architecture-diagram.png
