### ISSUE TITLE
Shipping cost zeroes with large product quantities

### ISSUE THREAD

**Issue by Pawlaklis** [GoogleCloudPlatform/microservices-demo#690]
### Describe the bug 
When adding large quantities of products to Cart shipping costs zeroes because of integer overflow.

### To Reproduce 
1. Add at more than about 195 products to Cart. 
2. Shipping cost turns to 0, 

### Screenshots 

![obraz](https://user-images.githubusercontent.com/55978132/150113130-993a9980-a7e7-4bfb-a589-60070824f57d.png)

**Comment by ahrarmonsur** [comment]
Related to https://github.com/GoogleCloudPlatform/microservices-demo/issues/691, both requiring a fix to the shipping cost calculator.

**Comment by NimJay** [comment]
Thanks for finding this as well, @Pawlaklis! :)
Fixed by @ckim328 in #694. 👏 

I've tested with 200 sunglasses:
<img width="550" alt="Screen Shot 2022-01-20 at 2 02 53 PM" src="https://user-images.githubusercontent.com/10292865/150404890-7be9069e-83c5-4505-b302-16fe00df3209.png">
