### ISSUE TITLE
Fix shipping cost calculation formula

### ISSUE THREAD

**Issue by Pawlaklis** [GoogleCloudPlatform/microservices-demo#691]
### Describe the bug 
Right now the cost of shipping is calculated using formula
<img src="https://latex.codecogs.com/svg.image?price&space;=&space;n&plus;3^{1&plus;\frac{n}{5}}" title="price = n+3^{1+\frac{n}{5}}" />

Because of that the costs grows exponential with number of products which is not only very unusual way to calculate shipping but also creates absurdly large numbers.

### To Reproduce 
Example: When buying 50 T-shirts (which costs $949.50) the shipping price is $177196.99 which is 190 times more that price of products.

### Screenshots 
![Screenshot 2022-01-17 at 19-32-24 Online Boutique](https://user-images.githubusercontent.com/55978132/150124219-6b2e1ea1-4721-4249-abbc-df9a9a843039.png)

### Possible solution
Calculate the cost as flat number not dependant on quantity of bought products.

**Comment by NimJay** [comment]
Thanks for point this out, @Pawlaklis!
@ckim328 has gone ahead and created a solution in #694.
We're just using a fixed shipping cost now to _keep things simple_.
