### ISSUE TITLE
Remove use of `latest` tag

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/microservices-demo#696]
## Background

* We want to remove use of the `latest` tag throughout this repository.
* See this [Google-internal bug](https://buganizer.corp.google.com/issues/215517944).
* We are using the `latest` tag in the `main` branch's GitHub Action called "Push and Deploy":
https://github.com/GoogleCloudPlatform/microservices-demo/blob/e1c04f89be61b9af59f6a277539757675b1a60df/.github/workflows/push-deploy.yaml#L33-L35

## Task

- [x] Create a pull-request to remove the above snippet of code.
- [x] Make sure the "Push and Deploy" GitHub Action still works.

**Comment by bourgeoisor** [comment]
We'd need to also make sure we're not breaking any existing deployment that uses `latest` (in a post-log4j-cve-world of course). I think we should still do this but would like to chat about it a bit.

**Comment by mahi072** [comment]
Hi, I would like to work on this issue.

**Comment by vaishnavi-ramanujapuram** [comment]
Hi @NimJay , I have gone through this repository and would like to work on this issue. Do I just need to remove the latest tag and wherever there's a use of latest tag ?

**Comment by NimJay** [comment]
@vaishnavi-ramanujapuram, 
I believe you can remove these 3 lines completely:
```
        # tag as latest
        skaffold build --default-repo=gcr.io/$PROJECT_ID \
                       --tag=latest
```
from [`/.github/workflows/push-deploy.yaml`](https://github.com/GoogleCloudPlatform/microservices-demo/blob/release/v0.4.2/.github/workflows/push-deploy.yaml).

I don't think those images are used by anyone, anywhere.

If someone wants to use Online Boutique container images, they should use images with explicit version (for instance, [adservice:v0.4.2](https://github.com/GoogleCloudPlatform/microservices-demo/blob/release/v0.4.2/kustomize/base/adservice.yaml#L44)) — not `adservice:latest`.

We should **keep** the 3 lines above it though:
```
        # tag with git hash
        skaffold build --default-repo=gcr.io/$PROJECT_ID \
                       --tag=$GITHUB_SHA
```
so that we're testing the `skaffold build`-ing of each Online Boutique service, per commit made to the `main` branch.

Hope this helps. :)

**Comment by vaishnavi-ramanujapuram** [comment]
Thank you @NimJay , i'll make the changes and submit the PR.

**Comment by vaishnavi-ramanujapuram** [comment]
@NimJay , i've raised the PR. Please review it and let me know if I need to make any changes.
Remove latest tag #1394

**Comment by vaishnavi-ramanujapuram** [comment]
Also, could you please assign me this as it is part of my academics.

**Comment by vaishnavi-ramanujapuram** [comment]
@NimJay Thank you for merging my PR. Can you please let me know when this issue will be closed.

**Comment by NimJay** [comment]
Sorry for the late response, @vaishnavi-ramanujapuram!
But thanks again for https://github.com/GoogleCloudPlatform/microservices-demo/pull/1394.
I will now close this GitHub Issue.
