### ISSUE TITLE
Remove `semistandard`

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/microservices-demo#712]
### Describe request or inquiry 
* Both Node.js services import [semistandard](https://github.com/standard/semistandard) as an npm `devDependecy`.
* But I don't think any developers of this repo actually uses it.
* Services affected:
  * currencyservice
https://github.com/GoogleCloudPlatform/microservices-demo/blob/d8936827909bcf18d554dce5064671f9465e115e/src/currencyservice/package.json#L24
  * paymentservice
https://github.com/GoogleCloudPlatform/microservices-demo/blob/d8936827909bcf18d554dce5064671f9465e115e/src/paymentservice/package.json#L24
* We need to:
* [ ] Double check that [semistandard](https://github.com/standard/semistandard) isn't being used in a meaningful way.
* [ ] Delete [semistandard](https://github.com/standard/semistandard) usage.

### What purpose/environment will this feature serve? 
* This is a clean-up task.
* This will help reduce the bloat of this app.

### Additional Info
* This is related to https://github.com/GoogleCloudPlatform/microservices-demo/issues/675.

**Comment by bourgeoisor** [comment]
I think we should still do this. Commenting to reset SLO.
