### ISSUE TITLE
Remove `pyyaml==6.0` as Direct Dependency

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/microservices-demo#713]
### Describe request or inquiry 
* This is regarding the Python services, `recommendationservice`.
* See https://github.com/GoogleCloudPlatform/microservices-demo/pull/711.
* In the above pull-request, we updated the (indirect) dependency `pyyaml` to `6.0` by adding it to the `requirements.in` file (as a "direct" dependency) and specifying the version we want (`6.0`).
* `recommendationservice` was only using `pyyaml` because of `google-python-cloud-debugger`.
* Eventually, when `google-python-cloud-debugger` upgrades its version of `pyyaml`, we will need to upgrade `google-python-cloud-debugger` and remove `pyyaml` from `requirements.in`.

### What purpose/environment will this feature serve? 
* This is a clean-up.

**Comment by mathieu-benoit** [comment]
Should be fixed by https://github.com/GoogleCloudPlatform/microservices-demo/pull/985
