### ISSUE TITLE
Enable dependabot to use pip-compile by default

### ISSUE THREAD

**Issue by ckim328** [GoogleCloudPlatform/microservices-demo#725]
### Describe request or inquiry 
When dependabot creates a PR update in our python microservices, currently it defaults to updating our generated `requirements.txt`, however our `requirements.in` are the files that actually specify the dependency
We saw this behavior in https://github.com/GoogleCloudPlatform/microservices-demo/pull/717, which had to be addressed in a manually created [PR](https://github.com/GoogleCloudPlatform/microservices-demo/pull/723)

### What purpose/environment will this feature serve? 
Dependabot PRs will make the necessary change to the correct file

**Comment by bourgeoisor** [comment]
PR merged and I just asked Renovate to re-run in this repository (it might take an hour or two). Closing.
