### ISSUE TITLE
Provide tagged releases/images

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#75]
It should be easy for someone who is just playing with this or deploying this app for a demo to take YAMLs and apply them to the cluster.

This requires:
1. tagging git releases
2. making pre-built container images available on gcr publicly (with :tags)
3. since tutorials etc will rely on this, also need long-term storage for images (e.g. `gcr.io/google-samples`)

**Comment by orthros** [comment]
I've done something similar to this using cloud build. I followed the example in https://github.com/GoogleCloudPlatform/endpoints-grpcrest-python/tree/part-2

**Comment by m-okeefe** [comment]
I can take this!

**Comment by ahmetb** [comment]
@m-okeefe Great! I'm interested in hearing a strawman design first, don’t invest too much into coding just yet.

**Comment by m-okeefe** [comment]
One way we could do this @ahmetb - 

## Setup (one-time)
- create long-lived GCP project where the Cloud Build trigger will live 
- authorize that project’s Cloud Builder svc account to push to `google-samples`  GCR
- create static yamls in `dist/kubernetes-manifests` with image tags (vs. existing skaffold yamls which have no tags) 

## Release flow: 
1. Repo owner manually tags a release against the master branch. 
2. Release publish triggers GCB, which builds all images with that release tag 
3. GCB pushes all images to GCR 
4. GCP clobbers static manifests to use the new tag (via `sed`)

I forked this repo and tested it out - created a new release against master, and triggered GCB on it:
<img width="1037" alt="screen shot 2019-01-24 at 3 43 50 pm" src="https://user-images.githubusercontent.com/3137106/51715842-2fbbea80-1fef-11e9-9327-1ccb8f8d23a6.png">

### Open Questions 

1. Should the GCB trigger actually live in the `google-samples`  project, not in a new separate project? 
2. Should we hook the end of the GCB pipeline into a success/failure system? (example: email notification for repo owners?) 
3. Should release tagging be manual? Or should patch releases automatically get published, on every merge into master.

**Comment by ahmetb** [comment]
> GCP clobbers static manifests to use the new tag (via `sed`)

this is unclear to me. Do you think trigger should make a commit to the repo back with the dist/* edited? (If so, that would be $TAG + 1 commit.)

I'm also often -1 about robots committing changes unless we have a reliable system. It makes the release process hidden away which isn't easily traceable from the repo.

> Should the GCB trigger actually live in the `google-samples`  project, not in a new separate project?

This would work better if we go GCB trigger route.

> 3. Should release tagging be manual? Or should patch releases automatically get published, on every merge into master.

I actually don't know if we need a GCB trigger. I personally don't mind a release script like:


```
export TAG=v0.1.2
./hack/make-release.sh # which updates dist/*, and builds, pushes changes
```

I suspect we'll have releases rarely (every 3-4 months) so I wonder if we're over-optimizing with GCB triggers. Thoughts?

**Comment by m-okeefe** [comment]
on YAML clobbering - yes, I suppose it would have to be GCB doing a robot-commit. I agree that this could get messy. (possibly a long-term incentive to put manifests in their own repo?) 

A script would also work! Few Qs:
- Will this script be run manually? / Do you envision someone manually setting `TAG` before running that?
- How do we ensure that script has been run?

**Comment by ahmetb** [comment]
Asking the real questions...

> * Will this script be run manually? / Do you envision someone manually setting `TAG` before running that?

So far I've done this for multiple projects with a proper RELEASING.md or MAINTENANCE.md, but this is certainly prone to human-error like humans not running it. :)

> * How do we ensure that script has been run?

Realistically we can't unless we build a release machinery around it. I envision for many releases humans doing manually `git tag`+`git push --tags`. We can't really insert a layer in-between to prevent this.

**Comment by ahmetb** [comment]
> I suppose it would have to be GCB doing a robot-commit

once you do this the problem becomes that the .yaml files will refer to tag `:$COMMIT1` but pushing the .yaml will cause repo to move onto `:$COMMIT2`.

So when you try to download the .yaml from `https://.../tree/$COMMIT2/dist/deploy.yaml`, despite the URL says `$COMMIT2`, you're getting images of `$COMMIIT1`.

You can read COMMIT as TAG above as well, my point is that unless we do it _before_ the tag, the file referring to `:$TAG` will be added after the tag is pushed.
