### ISSUE TITLE
Update skaffold config for compatibility with newer versions

### ISSUE THREAD

**Issue by davidstanke** [GoogleCloudPlatform/microservices-demo#76]
Running `skaffold run` on v 0.16.0 gives error: ``config version out of date: run `skaffold fix` ``

...fortunately, `skaffold fix` seems to work but we should prob. update the config. I'm not too familiar with backwards-compatibility in skaffold. Should we add STTEO 'minimum skaffold version' to the documentation?

**Comment by ahmetb** [comment]
We fixed in #72 and skaffold broke it again smh.
