### ISSUE TITLE
Update `skaffold` in `cloudbuild.yaml`

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/microservices-demo#761]
### Describe the bug 

* Our `skaffold.yaml` uses `skaffold` "Modules" — added in https://github.com/GoogleCloudPlatform/microservices-demo/pull/609.
* But the our `cloudbuild.yaml` file in the root directory uses `skaffold` **v0.20.0** which doesn't support `skaffold` "Modules".
https://github.com/GoogleCloudPlatform/microservices-demo/blob/8cd3ae52c93b2c5be5808c47bbfba1f8002ea13e/cloudbuild.yaml#L28
* We need to:
  * [ ] Update the version of `skaffold` being used to at least 1.27 (ideally, the latest) in the above `cloudbuild.yaml` file (in a new branch).
  * [ ] Test that updated `cloudbuild.yaml` file by creating a Google Cloud Build Trigger targeting the new branch.
  * [ ] Merge changes into `main`.
 * This issue was discovered in #752.

### To Reproduce 

* We would have to create a Google Cloud Build Trigger pointing to the `cloudbuild.yaml` file in `main`.

### Logs  

* I have not tested this breakage manually, but I assume we should see a message similar to [this](https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/514#pullrequestreview-713779181) in the Google Cloud Build Trigger's logs:
```
WARN[0000] Your Skaffold version might be too old. Download the latest version (1.28.1) from:
  https://github.com/GoogleContainerTools/skaffold/releases/tag/v1.28.1
parsing skaffold config: error parsing skaffold configuration file: unknown skaffold config API version "skaffold/v2beta18". Set the config 'apiVersion' to a known value. Check https://skaffold.dev/docs/references/yaml/ for the list of valid API versions. Otherwise, check that your skaffold version is up-to-date.
```

### Screenshots 

N/A

### Environment 
* Google Cloud Build

### Additional context 

N/A

### Exposure 

* This has been broken for a while now (`skaffold` modules was [added in Oct 2021](https://github.com/GoogleCloudPlatform/microservices-demo/pull/609)).
* We don't have data on how many people are relying on our `cloudbuild.yaml` file (i.e., for learning/demo purposes) — I assume it's minimal.

**Comment by mathieu-benoit** [comment]
Fixed by https://github.com/GoogleCloudPlatform/microservices-demo/pull/885 with explanation there.
