### ISSUE TITLE
currencyservice - unable to access external endpoint with istio

### ISSUE THREAD

**Issue by mukundha** [GoogleCloudPlatform/microservices-demo#80]
Currency service uses this endpoint - `http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml`

Maybe this could be recent change to the endpoint, but it redirect to a https URL, 
so if we enable Istio, we run into the issue described [here](https://istio.io/blog/2018/egress-https/#tls-origination-by-istio)

there are 2 options 
1) Open all egress traffic [diasble istio introspection]
2) maybe find another alternative or host a http equivalent of this endpoint?

Thanks,

**Comment by ahmetb** [comment]
Indeed, the change now poses a problem.

Another good option is to actually hardcode the conversion rates. We only use a few of them anyway. If you have time to refactor the currencyservice to use hardcoded conversion rates, it would be much appreciated.

**Comment by ahmetb** [comment]
cc: @ace-n also, #82.
We might need to hardcode the currency conversion values into the service. This has a potential of breaking live on-stage demos since we don't control it.

**Comment by ahmetb** [comment]
We removed the external dependency, so this should now be obsolete.
