### ISSUE TITLE
setCurrency and checkout failing 100% of requests on Locust

### ISSUE THREAD

**Issue by vskevakis** [GoogleCloudPlatform/microservices-demo#822]
Running the loadgenerator locally, either on venv or on a docker container (with the Dockerfile provided), all the setCurrency and checkout requests are failing. Checking on frontend webpage, everything works as it should be ( you can change currency and checkout). Same thing on Postman. 

I checked the loadgenerator (that runs on my cluster) logs and I saw that everything is normal there too,

### Environment 
Kubernetes environment on Google Cloud ( 1.21.10-gke.2000 )
Docker engine v20.10.7 - Windows 11
Conda venv with installed loadgenerator requirements.

**Comment by vskevakis** [comment]
A small update. I copied the loadgenerator image, turned off the headless mode so I can access the UI with port-forwarding and pushed it into dockerhub.  I then loaded this image to my deployment and I am able to apply requests directly from the loadgenerator deployment.

I noticed that if I use the internal address (frontend:80) I can use the setCurrency and checkout requests. When I use the external address I got from istio-ingressgateway, that's when I get the fails on the above requests.

Hope that's helpful,
Cheers

**Comment by mathieu-benoit** [comment]
Hi @vskevakis, sorry for the delay on this, but just to make sure, are you running the apps locally with Docker? Or on your local Kubernetes cluster with Kind/Minikube?

Also, could you confirm that it is working on your Kubernetes environment on Google Cloud? Is it on GKE?

Also, could you share the logs of the application in errors please?

Thanks!

**Comment by xtineskim** [comment]
seeing that the above info is in the initial comment - any help needed with this @NimJay ? (also just cooling down from our SLO!)

**Comment by NimJay** [comment]
Hi vskevakis@,

In this GitHub issue, we are not running the `loadgenerator` inside the same Kubernetes cluster (as the rest of the Online Boutique service).
Unfortunately, running the `loadgenerator` _**outside**_ the Kubernetes cluster (that Online Boutique is deployed to) is not a use case we currently have the bandwidth to support. :( Sorry. 

Please feel free to re-open this GitHub issue if I misinterpreted (i.e., if you are in fact running the `loadgenerator` inside your GKE cluster).
