### ISSUE TITLE
Remove src/cartservice/.vs

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#83]
https://github.com/GoogleCloudPlatform/microservices-demo/tree/master/src/cartservice/.vs/cartservice

This directory probably should not be checked in. Contains many binary/cache files. If there's config, we can keep it, but I couldn't find it as such.

**Comment by orthros** [comment]
.vs is a utility folder for Visual Studio 2017, and is usually ignored in most .NET projects

https://github.com/github/gitignore/blob/master/VisualStudio.gitignore#L29
