### ISSUE TITLE
Deprecate the use of Google Cloud Debugger

### ISSUE THREAD

**Issue by bourgeoisor** [GoogleCloudPlatform/microservices-demo#836]
Since Cloud Debugger is getting deprecated (doc: https://cloud.google.com/debugger/docs), we should remove it altogether and potentially replace it with Snapshot Debugger (https://github.com/GoogleCloudPlatform/snapshot-debugger)

Cloud Debugger is currently embedded in some services (for example, https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/src/recommendationservice/recommendation_server.py#L128)

Additionally, we should look into closing any potentially-no-longer-relevant issues, for example:
- https://github.com/GoogleCloudPlatform/microservices-demo/issues/538
- https://github.com/GoogleCloudPlatform/microservices-demo/issues/645
- https://github.com/GoogleCloudPlatform/microservices-demo/issues/832

**Comment by ckim328** [comment]
Snapshot debugger only supports Node.js debug agent in preview mode still, looks like Python3 support will come eventually?

**Comment by mathieu-benoit** [comment]
Is it something you could help with during one of your next rotations @arbrown or @minherz?

**Comment by eti-tme-tim** [comment]
Can we ensure that the cloud debugger replacement also has corresponding aarch64 support?

**Comment by xtineskim** [comment]
we can try to look into it! for now docs are showing that Cloud debugger will be deprecated May 31, 2023
(https://cloud.google.com/debugger/docs/deprecations)

**Comment by NimJay** [comment]
Thanks, @xtineskim, for pointing out that the `Snapshot Debugger` will [lose support after Aug 31, 2023](https://github.com/GoogleCloudPlatform/snapshot-debugger#support-period):
> Snapshot Debugger and associated agents will be supported until Aug 31, 2023, after which they will be archived and frozen.
In that case, I don't think we should use Snapshot Debugger at all.

We should still remove all instances (inside Online Boutique) of Cloud Debugger being used.
