### ISSUE TITLE
Introducing bug in ProductCatalogService for demos

### ISSUE THREAD

**Issue by MrTrustor** [GoogleCloudPlatform/microservices-demo#84]
Hi,

As discussed offline with @ahmetb, I introduced a bug in ProductCatalogService for a keynote demo of Next London 18.

I had some constraints for this demo:
- The bug needed to consume some CPU cycles for the problem to be easily visible in Stackdriver Profiler
- I needed to be able to trigger the bug without having to recreate a pod: in the new Stackdriver IRM product, we can show correlations between an alert and an other metric. It's easier with an existing pod: if you trigger the bug with a new pod, it's harder to get a correlation because all metrics for the pod began exactly at the same time.

Here is what I came up with:
- The bug is just a loop in the `parseCatalog` function that runs for 200 microseconds. This loop consumes some CPU cycles.
- The bug is triggered by a SIGUSR1, and removed (if needed) by SIGUSR2.

I think that this bug can be useful to other people for other demos.
Should I push a PR for that?

**Comment by ahmetb** [comment]
Overall sounds like a good plan. I noted a few things:

> * The bug is just a loop in the `parseCatalog` function that runs for 200 microseconds

In the currently checked in code, parseCatalog runs for 1s (slowing down all GetProduct requests). See [this image](https://user-images.githubusercontent.com/159209/47306282-d489ee80-d5e0-11e8-947a-145351d58f42.png).

So your 200us slowing down won't even be noticable. I'd say, just convert the 1s latency toggle-able.

> * The bug is triggered by a SIGUSR1, and removed (if needed) by SIGUSR2.

It's a great and clean way trigger it via signals. But I don't think kubectl can signal pods. (https://github.com/kubernetes/kubernetes/issues/24957) What do you have in mind to actually make this work?

**Comment by MrTrustor** [comment]
> In the currently checked in code, parseCatalog runs for 1s (slowing down all GetProduct requests).

Not really. parseCatalog is called _a lot_ when displaying specific pages of the website (a little bit on the home page, a lot on a product page), that's why we see a second in Profiler. I'd also argue that a second of delay is not enough to show slowness during a demo.
The [current code](https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/src/productcatalogservice/server.go#L148) is slow because it reads the catalog from a json file, but a single call to parseCatalog is still in the order of the hunder of microsecond. Using a loop with a defined runtime allows to more easily tweak how slow the website is.

> What do you have in mind to actually make this work?

I've been using `kubectl exec $(kubectl get pods -l app=productcatalogservice -o name | cut -d/ -f2) -c server -- kill -USR1 1`. Obviously, we would document that.

**Comment by ahmetb** [comment]
Sounds good. I think we can document this in productcatalog readme.

I think we can toggle a sleep betweeen 0 and 300ms (something noticable) every time
we receive a USR1. An alternative would be to handle both USR1/USR2 and use these to turn on/off.

**Comment by HelgIn** [comment]
Hello! I have a problem with this feature, hope you can help me. I use this on GKE to slowdown productcatalogservice and it works fine, but after some minutes I got **'panic: runtime error: invalid memory address or nil pointer dereference'** on **server.go:256**. Did you have this problem sometime? I wonder can it be because of CPU limit in deployment yaml? Currently I have 200mCores.

![online-boutique-pod-restarted](https://user-images.githubusercontent.com/4518644/106009990-45ba8500-60b9-11eb-8cae-2c46130a2e8d.png)
