### ISSUE TITLE
Remove code for Jaeger integration

### ISSUE THREAD

**Issue by ahrarmonsur** [GoogleCloudPlatform/microservices-demo#947]
### Describe request or inquiry 
The repo includes unused code and YAML configs related to Jaeger tracing, which has been replaced by showcasing Google Cloud Operations. As such, Jaeger-related code and documentation should be deprecated and removed.

### What purpose/environment will this feature serve? 
Since we now showcase Google CloudOps has our tracing agent, and we don't maintain a Jaeger variant of OnlineBoutique, it would make sense to remove the related code from the main stream.

From @askmeegs:
> The jaeger support in Online Boutique predates my time at Google, but my understanding is that it was designed as an OSS integration for tracing if the user didn't want to use Cloud Tracing (formerly Stackdriver Tracing). 
But right now the toggles for tracing enable/disable both Jaeger and Cloud Tracing at the same time. 🤷🏼 https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/src/shippingservice/main.go#L206 
I think given that Online Boutique is a first party GCP demo designed to showcase GCP, it's okay to remove Jaeger from the upstream.

**Comment by mathieu-benoit** [comment]
Any advice from @minherz or @arbrown?

Also, just making sure we have visibility of this, we have 2 issues open regarding Jaeger:
- https://github.com/GoogleCloudPlatform/microservices-demo/issues/385
- https://github.com/GoogleCloudPlatform/microservices-demo/issues/635

**Comment by mathieu-benoit** [comment]
Closing this one as Jaeger has been removed from the project: https://github.com/GoogleCloudPlatform/microservices-demo/pull/1088, coming in 0.3.11.
