### ISSUE TITLE
is there a http version instead of gRPC?

### ISSUE THREAD

**Issue by ryuxin** [GoogleCloudPlatform/microservices-demo#957]
Is it possible to replace gRPC with http?

Or any suggested microservice demo which only relies on http for communication?

Thanks a lot

**Comment by NimJay** [comment]
Great question!
The microservices in [Bank of Anthos](https://github.com/GoogleCloudPlatform/bank-of-anthos/) use HTTP.
Bank of Anthos was actually inspired by developers that had similar requests (i.e., wanted an HTTP-based, non-gRPC sample app) — so it's nice to see validation. Thanks, @ryuxin! 😄

**Comment by NimJay** [comment]
**Can we replace Online Boutique gRPC with HTTP?**
That would be a large overhaul.
There is no plan to do so — and there likely never will be (since Bank of Anthos exists).
