### ISSUE TITLE
Can I get tracing data and monitoring metrics on local kubernetes platform?

### ISSUE THREAD

**Issue by JackGzj** [GoogleCloudPlatform/microservices-demo#99]
I am doing an experiment using the hipster shop demo and I want to deploy it on my only kubernetes cluster and I am interested in the opencensus tracing data and monitoring metrics, can I get this data locally or I have to use the GCP？

**Comment by ahmetb** [comment]
When deployed to GCP, it exports the distributed tracing data to Stackdriver.
When you run locally, I believe OC by default spits out the trace info to STDOUT/STDERR –feel free to try it out.

I think at some point we'll add non-Stackdriver exporters (like Zipkin or Jaeger maybe). Until then this is all we got.
